// mobile/uni-app/src/components/AssetCenter.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { session } from '../lib/session';
import { t, dateTime } from '../lib/i18n';
import { go } from '../lib/navigation';
import { exactAmount, displayMoney } from '../generated/exact-amount';
import type { AssetOverview } from '../lib/assets';
import UiIcon from './UiIcon.vue';
import AssetIcon from './AssetIcon.vue';
import ActivityList from './ActivityList.vue';
import GrowthCampaign from './GrowthCampaign.vue';
const props = defineProps<{ overview: AssetOverview; prerequisite?: string }>();
const expanded = ref(false);
const key = 'balance-hidden:' + session.value?.user?.id;
const hidden = ref(uni.getStorageSync(key) === '1');
function toggle() {
    hidden.value = !hidden.value;
    uni.setStorageSync(key, hidden.value ? '1' : '0');
}
const usdt = computed(() => props.overview.assets.find((a) => a.asset === 'USDT'));
const tabs = computed(() => [
    ...(usdt.value
        ? [
              {
                  id: 'deposit',
                  label: 'Security deposit',
                  amount: usdt.value.deposit,
                  asset: 'USDT',
                  path: '/security-deposit',
                  icon: 'shield-check',
              },
          ]
        : []),
    ...props.overview.assets.map((a) => ({
        id: a.asset,
        label: a.asset,
        amount: a.available,
        asset: a.asset,
        path: '/funds?asset=' + a.asset,
        icon: '',
    })),
    ...(usdt.value && expanded.value
        ? [
              {
                  id: 'wealth',
                  label: 'Wealth management',
                  amount: null,
                  asset: 'USDT',
                  path: '/wealth',
                  icon: 'coins',
              },
          ]
        : []),
]);
const recent = computed(() =>
    props.overview.assets
        .flatMap((a) => a.activity.map((row) => ({ ...row, asset: a.asset })))
        .sort((a, b) => b.time.localeCompare(a.time) || b.id.localeCompare(a.id))
        .slice(0, 5),
);
const shortcuts = computed(() => [
    {
        label: 'Top up',
        icon: 'arrow-down',
        path:
            props.prerequisite ??
            '/assets/operate?mode=deposit&asset=' +
                (props.overview.assets.find((a) => a.rails.some((r) => r.deposit))?.asset ??
                    'USDT'),
    },
    {
        label: 'Withdraw',
        icon: 'arrow-up',
        path:
            props.prerequisite ??
            '/assets/operate?mode=withdrawal&asset=' +
                (props.overview.assets.find((a) => a.rails.some((r) => r.withdrawal))?.asset ??
                    'USDT'),
    },
    {
        label: 'Exchange',
        icon: 'arrow-left-right',
        path:
            props.prerequisite ??
            '/assets/operate?mode=exchange&asset=' +
                (props.overview.assets.find((a) => a.exchange)?.asset ?? 'USDC'),
    },
    {
        label: 'Transfer',
        icon: 'arrow-left-right',
        path: props.prerequisite ?? (usdt.value?.transfer ? '/wallet/transfer' : '/wallet'),
    },
]);
const priceLabel = computed(() =>
    props.overview.estimate === null
        ? t('Valuation unavailable. Original balances are unchanged.')
        : props.overview.updatedAt
          ? t('Prices updated: {{time}}', { time: dateTime(props.overview.updatedAt) })
          : '',
);
function show(value: string | null) {
    return hidden.value ? '••••••' : value === null ? '—' : exactAmount(value);
}
</script>
<template>
    <view class="asset-center"
        ><view class="balance-hero"
            ><view class="balance-label"
                ><text>{{ t('Estimated total assets') }}</text
                ><button
                    class="visibility"
                    :aria-label="t(hidden ? 'Show balance' : 'Hide balance')"
                    @click="toggle"
                >
                    <UiIcon :name="hidden ? 'eye-off' : 'eye'" :size="18" /></button></view
            ><view class="balance-value"
                ><text>{{
                    overview.estimate === null
                        ? '—'
                        : '≈ ' + (hidden ? '••••••' : displayMoney(overview.estimate))
                }}</text
                ><text class="balance-currency">USDT</text></view
            ><text v-if="priceLabel" class="price-label">{{ priceLabel }}</text></view
        ><view class="asset-actions"
            ><button
                v-for="shortcut in shortcuts"
                :key="shortcut.label"
                class="asset-action"
                @click="go(shortcut.path)"
            >
                <view class="action-icon"><UiIcon :name="shortcut.icon" :size="22" /></view
                ><text>{{ t(shortcut.label) }}</text>
            </button></view
        ><view v-if="!overview.activation.qualified" class="activation-notice"
            ><UiIcon name="shield-check" :size="20" /><view class="grow"
                ><text class="activation-title">{{ t('Account pending activation') }}</text
                ><text class="activation-copy">{{
                    t('Pay a member deposit or choose an agent level to activate.')
                }}</text></view
            ><button @click="go('/promotion/membership')">{{ t('Activate now') }}</button></view
        ><view class="account-panel"
            ><view class="panel-heading"
                ><text>{{ t('Accounts') }}</text
                ><button class="more" @click="expanded = !expanded">
                    {{ t(expanded ? 'Show less' : 'More')
                    }}<UiIcon name="chevron-right" :size="14" /></button></view
            ><view class="account-track" :class="{ expanded }"
                ><button
                    v-for="tab in tabs"
                    :key="tab.id"
                    class="account-tile"
                    :aria-label="t(tab.label)"
                    @click="go(tab.path)"
                >
                    <view v-if="tab.icon" class="managed-symbol"
                        ><UiIcon :name="tab.icon" :size="20" /></view
                    ><AssetIcon v-else :asset="tab.asset" /><view
                        v-if="tab.id !== 'wealth'"
                        class="tile-balance"
                        ><text>{{ show(tab.amount) }}</text
                        ><text v-if="tab.icon" class="tile-currency">USDT</text></view
                    ><text class="tile-label">{{ t(tab.label) }}</text>
                </button></view
            ></view
        ><GrowthCampaign /><view class="activity-panel"
            ><view class="panel-heading"
                ><text class="semibold">{{ t('Latest transactions') }}</text
                ><button class="more" @click="go('/funds')">
                    {{ t('More') }}<UiIcon name="chevron-right" :size="14" /></button></view
            ><ActivityList :items="recent" :hidden="hidden" /></view
    ></view>
</template>
<style scoped>
.asset-center {
    display: flex;
    flex-direction: column;
    gap: 16px;
}
.balance-hero {
    padding: 4px 8px;
    text-align: center;
}
.balance-label {
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 12px;
    color: #68736e;
}
.visibility {
    width: 44px;
    height: 44px;
    padding: 0;
    background: transparent;
    display: flex;
    align-items: center;
    justify-content: center;
}
.balance-value {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    align-items: baseline;
    column-gap: 8px;
    font-size: 30px;
    font-weight: 600;
    letter-spacing: -0.025em;
    line-height: 36px;
    overflow-wrap: anywhere;
}
.balance-currency {
    font-size: 16px;
    font-weight: 400;
    white-space: nowrap;
}
.price-label {
    display: block;
    margin-top: 8px;
    font-size: 11px;
    color: #68736e;
}
.asset-actions {
    display: flex;
    justify-content: space-evenly;
    gap: 8px;
    padding: 0 4px 4px;
}
.asset-action {
    display: flex;
    min-width: 0;
    flex: 1;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    border-radius: 12px;
    font-size: 12px;
    color: #68736e;
    background: transparent;
    padding: 0;
    line-height: 1.5;
}
.action-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 48px;
    height: 48px;
    background: #171915;
    border-radius: 50%;
}
.action-icon :deep(image) {
    filter: brightness(0) invert(1);
}
.activation-notice {
    display: flex;
    align-items: center;
    gap: 12px;
    background: #f2f6ef;
    border-radius: 16px;
    padding: 12px 16px;
}
.grow {
    flex: 1;
    min-width: 0;
}
.activation-title {
    display: block;
    font-size: 14px;
    font-weight: 600;
}
.activation-copy {
    display: block;
    margin-top: 4px;
    font-size: 12px;
    line-height: 20px;
    color: #68736e;
}
.activation-notice button {
    flex-shrink: 0;
    background: #193c34;
    color: white;
    border-radius: 999px;
    padding: 10px 12px;
    font-size: 12px;
    line-height: 16px;
}
.account-panel,
.activity-panel {
    border-radius: 16px;
    background: #fff;
    padding: 0 16px 16px;
}
.activity-panel {
    padding-bottom: 8px;
}
.panel-heading {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 12px;
    min-height: 56px;
    font-size: 16px;
    font-weight: 500;
}
.more {
    display: flex;
    align-items: center;
    gap: 4px;
    min-height: 44px;
    border-radius: 8px;
    background: transparent;
    font-size: 12px;
    color: #68736e;
    padding: 0;
    line-height: 20px;
}
.account-track {
    display: flex;
    gap: 12px;
    overflow-x: auto;
    padding-bottom: 4px;
}
.account-track.expanded {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
}
.account-tile {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    min-width: 96px;
    width: calc((100% - 24px) / 3);
    flex-shrink: 0;
    background: #f7f6f1;
    border-radius: 12px;
    padding: 12px 8px;
    line-height: 20px;
}
.expanded .account-tile {
    min-width: 0;
    width: 100%;
}
.managed-symbol {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 50%;
    background: #d1fae5;
}
.tile-balance {
    margin-top: 8px;
    display: flex;
    justify-content: center;
    align-items: baseline;
    gap: 4px;
    width: 100%;
    min-width: 0;
    font-size: 14px;
    font-weight: 500;
}
.tile-balance > text:first-child {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
.tile-currency {
    font-size: 10px;
    font-weight: 400;
    flex-shrink: 0;
}
.tile-label {
    display: block;
    margin-top: 4px;
    width: 100%;
    overflow-wrap: anywhere;
    font-size: 12px;
    color: #68736e;
}
.semibold {
    font-weight: 600;
}
@media (min-width: 640px) {
    .balance-value {
        font-size: 36px;
        line-height: 40px;
    }
    .action-icon {
        width: 56px;
        height: 56px;
    }
    .account-panel,
    .activity-panel {
        padding-left: 20px;
        padding-right: 20px;
    }
    .account-track.expanded {
        grid-template-columns: repeat(6, minmax(0, 1fr));
    }
    .account-tile {
        flex: 1;
    }
}
</style>

// resources/js/components/user/AssetCenter.tsx
import { exactAmount, displayMoney } from '@/lib/exact-amount';
import { useState, useSyncExternalStore } from 'react';
import { Link, usePage } from '@inertiajs/react';
import type { SharedProps } from '@/types/global';
import {
    Eye,
    EyeOff,
    ArrowDown,
    ArrowUp,
    ArrowLeftRight,
    ChevronRight,
    ShieldCheck,
    Coins,
} from 'lucide-react';
import { t, dateTime } from '@/i18n';
import { GrowthCampaign } from '@/components/user/GrowthCampaign';

export type AssetAccount = {
    asset: string;
    available: string;
    held: string;
    deposit: string;
    exchange: boolean;
    exchangeUnavailableReason?: string | null;
    transfer?: boolean;
    rails: {
        code: string;
        network: string;
        deposit: boolean;
        withdrawal: boolean;
        feePercent: string | null;
        minimum: string | null;
    }[];
    activity: { id: string; kind: string; amount: string; time: string }[];
    orders?: { id: string; mode: string; amount: string; state: string; time: string }[];
};
export type AccountActivation = {
    qualified: boolean;
    agent: boolean;
    rank: number;
    endsAt: string | null;
    ordinaryAvailable: boolean;
    depositSatisfied: boolean;
    depositRequired: string;
    depositCurrent: string;
    depositRemaining: string;
    refundPending: boolean;
};
export type AssetOverview = {
    activation: AccountActivation;
    cumulativeCommission: string;
    assets: AssetAccount[];
    estimate: string | null;
    updatedAt: string | null;
};
const colors: Record<string, string> = {
    USDT: 'bg-emerald-600',
    USDC: 'bg-blue-600',
    ETH: 'bg-indigo-500',
    BTC: 'bg-orange-500',
};
export function AssetIcon({ asset }: { asset: string }) {
    return (
        <span
            aria-hidden
            className={`flex size-9 shrink-0 items-center justify-center rounded-full text-lg font-semibold text-white ${colors[asset]}`}
        >
            {({ USDT: '₮', USDC: '$', ETH: 'Ξ', BTC: '₿' } as Record<string, string>)[asset]}
        </span>
    );
}
export function AssetCenter({
    overview,
    prerequisiteHref,
}: {
    overview: AssetOverview;
    prerequisiteHref?: string;
}) {
    const [expanded, setExpanded] = useState(false);
    const { auth } = usePage<SharedProps>().props;
    const key = `balance-hidden:${auth.user?.id ?? 'guest'}`;
    const hidden = useSyncExternalStore(
        (listener) => {
            window.addEventListener('balance-visibility', listener);
            return () => window.removeEventListener('balance-visibility', listener);
        },
        () => {
            try {
                return sessionStorage.getItem(key) === '1';
            } catch {
                return false;
            }
        },
        () => false,
    );
    const setHidden = (value: boolean) => {
        try {
            sessionStorage.setItem(key, value ? '1' : '0');
        } catch {
            /* Browser storage can be unavailable. */
        }
        window.dispatchEvent(new Event('balance-visibility'));
    };
    const current = overview.assets.find((a) => a.asset === 'USDT') ?? overview.assets[0];
    if (!current) return null;
    const show = (value: string | null) =>
        hidden ? '••••••' : value === null ? '—' : exactAmount(value);
    const usdt = overview.assets.find((a) => a.asset === 'USDT');
    const managedAccounts = usdt
        ? [
              {
                  id: 'deposit',
                  label: 'Security deposit',
                  amount: usdt.deposit,
                  href: '/security-deposit',
                  icon: ShieldCheck,
              },
          ]
        : [];
    const tabs = [
        ...managedAccounts.map((a) => ({ ...a, asset: 'USDT' })),
        ...overview.assets.map((a) => ({
            id: a.asset,
            label: a.asset,
            amount: a.available,
            asset: a.asset,
            icon: null,
            href: `/funds?asset=${a.asset}`,
        })),
        ...(usdt && expanded
            ? [
                  {
                      id: 'wealth',
                      label: 'Wealth management',
                      amount: null,
                      asset: 'USDT',
                      href: '/wealth',
                      icon: Coins,
                  },
              ]
            : []),
    ];
    const depositAsset = overview.assets.find((a) => a.rails.some((r) => r.deposit));
    const withdrawalAsset = overview.assets.find((a) => a.rails.some((r) => r.withdrawal));
    const exchangeAsset =
        overview.assets.find((a) => a.asset === current.asset && a.asset !== 'USDT') ??
        overview.assets.find((a) => a.exchange) ??
        overview.assets.find((a) => a.asset !== 'USDT');
    const shortcuts = [
        {
            label: 'Top up',
            href:
                prerequisiteHref ??
                `/assets/operate?mode=deposit&asset=${depositAsset?.asset ?? 'USDT'}`,
            icon: ArrowDown,
        },
        {
            label: 'Withdraw',
            href:
                prerequisiteHref ??
                `/assets/operate?mode=withdrawal&asset=${withdrawalAsset?.asset ?? 'USDT'}`,
            icon: ArrowUp,
        },
        {
            label: 'Exchange',
            href:
                prerequisiteHref ??
                `/assets/operate?mode=exchange&asset=${exchangeAsset?.asset ?? 'USDC'}`,
            icon: ArrowLeftRight,
        },
        {
            label: 'Transfer',
            href: prerequisiteHref ?? (usdt?.transfer ? '/wallet/transfer' : '/wallet'),
            icon: ArrowLeftRight,
        },
    ];
    return (
        <div className="space-y-4">
            <section className="px-2 py-1 text-center">
                <div className="flex items-center justify-center text-xs text-muted-foreground">
                    <h1>{t('Estimated total assets')}</h1>
                    <button
                        className="flex size-11 items-center justify-center rounded-full focus-visible:outline-2"
                        onClick={() => setHidden(!hidden)}
                        aria-label={t(hidden ? 'Show balance' : 'Hide balance')}
                    >
                        {hidden ? <EyeOff size={18} /> : <Eye size={18} />}
                    </button>
                </div>
                <p className="flex flex-wrap items-baseline justify-center gap-x-2 text-3xl font-semibold tracking-tight sm:text-4xl">
                    <span className="break-all">
                        {overview.estimate === null
                            ? '—'
                            : `≈ ${hidden ? '••••••' : displayMoney(overview.estimate)}`}
                    </span>
                    <span className="whitespace-nowrap text-base font-normal">USDT</span>
                </p>
                {(overview.estimate === null || overview.updatedAt) && (
                    <p className="mt-2 text-[11px] text-muted-foreground">
                        {overview.estimate === null
                            ? t('Valuation unavailable. Original balances are unchanged.')
                            : t('Prices updated: {{time}}', {
                                  time: dateTime(overview.updatedAt!),
                              })}
                    </p>
                )}
            </section>
            {shortcuts.length > 0 && (
                <nav
                    aria-label={t('Account actions')}
                    className="flex justify-evenly gap-2 px-1 pb-1"
                >
                    {shortcuts.map((action) => (
                        <Link
                            key={action.label}
                            href={action.href}
                            className="flex min-w-0 flex-1 flex-col items-center gap-2 rounded-xl text-center text-xs text-muted-foreground focus-visible:outline-2"
                        >
                            <span className="flex size-12 items-center justify-center rounded-full bg-[#171915] text-white sm:size-14">
                                <action.icon size={22} />
                            </span>
                            <span className="break-words">{t(action.label)}</span>
                        </Link>
                    ))}
                </nav>
            )}
            {!overview.activation.qualified && (
                <section
                    aria-label={t('Account activation')}
                    className="flex items-center gap-3 rounded-2xl bg-[#f2f6ef] px-4 py-3"
                >
                    <ShieldCheck className="size-5 shrink-0 text-emerald-800" aria-hidden="true" />
                    <div className="min-w-0 flex-1">
                        <h2 className="text-sm font-semibold">{t('Account pending activation')}</h2>
                        <p className="mt-1 text-xs leading-5 text-muted-foreground">
                            {t('Pay a member deposit or choose an agent level to activate.')}
                        </p>
                    </div>
                    <Link
                        href="/promotion/membership"
                        className="shrink-0 rounded-full bg-[#193c34] px-3 py-2.5 text-xs font-medium text-white"
                    >
                        {t('Activate now')}
                    </Link>
                </section>
            )}
            <section className="rounded-2xl bg-surface px-4 pb-4 sm:px-5 sm:pb-5">
                <div className="flex min-h-14 items-center justify-between gap-3">
                    <h2 className="text-base font-medium">{t('Accounts')}</h2>
                    <button
                        onClick={() => setExpanded(!expanded)}
                        className="flex min-h-11 items-center gap-1 rounded-lg text-xs text-muted-foreground"
                        aria-expanded={expanded}
                        aria-controls="asset-accounts"
                    >
                        {t(expanded ? 'Show less' : 'More')}
                        <ChevronRight size={14} className={expanded ? '-rotate-90' : ''} />
                    </button>
                </div>
                <div
                    id="asset-accounts"
                    role="group"
                    aria-label={t('Accounts')}
                    className={
                        expanded
                            ? 'grid grid-cols-3 gap-3 pb-1 sm:grid-cols-6'
                            : 'flex gap-3 overflow-x-auto pb-1'
                    }
                >
                    {tabs.map((a) => {
                        const className = `user-asset-account flex ${expanded ? 'min-w-0' : 'w-[calc((100%_-_1.5rem)/3)] min-w-24 shrink-0 sm:flex-1'} flex-col items-center rounded-xl bg-[#f7f6f1] px-2 py-3 text-center focus-visible:outline-2`;
                        const content = (
                            <>
                                {a.icon ? (
                                    <span
                                        aria-hidden
                                        className="flex size-9 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-emerald-800"
                                    >
                                        <a.icon size={20} />
                                    </span>
                                ) : (
                                    <AssetIcon asset={a.asset} />
                                )}
                                {a.id !== 'wealth' && (
                                    <span
                                        title={a.icon ? `${show(a.amount)} USDT` : show(a.amount)}
                                        className="mt-2 flex w-full min-w-0 items-baseline justify-center gap-1 text-sm font-medium tabular-nums"
                                    >
                                        <span className="truncate">{show(a.amount)}</span>
                                        {a.icon && (
                                            <span className="shrink-0 text-[10px] font-normal">
                                                USDT
                                            </span>
                                        )}
                                    </span>
                                )}
                                <span
                                    className={`${a.id === 'wealth' ? 'mt-2' : 'mt-1'} block w-full break-words text-xs text-muted-foreground`}
                                >
                                    {t(a.label)}
                                </span>
                            </>
                        );
                        return (
                            <Link
                                key={a.id}
                                href={a.href}
                                aria-label={t(a.label)}
                                className={className}
                            >
                                {content}
                            </Link>
                        );
                    })}
                </div>
            </section>
            <GrowthCampaign variant="account" />
            {!!current.orders?.length && (
                <section>
                    <h2 className="mb-2 font-semibold">{t('Recent requests')}</h2>
                    {current.orders.map((order) => (
                        <Link
                            key={order.id}
                            href={`/assets/operate?mode=${order.mode}&asset=${current.asset}&order=${order.id}`}
                            className="flex min-h-14 items-center justify-between gap-3 border-b py-3 text-sm"
                        >
                            <div>
                                <p>
                                    {t(
                                        order.mode === 'exchange'
                                            ? 'Exchange'
                                            : order.mode === 'withdrawal'
                                              ? 'Withdrawal'
                                              : 'Top up',
                                    )}
                                </p>
                                <p className="mt-1 text-xs text-muted-foreground">
                                    {t(order.state)}
                                </p>
                            </div>
                            <span className="break-all text-right">
                                {show(order.amount)} {current.asset}
                            </span>
                            <ChevronRight className="size-4 shrink-0" />
                        </Link>
                    ))}
                </section>
            )}
        </div>
    );
}
