// mobile/uni-app/src/screens/WithdrawalHistory.vue
<script setup lang="ts">
import PageShell from '../components/PageShell.vue';
import { t, dateTime } from '../lib/i18n';
import { go } from '../lib/navigation';
import { displayMoney } from '../generated/exact-amount';
defineProps<{
    page: {
        history: {
            data: {
                id: string;
                amount: string;
                feeAmount: string;
                receiveAmount: string;
                asset: string;
                maskedAddress: string;
                requestedAt: string;
                state: string;
            }[];
            currentPage: number;
            lastPage: number;
        };
    };
}>();
const labels: Record<string, string> = {
    pending: 'Pending review',
    processing: 'Withdrawal approved',
    confirming: 'Confirming transaction',
    completed: 'Withdrawal complete',
    rejected: 'Withdrawal rejected',
    cancelled: 'Withdrawal cancelled',
};
</script>
<template>
    <PageShell :title="t('Withdrawal history')" back="/wallet/withdraw" active="assets"
        ><text v-if="!page.history.data.length" class="empty muted">{{
            t('No withdrawals yet.')
        }}</text
        ><view
            v-for="order in page.history.data"
            :key="order.id"
            class="order"
            @click="go('/wallet/withdrawals/' + order.id)"
            ><view class="body"
                ><text class="amount">{{ displayMoney(order.amount) }} {{ order.asset }}</text
                ><text class="muted">{{ order.maskedAddress }}</text
                ><template v-if="!['rejected', 'cancelled'].includes(order.state)"
                    ><text class="small muted"
                        >{{ t('Withdrawal fee') }}: {{ displayMoney(order.feeAmount) }} USDT</text
                    ><text class="small muted"
                        >{{ t('Amount to receive') }}:
                        {{ displayMoney(order.receiveAmount) }} USDT</text
                    ></template
                ><text class="small muted">{{ dateTime(order.requestedAt) }}</text></view
            ><text class="status">{{ t(labels[order.state] ?? order.state) }}</text></view
        ><view v-if="page.history.lastPage > 1" class="pages"
            ><button
                class="secondary"
                :disabled="page.history.currentPage <= 1"
                @click="go('/wallet/withdrawals?page=' + (page.history.currentPage - 1), true)"
            >
                {{ t('Previous') }}</button
            ><text>{{ page.history.currentPage }} / {{ page.history.lastPage }}</text
            ><button
                class="secondary"
                :disabled="page.history.currentPage >= page.history.lastPage"
                @click="go('/wallet/withdrawals?page=' + (page.history.currentPage + 1), true)"
            >
                {{ t('Next') }}
            </button></view
        ></PageShell
    >
</template>
<style scoped>
.empty {
    display: block;
    text-align: center;
    padding: 24px 0;
    font-size: 14px;
}
.order {
    display: flex;
    justify-content: space-between;
    gap: 16px;
    padding: 16px 0;
    border-bottom: 1px solid #e2e7e4;
}
.body {
    min-width: 0;
}
.body > text {
    display: block;
    margin-top: 4px;
    font-size: 14px;
    overflow-wrap: anywhere;
}
.body > .amount {
    font-weight: 600;
    font-size: 16px;
    margin-top: 0;
}
.body > .small {
    font-size: 12px;
}
.status {
    font-size: 14px;
    flex-shrink: 0;
}
.pages {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 16px;
    margin-top: 16px;
    font-size: 14px;
}
.pages button {
    font-size: 14px;
    margin: 0;
}
</style>

// resources/js/components/user/WithdrawalHistory.tsx
import { Link, router } from '@inertiajs/react';
import { t, dateTime } from '@/i18n';
import { MoneyDisplay } from '@/components/shared/MoneyDisplay';
import { displayMoney } from '@/lib/exact-amount';
import { Button } from '@/components/ui/button';
import type { MoneyAmount } from '@/types/global';

export type WithdrawalHistoryData = {
    data: {
        id: string;
        amount: MoneyAmount;
        feeAmount: string;
        receiveAmount: string;
        asset: string;
        maskedAddress: string;
        requestedAt: string;
        state: 'pending' | 'processing' | 'confirming' | 'completed' | 'rejected' | 'cancelled';
    }[];
    currentPage: number;
    lastPage: number;
};

const labels = {
    pending: 'Pending review',
    processing: 'Withdrawal approved',
    confirming: 'Confirming transaction',
    completed: 'Withdrawal complete',
    rejected: 'Withdrawal rejected',
    cancelled: 'Withdrawal cancelled',
};

export function WithdrawalHistory({ history }: { history: WithdrawalHistoryData }) {
    const navigate = (page: number) =>
        router.get(
            '/wallet/withdrawals',
            { page },
            {
                only: ['history'],
                preserveState: true,
                preserveScroll: true,
            },
        );
    return (
        <section className="space-y-4" aria-label={t('Withdrawal history')}>
            {history.data.length === 0 ? (
                <p className="py-6 text-center text-sm text-muted-foreground">
                    {t('No withdrawals yet.')}
                </p>
            ) : (
                <ul className="divide-y">
                    {history.data.map((order) => (
                        <li key={order.id}>
                            <Link
                                href={`/wallet/withdrawals/${order.id}`}
                                className="flex justify-between gap-4 py-4"
                            >
                                <div className="min-w-0 space-y-1">
                                    <p className="font-semibold">
                                        <MoneyDisplay amount={order.amount} asset={order.asset} />
                                    </p>
                                    <p className="text-sm text-muted-foreground">
                                        {order.maskedAddress}
                                    </p>
                                    {!['rejected', 'cancelled'].includes(order.state) && (
                                        <p className="text-xs text-muted-foreground">
                                            {t('Withdrawal fee')}: {displayMoney(order.feeAmount)}{' '}
                                            USDT
                                            <br />
                                            {t('Amount to receive')}:{' '}
                                            {displayMoney(order.receiveAmount)} USDT
                                        </p>
                                    )}
                                    <p className="text-xs text-muted-foreground">
                                        {dateTime(order.requestedAt)}
                                    </p>
                                </div>
                                <span className="shrink-0 text-sm">{t(labels[order.state])}</span>
                            </Link>
                        </li>
                    ))}
                </ul>
            )}
            {history.lastPage > 1 && (
                <div className="flex items-center justify-center gap-4">
                    <Button
                        variant="secondary"
                        size="sm"
                        disabled={history.currentPage <= 1}
                        onClick={() => navigate(history.currentPage - 1)}
                    >
                        {t('Previous')}
                    </Button>
                    <span className="text-sm tabular-nums">
                        {history.currentPage} / {history.lastPage}
                    </span>
                    <Button
                        variant="secondary"
                        size="sm"
                        disabled={history.currentPage >= history.lastPage}
                        onClick={() => navigate(history.currentPage + 1)}
                    >
                        {t('Next')}
                    </Button>
                </div>
            )}
        </section>
    );
}
