// mobile/uni-app/src/screens/AssetFlow.vue
<script setup lang="ts">
import { computed, reactive, ref, onBeforeUnmount } from 'vue';
import PageShell from '../components/PageShell.vue';
import FormField from '../components/FormField.vue';
import FormErrors from '../components/FormErrors.vue';
import SelectField from '../components/SelectField.vue';
import ConfirmCheck from '../components/ConfirmCheck.vue';
import DepositInstructions from '../components/DepositInstructions.vue';
import AssetIcon from '../components/AssetIcon.vue';
import { t, dateTime } from '../lib/i18n';
import { go } from '../lib/navigation';
import { useAction, requestId } from '../lib/client';
import { subtract, type AssetOverview } from '../lib/assets';
import { exactAmount, withdrawalPercentageFee, meetsTopupMinimum } from '../generated/exact-amount';
import { assetNetworkLabel } from '../generated/asset-network';
type Result = {
    id: string;
    asset: string;
    amount: string;
    state: string;
    network?: string;
    address?: string;
    fee?: string;
    feePercent?: string | null;
    receive?: string;
    rate?: string;
    expiresAt?: string;
    canConfirm?: boolean;
    canCancel?: boolean;
};
const props = defineProps<{
    page: {
        overview: AssetOverview;
        mode: 'deposit' | 'withdrawal' | 'exchange';
        selectedAsset: string;
        result: Result | null;
    };
}>();
const emit = defineEmits<{ reload: [] }>();
const action = useAction(),
    review = ref(false),
    reviewRate = ref<string | null>(null),
    clock = ref(Date.now());
const timer = setInterval(() => (clock.value = Date.now()), 1000);
onBeforeUnmount(() => clearInterval(timer));
const form = reactive({
    mode: props.page.mode,
    asset: props.page.selectedAsset,
    rail: '',
    amount: '',
    address: '',
    expected_fee: '',
    confirmed: false,
    request_id: requestId(),
});
const account = computed(() => props.page.overview.assets.find((a) => a.asset === form.asset)!);
const rails = computed(
    () =>
        account.value?.rails.filter((r) =>
            props.page.mode === 'deposit' ? r.deposit : r.withdrawal,
        ) ?? [],
);
const rail = computed(() => rails.value.find((r) => r.code === form.rail));
const calculatedFee = computed(() =>
    withdrawalPercentageFee(form.amount, rail.value?.feePercent ?? null, form.asset),
);
const seconds = computed(() =>
    props.page.result?.expiresAt
        ? Math.max(0, Math.ceil((Date.parse(props.page.result.expiresAt) - clock.value) / 1000))
        : 0,
);
const unavailable = computed(() =>
    props.page.mode === 'exchange' ? !account.value?.exchange : !rails.value.length,
);
const unavailableMessage = computed(() =>
    props.page.mode === 'exchange'
        ? (account.value?.exchangeUnavailableReason ?? 'Exchange is not available for this asset.')
        : props.page.mode === 'deposit'
          ? 'No deposit network is available for this currency.'
          : 'No withdrawal network is available for this currency.',
);
const title = computed(() =>
    t(
        props.page.mode === 'deposit'
            ? 'Top up'
            : props.page.mode === 'withdrawal'
              ? 'Withdraw'
              : 'Exchange to USDT',
    ),
);
const expires = computed(() =>
    t('Valid until {{time}}', { time: dateTime(props.page.result?.expiresAt ?? '') }),
);
const confirmLabel = computed(
    () => t('Confirm exchange') + ' · ' + t('{{seconds}} seconds', { seconds: seconds.value }),
);
const invalid = computed(
    () =>
        action.pending.value ||
        !form.amount ||
        (props.page.mode === 'exchange' ? !account.value?.exchange : !rail.value) ||
        (review.value && !form.confirmed) ||
        (props.page.mode === 'withdrawal' && calculatedFee.value === null) ||
        (props.page.mode === 'deposit' &&
            rail.value?.code === 'USDT_TRON' &&
            !meetsTopupMinimum(form.amount, rail.value.minimum ?? '0')),
);
function intentChanged() {
    form.request_id = requestId();
    form.confirmed = false;
    review.value = false;
}
function chooseAsset(value: string) {
    form.asset = value;
    form.rail = '';
    form.amount = '';
    form.address = '';
    form.expected_fee = '';
    intentChanged();
}
async function submit() {
    if (unavailable.value || action.pending.value) return;
    if (rail.value?.code === 'USDT_TRON') {
        if (props.page.mode === 'deposit')
            await action.submit('/wallet/top-ups', {
                request_id: form.request_id,
                requested_amount: form.amount,
            });
        else go('/wallet/withdraw');
        return;
    }
    if (props.page.mode === 'withdrawal' && !review.value) {
        if (calculatedFee.value === null) return;
        reviewRate.value = rail.value?.feePercent ?? null;
        form.expected_fee = calculatedFee.value;
        review.value = true;
        return;
    }
    await action.submit('/assets/orders', { ...form });
}
async function operation(kind: 'confirm' | 'cancel') {
    if (!props.page.result) return;
    await action.submit(
        `/assets/${kind === 'confirm' ? 'exchanges' : 'withdrawals'}/${props.page.result.id}/${kind}`,
        { confirmed: true },
        { navigate: false, success: () => emit('reload') },
    );
}
</script>
<template>
    <PageShell :title="title" back="/dashboard" active="assets"
        ><view class="flow"
            ><FormErrors :errors="action.errors.value" /><DepositInstructions
                v-if="page.result && page.mode === 'deposit'"
                :asset="page.result.asset"
                :amount="page.result.amount"
                :network="page.result.network"
                :address="page.result.address"
                :state="
                    seconds === 0 && page.result.state !== 'Completed'
                        ? 'Top-up expired'
                        : page.result.state
                "
                :expires-at="page.result.expiresAt"
                :payable="seconds > 0 && page.result.state !== 'Completed'"
                :new-href="'/assets/operate?mode=deposit&asset=' + page.result.asset"
            /><view v-else-if="page.result" class="flow-card stack"
                ><view class="result-heading"
                    ><AssetIcon :asset="page.result.asset" /><view
                        ><text class="bold block">{{ t(page.result.state) }}</text
                        ><text class="muted"
                            >{{ page.result.asset }}
                            {{
                                page.result.network
                                    ? ' · ' +
                                      assetNetworkLabel(page.result.network, page.result.asset)
                                    : ''
                            }}</text
                        ></view
                    ></view
                ><text class="result-amount"
                    >{{ exactAmount(page.result.amount) }}
                    <text class="currency">{{ page.result.asset }}</text></text
                ><text v-if="page.mode === 'withdrawal'" class="detail"
                    >{{ t('Destination address') }}: {{ page.result.address }}</text
                ><text v-if="page.result.rate" class="detail"
                    >{{ t('Exchange rate') }}: 1 {{ page.result.asset }} ≈
                    {{ exactAmount(page.result.rate) }} USDT</text
                ><text v-if="page.result.fee !== undefined" class="detail"
                    >{{ t('Platform fee') }}: {{ exactAmount(page.result.fee) }}
                    {{ page.mode === 'exchange' ? 'USDT' : page.result.asset }}
                    {{
                        page.result.feePercent != null
                            ? ' (' + exactAmount(page.result.feePercent) + '%)'
                            : ''
                    }}</text
                ><view v-if="page.result.receive" class="receive-result"
                    ><text class="muted block">{{ t('You receive') }}</text
                    ><text class="receive-amount"
                        >{{ exactAmount(page.result.receive) }}
                        {{ page.mode === 'exchange' ? 'USDT' : page.result.asset }}</text
                    ></view
                ><text v-if="page.result.expiresAt" class="small muted">{{ expires }}</text
                ><template v-if="page.mode === 'exchange' && page.result.canConfirm"
                    ><text class="muted">{{
                        t(
                            'This exchanges your available balance internally. Confirm only after reviewing the final amounts.',
                        )
                    }}</text
                    ><button
                        class="primary wide"
                        :disabled="action.pending.value || seconds === 0"
                        @click="operation('confirm')"
                    >
                        {{ confirmLabel }}
                    </button></template
                ><button
                    v-if="page.result.canCancel"
                    class="secondary wide"
                    :disabled="action.pending.value"
                    @click="operation('cancel')"
                >
                    {{ t('Cancel withdrawal') }}</button
                ><text
                    class="text-link"
                    @click="go('/assets/operate?mode=' + page.mode + '&asset=' + page.result.asset)"
                    >{{ t('Start a new request') }}</text
                ></view
            ><view v-else-if="account" class="flow-card"
                ><SelectField
                    v-model="form.asset"
                    class="asset-choice"
                    hide-label
                    :label="t('Select currency')"
                    :options="page.overview.assets.map((a) => ({ value: a.asset, label: a.asset }))"
                    :disabled="action.pending.value"
                    @update:model-value="chooseAsset"
                    ><view class="asset-choice-value"
                        ><AssetIcon :asset="form.asset" /><text>{{ form.asset }}</text></view
                    ></SelectField
                ><text class="available"
                    >{{ t('Available balance') }}: {{ exactAmount(account.available) }}
                    {{ account.asset }}</text
                ><view v-if="page.mode === 'exchange'" class="receive-box"
                    ><text class="small muted">{{ t('Receive currency') }}</text
                    ><view class="result-heading"
                        ><AssetIcon asset="USDT" /><text class="bold">USDT</text></view
                    ><text class="small muted">{{
                        t('Card opening and card top-ups use your available USDT balance.')
                    }}</text></view
                ><SelectField
                    v-if="page.mode !== 'exchange' && !unavailable"
                    v-model="form.rail"
                    hide-label
                    :placeholder="t('Select network')"
                    :label="t('Select network')"
                    :options="
                        rails.map((r) => ({
                            value: r.code,
                            label: assetNetworkLabel(r.network, form.asset) ?? r.network,
                        }))
                    "
                    :disabled="action.pending.value"
                    @update:model-value="intentChanged"
                /><text v-if="unavailable" class="unavailable">{{ t(unavailableMessage) }}</text
                ><button
                    v-else-if="rail?.code === 'USDT_TRON' && page.mode === 'withdrawal'"
                    class="primary wide"
                    @click="submit"
                >
                    {{ t('Continue') }}</button
                ><template v-else
                    ><FormField
                        v-model="form.amount"
                        :label="t('Amount') + ' · ' + account.asset"
                        type="digit"
                        :disabled="action.pending.value"
                        @update:model-value="intentChanged"
                    /><FormField
                        v-if="page.mode === 'withdrawal'"
                        v-model="form.address"
                        :label="t('Destination address')"
                        :disabled="action.pending.value"
                        :maxlength="128"
                        @update:model-value="intentChanged"
                    /><text
                        v-if="rail?.code === 'USDT_TRON' && page.mode === 'deposit'"
                        class="hint"
                        >{{ t('TRC20 · No top-up fee') }}</text
                    ><text v-if="rail?.minimum && page.mode === 'deposit'" class="hint"
                        >{{ t('Minimum deposit') }}: {{ exactAmount(rail.minimum) }}
                        {{ account.asset }}</text
                    ><text
                        v-if="
                            page.mode === 'withdrawal' &&
                            (review ? reviewRate : rail?.feePercent) != null
                        "
                        class="hint"
                        >{{ t('Withdrawal fee rate') }}:
                        {{ exactAmount((review ? reviewRate : rail?.feePercent) ?? '0') }}%
                        {{
                            (review ? form.expected_fee : calculatedFee) !== null
                                ? ' · ' +
                                  exactAmount(review ? form.expected_fee : (calculatedFee ?? '0')) +
                                  ' ' +
                                  account.asset
                                : ''
                        }}</text
                    ><view v-if="page.mode === 'withdrawal' && review" class="review-box"
                        ><text class="block"
                            >{{ assetNetworkLabel(rail?.network, form.asset) }} ·
                            {{ form.address }}</text
                        ><text class="block"
                            >{{ t('Amount') }}: {{ form.amount }} {{ account.asset }}</text
                        ><text class="block"
                            >{{ t('You receive') }}: {{ subtract(form.amount, form.expected_fee) }}
                            {{ account.asset }}</text
                        ><ConfirmCheck
                            v-model="form.confirmed"
                            :label="t('I checked the network, address and final amount.')" /></view
                    ><text v-if="page.mode === 'exchange'" class="hint">{{
                        t('The next step shows the final rate, fee and quote expiry.')
                    }}</text
                    ><button class="primary wide" :disabled="invalid" @click="submit">
                        {{
                            t(
                                page.mode === 'exchange'
                                    ? 'Get quote'
                                    : page.mode === 'withdrawal'
                                      ? review
                                          ? 'Confirm withdrawal'
                                          : 'Review withdrawal'
                                      : 'Create deposit order',
                            )
                        }}
                    </button></template
                ></view
            ><view v-if="page.mode === 'withdrawal' && !page.result" class="withdrawal-note"
                ><text>{{
                    t(
                        'USDT and USDC withdrawals incur a 10% fee. ETH and BTC withdrawals have no fee.',
                    )
                }}</text
                ><text>{{
                    t('Account-to-account transfers are free for all currencies.')
                }}</text></view
            ></view
        ></PageShell
    >
</template>
<style scoped>
.flow {
    max-width: 512px;
    margin: auto;
}
.flow-card {
    background: white;
    border-radius: 16px;
    padding: 20px;
}
.asset-choice :deep(.select-trigger) {
    background: #f0f3f1;
    border: 0;
    border-radius: 12px;
    padding: 12px;
    min-height: 60px;
}
.asset-choice-value {
    display: flex;
    align-items: center;
    gap: 12px;
    font-weight: 500;
}
.stack {
    gap: 20px;
}
.available {
    display: block;
    font-size: 12px;
    color: #68736e;
    overflow-wrap: anywhere;
    margin-bottom: 20px;
}
.result-heading {
    display: flex;
    align-items: center;
    gap: 12px;
}
.block {
    display: block;
}
.bold {
    font-weight: 600;
}
.small {
    font-size: 12px;
}
.detail {
    display: block;
    font-size: 14px;
    overflow-wrap: anywhere;
}
.result-amount {
    font-size: 30px;
    line-height: 36px;
    font-weight: 600;
    overflow-wrap: anywhere;
}
.currency {
    font-size: 16px;
}
.receive-result {
    border-top: 1px solid #e2e7e4;
    padding-top: 16px;
}
.receive-amount {
    display: block;
    font-size: 24px;
    font-weight: 600;
    line-height: 32px;
    margin-top: 4px;
    overflow-wrap: anywhere;
}
.wide {
    width: 100%;
    min-height: 48px;
    border-radius: 999px;
    padding: 12px 20px;
    font-size: 14px;
    line-height: 24px;
}
.text-link {
    display: block;
    text-align: center;
    text-decoration: underline;
    font-size: 14px;
    padding: 12px 0;
}
.receive-box {
    display: flex;
    flex-direction: column;
    gap: 8px;
    border-radius: 12px;
    background: #f0f3f1;
    padding: 16px;
    margin-bottom: 20px;
}
.unavailable {
    display: block;
    padding: 16px;
    border-radius: 12px;
    background: #f0f3f1;
    font-size: 14px;
    color: #68736e;
}
.hint {
    display: block;
    margin-bottom: 20px;
    font-size: 12px;
    color: #68736e;
    line-height: 1.6;
}
.review-box {
    padding: 16px;
    background: #f0f3f1;
    border-radius: 12px;
    font-size: 14px;
    line-height: 24px;
    margin-bottom: 20px;
    overflow-wrap: anywhere;
}
.review-box > .block + .block {
    margin-top: 12px;
}
.withdrawal-note {
    display: flex;
    flex-direction: column;
    gap: 8px;
    padding: 24px 8px 0;
    font-size: 14px;
    color: #68736e;
    line-height: 24px;
}
</style>

// resources/js/pages/user/AssetFlow.tsx
import { assetNetworkLabel } from '@/lib/asset-network';
import { DepositInstructions } from '@/components/user/DepositInstructions';
import { exactAmount, meetsTopupMinimum, withdrawalPercentageFee } from '@/lib/exact-amount';
import { useEffect, useState } from 'react';
import { Head, Link, useForm, usePage, router } from '@inertiajs/react';
import { ChevronDown, Check } from 'lucide-react';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { UserLayout } from '@/layouts/UserLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Sheet, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { AssetIcon, type AssetOverview } from '@/components/user/AssetCenter';
import { t, dateTime, errorMessage, useClientTranslation } from '@/i18n';

type Result = {
    id: string;
    asset: string;
    amount: string;
    state: string;
    network?: string;
    address?: string;
    fee?: string;
    feePercent?: string | null;
    receive?: string;
    rate?: string;
    expiresAt?: string;
    canConfirm?: boolean;
    canCancel?: boolean;
};
export default function AssetFlow({
    overview,
    mode,
    selectedAsset,
    result,
}: {
    overview: AssetOverview;
    mode: 'deposit' | 'withdrawal' | 'exchange';
    selectedAsset: string;
    result: Result | null;
}) {
    useClientTranslation();
    const serverErrors = usePage().props.errors;
    const [clock, setClock] = useState(() => Date.now());
    useEffect(() => {
        const timer = window.setInterval(() => setClock(Date.now()), 1000);
        return () => window.clearInterval(timer);
    }, []);
    const seconds = result?.expiresAt
        ? Math.max(0, Math.ceil((new Date(result.expiresAt).getTime() - clock) / 1000))
        : 0;
    const [picker, setPicker] = useState<'asset' | 'network' | null>(null);
    const [review, setReview] = useState(false);
    const [reviewRate, setReviewRate] = useState<string | null>(null);
    const [busy, setBusy] = useState(false);
    const form = useForm({
        mode,
        asset: selectedAsset,
        rail: '',
        amount: '',
        address: '',
        expected_fee: '',
        confirmed: false,
        request_id: crypto.randomUUID(),
    });
    const account = overview.assets.find((a) => a.asset === form.data.asset)!;
    const rails = account.rails.filter((r) => (mode === 'deposit' ? r.deposit : r.withdrawal));
    const rail = rails.find((r) => r.code === form.data.rail);
    const calculatedFee = withdrawalPercentageFee(
        form.data.amount,
        rail?.feePercent ?? null,
        account.asset,
    );
    const shownFee = review ? form.data.expected_fee : calculatedFee;
    const shownRate = review ? reviewRate : rail?.feePercent;
    const unavailable = mode === 'exchange' ? !account.exchange : rails.length === 0;
    const unavailableMessage =
        mode === 'exchange'
            ? (account.exchangeUnavailableReason ?? 'Exchange is not available for this asset.')
            : mode === 'deposit'
              ? 'No deposit network is available for this currency.'
              : 'No withdrawal network is available for this currency.';
    const title =
        mode === 'deposit' ? 'Top up' : mode === 'withdrawal' ? 'Withdraw' : 'Exchange to USDT';
    const update = (field: 'amount' | 'address', value: string) => {
        form.setData({
            ...form.data,
            [field]: value,
            request_id: crypto.randomUUID(),
            confirmed: false,
        });
        setReview(false);
    };
    const choose = (asset: string, code = '') => {
        router.get('/assets/operate', { mode, asset }, { preserveScroll: true });
        form.setData({
            ...form.data,
            asset,
            rail: code,
            amount: '',
            address: '',
            expected_fee: '',
            confirmed: false,
            request_id: crypto.randomUUID(),
        });
        setPicker(null);
        setReview(false);
    };
    const submit = () => {
        if (unavailable || busy || form.processing) return;
        if (rail?.code === 'USDT_TRON') {
            if (mode === 'deposit') {
                setBusy(true);
                router.post(
                    '/wallet/top-ups',
                    { request_id: form.data.request_id, requested_amount: form.data.amount },
                    { preserveScroll: true, onFinish: () => setBusy(false) },
                );
            } else {
                router.visit('/wallet/withdraw');
            }
            return;
        }
        form.post('/assets/orders', {
            preserveScroll: true,
            onError: () => {
                setReview(false);
                form.setData('confirmed', false);
            },
        });
    };
    const operation = (url: string) => {
        setBusy(true);
        router.post(
            url,
            { confirmed: true },
            { preserveScroll: true, onFinish: () => setBusy(false) },
        );
    };
    return (
        <UserLayout>
            <Head title={t(title)} />
            <div className="mx-auto max-w-lg space-y-6">
                <UserPageHeader title={t(title)} backHref="/dashboard" />
                {result && mode === 'deposit' ? (
                    <DepositInstructions
                        asset={result.asset}
                        amount={result.amount}
                        network={result.network}
                        address={result.address}
                        state={
                            seconds === 0 && result.state !== 'Completed'
                                ? 'Top-up expired'
                                : result.state
                        }
                        expiresAt={result.expiresAt}
                        payable={seconds > 0 && result.state !== 'Completed'}
                        newHref={`/assets/operate?mode=deposit&asset=${result.asset}`}
                    />
                ) : result ? (
                    <section className="space-y-5 rounded-2xl bg-surface p-5">
                        <div className="flex items-center gap-3">
                            <AssetIcon asset={result.asset} />
                            <div>
                                <h2 className="font-semibold">{t(result.state)}</h2>
                                <p className="text-sm text-muted-foreground">
                                    {result.asset}
                                    {result.network
                                        ? ` · ${assetNetworkLabel(result.network, account.asset)}`
                                        : ''}
                                </p>
                            </div>
                        </div>
                        <p className="break-all text-3xl font-semibold">
                            {exactAmount(result.amount)}{' '}
                            <span className="text-base">{result.asset}</span>
                        </p>
                        {mode === 'withdrawal' && (
                            <p className="break-all text-sm">
                                {t('Destination address')}: {result.address}
                            </p>
                        )}
                        {result.rate && (
                            <p className="break-all text-sm">
                                {t('Exchange rate')}: 1 {result.asset} {'≈'}{' '}
                                {exactAmount(result.rate)} USDT
                            </p>
                        )}
                        {result.fee !== undefined && (
                            <p className="break-all text-sm">
                                {t('Platform fee')}: {exactAmount(result.fee)}{' '}
                                {mode === 'exchange' ? 'USDT' : result.asset}
                                {result.feePercent != null &&
                                    ` (${exactAmount(result.feePercent)}%)`}
                            </p>
                        )}
                        {result.receive && (
                            <div className="border-t pt-4">
                                <p className="text-sm text-muted-foreground">{t('You receive')}</p>
                                <p className="mt-1 break-all text-2xl font-semibold">
                                    {exactAmount(result.receive)}{' '}
                                    {mode === 'exchange' ? 'USDT' : result.asset}
                                </p>
                            </div>
                        )}
                        {result.expiresAt && (
                            <p className="text-xs text-muted-foreground">
                                {t('Valid until {{time}}', { time: dateTime(result.expiresAt) })}
                            </p>
                        )}
                        {mode === 'exchange' && result.canConfirm && (
                            <>
                                <p className="text-sm text-muted-foreground">
                                    {t(
                                        'This exchanges your available balance internally. Confirm only after reviewing the final amounts.',
                                    )}
                                </p>
                                <Button
                                    className="min-h-12 w-full rounded-full"
                                    disabled={busy || seconds === 0}
                                    onClick={() =>
                                        operation(`/assets/exchanges/${result.id}/confirm`)
                                    }
                                >
                                    {t('Confirm exchange')} ·{' '}
                                    {t('{{seconds}} seconds', { seconds })}
                                </Button>
                            </>
                        )}
                        {result.canCancel && (
                            <Button
                                variant="secondary"
                                className="min-h-12 w-full"
                                disabled={busy}
                                onClick={() => operation(`/assets/withdrawals/${result.id}/cancel`)}
                            >
                                {t('Cancel withdrawal')}
                            </Button>
                        )}
                        <Link
                            href={`/assets/operate?mode=${mode}&asset=${result.asset}`}
                            className="block py-3 text-center text-sm underline"
                        >
                            {t('Start a new request')}
                        </Link>
                    </section>
                ) : (
                    <section className="space-y-5 rounded-2xl bg-surface p-5">
                        <button
                            onClick={() => setPicker('asset')}
                            className="flex min-h-14 w-full items-center gap-3 rounded-xl bg-muted p-3"
                        >
                            <AssetIcon asset={account.asset} />
                            <span className="flex-1 text-left font-medium">{account.asset}</span>
                            <ChevronDown size={18} />
                        </button>
                        <p className="break-all text-xs text-muted-foreground">
                            {t('Available balance')}: {exactAmount(account.available)}{' '}
                            {account.asset}
                        </p>
                        {mode === 'exchange' && (
                            <div className="space-y-2 rounded-xl bg-muted p-4">
                                <p className="text-xs text-muted-foreground">
                                    {t('Receive currency')}
                                </p>
                                <div className="flex items-center gap-3 font-medium">
                                    <AssetIcon asset="USDT" />
                                    <span>USDT</span>
                                </div>
                                <p className="text-xs text-muted-foreground">
                                    {t(
                                        'Card opening and card top-ups use your available USDT balance.',
                                    )}
                                </p>
                            </div>
                        )}
                        {mode !== 'exchange' && !unavailable && (
                            <button
                                onClick={() => setPicker('network')}
                                className="flex min-h-12 w-full items-center justify-between rounded-xl border px-4 text-sm"
                            >
                                {assetNetworkLabel(rail?.network, account.asset) ??
                                    t('Select network')}
                                <ChevronDown size={18} />
                            </button>
                        )}
                        {unavailable ? (
                            <p
                                role="status"
                                className="rounded-xl bg-muted p-4 text-sm text-muted-foreground"
                            >
                                {t(unavailableMessage)}
                            </p>
                        ) : rail?.code === 'USDT_TRON' && mode === 'withdrawal' ? (
                            <Button className="min-h-12 w-full rounded-full" onClick={submit}>
                                {t('Continue')}
                            </Button>
                        ) : (
                            <>
                                <label className="block space-y-2 text-sm">
                                    <span>
                                        {t('Amount')} · {account.asset}
                                    </span>
                                    <Input
                                        inputMode="decimal"
                                        value={form.data.amount}
                                        onChange={(e) => update('amount', e.target.value)}
                                        className="min-h-12"
                                    />
                                </label>
                                {mode === 'withdrawal' && (
                                    <label className="block space-y-2 text-sm">
                                        <span>{t('Destination address')}</span>
                                        <Input
                                            value={form.data.address}
                                            onChange={(e) => update('address', e.target.value)}
                                            className="min-h-12"
                                            autoComplete="off"
                                            spellCheck={false}
                                        />
                                    </label>
                                )}
                                {rail?.code === 'USDT_TRON' && mode === 'deposit' && (
                                    <p className="text-xs text-muted-foreground">
                                        {t('TRC20 · No top-up fee')}
                                    </p>
                                )}
                                {rail?.minimum && mode === 'deposit' && (
                                    <p className="text-xs text-muted-foreground">
                                        {t('Minimum deposit')}: {exactAmount(rail.minimum)}{' '}
                                        {account.asset}
                                    </p>
                                )}
                                {mode === 'withdrawal' && shownRate != null && (
                                    <p className="text-sm">
                                        {t('Withdrawal fee rate')}: {exactAmount(shownRate)}%
                                        {shownFee !== null &&
                                            ` · ${exactAmount(shownFee)} ${account.asset}`}
                                    </p>
                                )}
                                {mode === 'withdrawal' && review && (
                                    <div className="space-y-3 rounded-xl bg-muted p-4 text-sm">
                                        <p className="break-all">
                                            {assetNetworkLabel(rail?.network, account.asset)} ·{' '}
                                            {form.data.address}
                                        </p>
                                        <p>
                                            {t('Amount')}: {form.data.amount} {account.asset}
                                        </p>
                                        <p>
                                            {t('You receive')}:{' '}
                                            {subtract(form.data.amount, form.data.expected_fee)}{' '}
                                            {account.asset}
                                        </p>
                                        <label className="flex min-h-11 items-center gap-3">
                                            <input
                                                type="checkbox"
                                                checked={form.data.confirmed}
                                                onChange={(e) =>
                                                    form.setData('confirmed', e.target.checked)
                                                }
                                            />
                                            {t('I checked the network, address and final amount.')}
                                        </label>
                                    </div>
                                )}
                                {mode === 'exchange' && (
                                    <p className="text-xs text-muted-foreground">
                                        {t(
                                            'The next step shows the final rate, fee and quote expiry.',
                                        )}
                                    </p>
                                )}
                                <Button
                                    className="min-h-12 w-full rounded-full"
                                    disabled={
                                        busy ||
                                        form.processing ||
                                        !form.data.amount ||
                                        (mode === 'deposit' &&
                                            rail?.code === 'USDT_TRON' &&
                                            !meetsTopupMinimum(
                                                form.data.amount,
                                                rail.minimum ?? '0',
                                            )) ||
                                        (mode === 'exchange' ? !account.exchange : !rail) ||
                                        (review && !form.data.confirmed) ||
                                        (mode === 'withdrawal' && calculatedFee === null)
                                    }
                                    onClick={() => {
                                        if (mode === 'withdrawal' && !review) {
                                            if (calculatedFee === null) return;
                                            setReviewRate(rail?.feePercent ?? null);
                                            setReview(true);
                                            form.setData('expected_fee', calculatedFee);
                                        } else submit();
                                    }}
                                >
                                    {t(
                                        mode === 'exchange'
                                            ? 'Get quote'
                                            : mode === 'withdrawal'
                                              ? review
                                                  ? 'Confirm withdrawal'
                                                  : 'Review withdrawal'
                                              : 'Create deposit order',
                                    )}
                                </Button>
                            </>
                        )}
                    </section>
                )}
                {mode === 'withdrawal' && !result && (
                    <div className="space-y-2 px-2 text-sm leading-6 text-muted-foreground">
                        <p>
                            {t(
                                'USDT and USDC withdrawals incur a 10% fee. ETH and BTC withdrawals have no fee.',
                            )}
                        </p>
                        <p>{t('Account-to-account transfers are free for all currencies.')}</p>
                    </div>
                )}
                {Object.values({ ...serverErrors, ...form.errors }).map((message, index) => (
                    <p key={index} role="alert" className="text-sm text-destructive">
                        {errorMessage(message)}
                    </p>
                ))}
                <Sheet
                    open={picker !== null}
                    onOpenChange={(open) => {
                        if (!open) setPicker(null);
                    }}
                >
                    <SheetContent
                        closeLabel={t('Close')}
                        className="inset-x-0 top-auto bottom-0 mx-auto max-h-[80vh] w-full max-w-lg overflow-y-auto rounded-t-3xl border-0 p-6 pb-8"
                    >
                        <SheetTitle className="block pb-5 text-center font-semibold">
                            {t(picker === 'asset' ? 'Select currency' : 'Select network')}
                        </SheetTitle>
                        <SheetDescription className="sr-only">
                            {t('Only enabled currency and network combinations are available.')}
                        </SheetDescription>
                        {picker === 'asset'
                            ? overview.assets
                                  .filter((a) => mode !== 'exchange' || a.asset !== 'USDT')
                                  .map((a) => (
                                      <button
                                          key={a.asset}
                                          onClick={() => choose(a.asset)}
                                          className="flex min-h-16 w-full items-center gap-3 border-t"
                                      >
                                          <AssetIcon asset={a.asset} />
                                          <span className="flex-1 text-left">{a.asset}</span>
                                          {a.asset === account.asset && <Check size={20} />}
                                      </button>
                                  ))
                            : rails.map((r) => (
                                  <button
                                      key={r.code}
                                      onClick={() => {
                                          form.setData({
                                              ...form.data,
                                              rail: r.code,
                                              amount: '',
                                              address: '',
                                              confirmed: false,
                                              request_id: crypto.randomUUID(),
                                          });
                                          setPicker(null);
                                          setReview(false);
                                      }}
                                      className="flex min-h-16 w-full items-center justify-between border-t"
                                  >
                                      <span>{assetNetworkLabel(r.network, account.asset)}</span>
                                      {r.code === rail?.code && <Check size={20} />}
                                  </button>
                              ))}
                    </SheetContent>
                </Sheet>
            </div>
        </UserLayout>
    );
}
// Exact display preview only; the server independently computes and validates the payout.
function subtract(a: string, b: string): string {
    try {
        const units = (v: string) => {
            const [i = '', f = ''] = v.split('.');
            if (!/^\d+$/.test(i) || !/^\d{0,18}$/.test(f)) throw Error();
            return BigInt(i + f.padEnd(18, '0'));
        };
        const n = units(a) - units(b);
        if (n <= 0n) return '—';
        const s = n.toString().padStart(19, '0');
        return exactAmount(s.slice(0, -18) + '.' + s.slice(-18));
    } catch {
        return '—';
    }
}
