// mobile/uni-app/src/screens/Kyc.vue
<script setup lang="ts">
import { useSensitiveScreen } from '../lib/sensitive';
import { computed, reactive } from 'vue';
import { t, locale, dateTime } from '../lib/i18n';
import { useAction } from '../lib/client';
import { photoUrl } from '../lib/api';
import { go } from '../lib/navigation';
import PageShell from '../components/PageShell.vue';
import StatusBanner from '../components/StatusBanner.vue';
import FormErrors from '../components/FormErrors.vue';
import SelectField from '../components/SelectField.vue';
import UploadField from '../components/UploadField.vue';
import countries from '../generated/countries.json';
const props = defineProps<{
    page: {
        kyc: {
            status: string;
            reviewMessage: string | null;
            documentType?: string | null;
            documentCountry?: string | null;
            maskedIdentityNumber?: string | null;
            submittedAt?: string | null;
            verifiedAt?: string | null;
            frontUrl?: string | null;
            backUrl?: string | null;
        };
        canSubmit: boolean;
        maxDocumentMb: number;
        backHref: string;
    };
}>();
const emit = defineEmits<{ reload: [] }>();
const action = useAction();
const form = reactive({
    document_type: 'NATIONAL_ID',
    document_country: 'CN',
    front: '',
    back: '',
});
const states: Record<string, { title: string; description: string; tone: string }> = {
    NOT_SUBMITTED: {
        title: 'Identity verification',
        description: 'Verify your identity to continue.',
        tone: 'neutral',
    },
    PENDING: {
        title: 'Verification under review',
        description: 'Your information has been submitted.',
        tone: 'pending',
    },
    APPROVED: {
        title: 'Identity verified',
        description: 'Your identity verification is complete.',
        tone: 'success',
    },
    REJECTED: {
        title: 'Verification could not be approved',
        description: 'Please contact support for assistance.',
        tone: 'warning',
    },
    RESUBMISSION_REQUIRED: {
        title: 'Action required',
        description: 'Please submit a new set of identity documents.',
        tone: 'warning',
    },
};
const state = computed(() => states[props.page.kyc.status] ?? states.NOT_SUBMITTED);
const countryOptions = computed(() => {
    const names = new Intl.DisplayNames([locale.value], { type: 'region' });
    const priority = ['CN', 'HK', 'MO', 'TW'];
    return countries
        .filter((c) => form.document_type === 'PASSPORT' || c.code === 'CN')
        .map((c) => ({
            value: c.code,
            label: names.of(c.code) ?? c.name,
            keywords: [c.name, c.code],
        }))
        .sort((a, b) => {
            const rank = (code: string) => (priority.includes(code) ? priority.indexOf(code) : 4);
            return rank(a.value) - rank(b.value) || a.label.localeCompare(b.label, locale.value);
        });
});
function resetFiles() {
    form.document_country = 'CN';
    form.front = '';
    form.back = '';
}
useSensitiveScreen(
    () => {
        form.front = '';
        form.back = '';
    },
    { retainOnBackground: true },
);
async function submit() {
    const files = [
        { name: 'front', path: form.front },
        ...(form.document_type === 'NATIONAL_ID' ? [{ name: 'back', path: form.back }] : []),
    ].filter((file) => file.path);
    await action.submit(
        '/kyc/applications' +
            (props.page.backHref === '/account/security' ? '?from=account-security' : ''),
        {
            document_type: form.document_type,
            document_country: form.document_country,
        },
        {
            files,
            navigate: false,
            success: () => {
                resetFiles();
                emit('reload');
            },
        },
    );
}
</script>
<template>
    <PageShell :title="t('Identity verification')" :back="page.backHref" active="account"
        ><StatusBanner
            :title="t(state.title)"
            :description="
                page.kyc.reviewMessage && page.kyc.status === 'RESUBMISSION_REQUIRED'
                    ? page.kyc.reviewMessage
                    : t(state.description)
            "
            :tone="state.tone"
        /><view v-if="page.kyc.status === 'APPROVED'" class="kyc-card">
            <text class="kyc-title">{{ t('Identity verified') }}</text>
            <view class="verified-row"
                ><text>{{ t('Document type') }}</text
                ><text>{{
                    t(
                        page.kyc.documentType === 'PASSPORT'
                            ? 'Passport'
                            : 'Mainland China identity card',
                    )
                }}</text></view
            >
            <view class="verified-row"
                ><text>{{ t('Document country') }}</text
                ><text>{{
                    page.kyc.documentCountry
                        ? new Intl.DisplayNames([locale], { type: 'region' }).of(
                              page.kyc.documentCountry,
                          )
                        : '—'
                }}</text></view
            >
            <view class="verified-row"
                ><text>{{ t('Identity number') }}</text
                ><text>{{ page.kyc.maskedIdentityNumber ?? '—' }}</text></view
            >
            <view class="verified-row"
                ><text>{{ t('Verification time') }}</text
                ><text>{{ page.kyc.verifiedAt ? dateTime(page.kyc.verifiedAt) : '—' }}</text></view
            >
            <view class="document-grid">
                <view
                    ><text class="label">{{
                        t(
                            page.kyc.documentType === 'PASSPORT'
                                ? 'Passport information page'
                                : 'ID front',
                        )
                    }}</text>
                    <image
                        v-if="page.kyc.frontUrl"
                        :src="photoUrl(page.kyc.frontUrl) ?? ''"
                        mode="widthFix"
                        class="verified-photo"
                    />
                    <text v-else class="muted">{{ t('Image unavailable') }}</text>
                </view>
                <view v-if="page.kyc.documentType !== 'PASSPORT'"
                    ><text class="label">{{ t('ID back') }}</text>
                    <image
                        v-if="page.kyc.backUrl"
                        :src="photoUrl(page.kyc.backUrl) ?? ''"
                        mode="widthFix"
                        class="verified-photo"
                    />
                    <text v-else class="muted">{{ t('Image unavailable') }}</text>
                </view>
            </view> </view
        ><view v-else-if="page.canSubmit" class="kyc-card"
            ><text class="kyc-title">{{
                t(
                    page.kyc.status === 'RESUBMISSION_REQUIRED'
                        ? 'Resubmit documents'
                        : 'Submit identity documents',
                )
            }}</text
            ><view v-if="Object.keys(action.errors.value).length"
                ><FormErrors :errors="action.errors.value" /><view class="error-actions"
                    ><text @click="emit('reload')">{{ t('Refresh status') }}</text
                    ><text @click="go('/support')">{{ t('Online support') }}</text></view
                ></view
            >
            <form @submit="submit">
                <SelectField
                    v-model="form.document_type"
                    :label="t('Document type')"
                    :options="[
                        { value: 'NATIONAL_ID', label: t('Mainland China identity card') },
                        { value: 'PASSPORT', label: t('Passport') },
                    ]"
                    :disabled="action.pending.value"
                    @update:model-value="resetFiles"
                /><SelectField
                    v-model="form.document_country"
                    :label="t('Document country')"
                    :options="countryOptions"
                    :disabled="action.pending.value"
                    searchable
                /><view class="document-grid"
                    ><UploadField
                        v-model="form.front"
                        :label="
                            t(
                                form.document_type === 'PASSPORT'
                                    ? 'Passport information page'
                                    : 'ID front',
                            )
                        "
                        :max-mb="page.maxDocumentMb"
                        :disabled="action.pending.value" /><UploadField
                        v-if="form.document_type === 'NATIONAL_ID'"
                        v-model="form.back"
                        :label="t('ID back')"
                        :max-mb="page.maxDocumentMb"
                        :disabled="action.pending.value" /></view
                ><button
                    class="primary submit-button"
                    form-type="submit"
                    :disabled="
                        action.pending.value ||
                        !form.front ||
                        (form.document_type === 'NATIONAL_ID' && !form.back)
                    "
                >
                    {{ t(action.pending.value ? 'Submitting…' : 'Submit for review') }}
                </button>
            </form></view
        ><text
            v-else-if="['NOT_SUBMITTED', 'RESUBMISSION_REQUIRED'].includes(page.kyc.status)"
            class="muted"
            >{{
                t(
                    'New submissions are currently unavailable. Your account or Tenant may be restricted, or KYC may be disabled.',
                )
            }}</text
        ></PageShell
    >
</template>
<style scoped>
.verified-row {
    display: flex;
    justify-content: space-between;
    gap: 16px;
    padding: 12px 0;
    font-size: 14px;
}
.verified-row > text:last-child {
    text-align: right;
    overflow-wrap: anywhere;
}
.verified-photo {
    width: 100%;
    display: block;
    border-radius: 12px;
}
.kyc-card {
    border: 1px solid #e2e7e4;
    border-radius: 24px;
    padding: 24px;
    background: white;
}
.kyc-title {
    display: block;
    font-size: 20px;
    font-weight: 600;
    margin-bottom: 24px;
}
.document-grid {
    display: grid;
    gap: 0;
}
.submit-button {
    border-radius: 999px;
    min-height: 44px;
    line-height: 24px;
    padding: 10px 24px;
    width: 100%;
    font-weight: 500;
}
.error-actions {
    display: flex;
    gap: 16px;
    flex-wrap: wrap;
    font-size: 14px;
    text-decoration: underline;
    margin-bottom: 20px;
}
@media (min-width: 640px) {
    .document-grid {
        grid-template-columns: 1fr 1fr;
        gap: 20px;
    }
    .submit-button {
        width: auto;
        display: inline-block;
    }
}
</style>

// resources/js/pages/user/Kyc.tsx
import { t, useClientTranslation, errorMessage } from '@/i18n';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { UserStatusBanner } from '@/components/user/UserStatusBanner';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { FormField } from '@/components/ui/form-field';
import { Input } from '@/components/ui/input';
import { SearchSelect } from '@/components/ui/search-select';
import { countryOptions, useCardGeography, type Country } from '@/hooks/useCardGeography';
import { UserLayout } from '@/layouts/UserLayout';

type KycStatus = 'NOT_SUBMITTED' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'RESUBMISSION_REQUIRED';
type Props = {
    kyc: {
        status: KycStatus;
        reviewMessage: string | null;
        submittedAt: string | null;
        verifiedAt: string | null;
        documentCountry: string | null;
        maskedIdentityNumber: string | null;
    };
    canSubmit: boolean;
    maxDocumentMb: number;
    backHref: '/account' | '/account/security';
};

const content = {
    NOT_SUBMITTED: {
        title: 'Identity verification',
        description: 'Verify your identity to continue.',
        tone: 'neutral',
    },
    PENDING: {
        title: 'Verification under review',
        description: 'Your information has been submitted.',
        tone: 'pending',
    },
    APPROVED: {
        title: 'Identity verified',
        description: 'Your identity verification is complete.',
        tone: 'success',
    },
    REJECTED: {
        title: 'Verification could not be approved',
        description: 'Please contact support for assistance.',
        tone: 'warning',
    },
    RESUBMISSION_REQUIRED: {
        title: 'Action required',
        description: 'Please submit a new set of identity documents.',
        tone: 'warning',
    },
} satisfies Record<
    KycStatus,
    { title: string; description: string; tone: 'neutral' | 'pending' | 'success' | 'warning' }
>;

export default function Kyc({ kyc, canSubmit, maxDocumentMb, backHref }: Props) {
    const { i18n } = useClientTranslation();
    const countries = useCardGeography<Country[]>('countries');
    const countryItems = countryOptions(countries.data ?? [], i18n.language);
    const form = useForm<{
        document_type: string;
        document_country: string;
        identity_number: string;
        front: File | null;
        back: File | null;
        form?: string;
    }>({
        document_type: 'NATIONAL_ID',
        document_country: 'CN',
        identity_number: '',
        front: null,
        back: null,
        form: undefined,
    });
    const state = content[kyc.status];
    return (
        <UserLayout>
            <Head title={t('Identity verification')} />
            <div className="mx-auto max-w-3xl space-y-6 sm:space-y-8">
                <UserPageHeader title={t('Identity verification')} backHref={backHref} />
                <UserStatusBanner
                    title={t(state.title)}
                    description={
                        kyc.reviewMessage && kyc.status === 'RESUBMISSION_REQUIRED'
                            ? kyc.reviewMessage
                            : t(state.description)
                    }
                    tone={state.tone}
                />
                {canSubmit && (
                    <Card className="rounded-[var(--user-radius-lg)] shadow-none">
                        <CardHeader>
                            <CardTitle>
                                {kyc.status === 'RESUBMISSION_REQUIRED'
                                    ? t('Resubmit documents')
                                    : t('Submit identity documents')}
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            {form.errors.form && (
                                <Alert className="mb-5 border-red-200 bg-red-50 text-destructive">
                                    <AlertDescription>
                                        {errorMessage(
                                            form.errors.form,
                                            'We could not complete identity verification. Refresh the status below. If the problem continues, contact support.',
                                        )}
                                    </AlertDescription>
                                    <div className="mt-3 flex flex-wrap gap-4">
                                        <button
                                            type="button"
                                            className="underline underline-offset-4"
                                            onClick={() => router.reload()}
                                        >
                                            {t('Refresh status')}
                                        </button>
                                        <Link
                                            href="/support"
                                            className="underline underline-offset-4"
                                        >
                                            {t('Online support')}
                                        </Link>
                                    </div>
                                </Alert>
                            )}
                            <form
                                className="space-y-5"
                                onSubmit={(event) => {
                                    event.preventDefault();
                                    form.post(
                                        backHref === '/account/security'
                                            ? '/kyc/applications?from=account-security'
                                            : '/kyc/applications',
                                        { forceFormData: true },
                                    );
                                }}
                            >
                                <FormField
                                    id="document-type"
                                    label={t('Document type')}
                                    error={errorMessage(form.errors.document_type)}
                                >
                                    <select
                                        id="document-type"
                                        className="w-full rounded-lg border p-3"
                                        value={form.data.document_type}
                                        disabled={form.processing}
                                        onChange={(event) =>
                                            form.setData((data) => ({
                                                ...data,
                                                document_type: event.target.value,
                                                document_country: 'CN',
                                                front: null,
                                                back: null,
                                            }))
                                        }
                                    >
                                        <option value="NATIONAL_ID">
                                            {t('Mainland China identity card')}
                                        </option>
                                        <option value="PASSPORT">{t('Passport')}</option>
                                    </select>
                                </FormField>
                                <FormField
                                    id="document-country"
                                    label={t('Document country')}
                                    error={errorMessage(form.errors.document_country)}
                                >
                                    <SearchSelect
                                        id="document-country"
                                        label={t('Document country')}
                                        value={form.data.document_country}
                                        options={
                                            form.data.document_type === 'NATIONAL_ID'
                                                ? countryItems.filter((item) => item.value === 'CN')
                                                : countryItems
                                        }
                                        placeholder={t('Please select')}
                                        searchLabel={t('Search options')}
                                        emptyLabel={t('No matching options')}
                                        disabled={form.processing || !countryItems.length}
                                        invalid={!!form.errors.document_country}
                                        onValueChange={(value) => {
                                            form.setData('document_country', value);
                                            form.clearErrors('document_country');
                                        }}
                                    />
                                    {countries.failed && (
                                        <div role="alert" className="text-sm text-destructive">
                                            {t('Location options could not be loaded.')}{' '}
                                            <button
                                                type="button"
                                                className="underline"
                                                onClick={countries.retry}
                                            >
                                                {t('Try again')}
                                            </button>
                                        </div>
                                    )}
                                </FormField>
                                <FormField
                                    id="identity-number"
                                    label={t('Identity number')}
                                    description={t(
                                        'Enter the document number exactly as shown in the uploaded image.',
                                    )}
                                    error={errorMessage(form.errors.identity_number)}
                                >
                                    <Input
                                        id="identity-number"
                                        required
                                        value={form.data.identity_number}
                                        onChange={(event) =>
                                            form.setData('identity_number', event.target.value)
                                        }
                                        autoComplete="off"
                                    />
                                </FormField>
                                <div className="grid gap-5 sm:grid-cols-2">
                                    <FormField
                                        id="id-front"
                                        label={t(
                                            form.data.document_type === 'PASSPORT'
                                                ? 'Passport information page'
                                                : 'ID front',
                                        )}
                                        description={t('JPEG, PNG or WEBP · max {{value1}} MB', {
                                            value1: maxDocumentMb,
                                        })}
                                        error={errorMessage(form.errors.front)}
                                    >
                                        <Input
                                            id="id-front"
                                            key={form.data.document_type}
                                            required
                                            type="file"
                                            accept="image/jpeg,image/png,image/webp"
                                            onChange={(event) =>
                                                form.setData(
                                                    'front',
                                                    event.target.files?.[0] ?? null,
                                                )
                                            }
                                        />
                                    </FormField>
                                    {form.data.document_type === 'NATIONAL_ID' && (
                                        <FormField
                                            id="id-back"
                                            label={t('ID back')}
                                            description={t(
                                                'JPEG, PNG or WEBP · max {{value1}} MB',
                                                {
                                                    value1: maxDocumentMb,
                                                },
                                            )}
                                            error={errorMessage(form.errors.back)}
                                        >
                                            <Input
                                                id="id-back"
                                                required
                                                type="file"
                                                accept="image/jpeg,image/png,image/webp"
                                                onChange={(event) =>
                                                    form.setData(
                                                        'back',
                                                        event.target.files?.[0] ?? null,
                                                    )
                                                }
                                            />
                                        </FormField>
                                    )}
                                </div>
                                <Button
                                    className="w-full sm:w-auto"
                                    disabled={form.processing || !countryItems.length}
                                >
                                    {form.processing ? t('Submitting…') : t('Submit for review')}
                                </Button>
                            </form>
                        </CardContent>
                    </Card>
                )}
                {!canSubmit &&
                    (kyc.status === 'NOT_SUBMITTED' || kyc.status === 'RESUBMISSION_REQUIRED') && (
                        <Alert>
                            <AlertDescription>
                                {t(
                                    'New submissions are currently unavailable. Your account or Tenant may be restricted, or KYC may be disabled.',
                                )}
                            </AlertDescription>
                        </Alert>
                    )}
            </div>
        </UserLayout>
    );
}
