// mobile/uni-app/src/pages/messages/index.vue
<script setup lang="ts">
import { ref } from 'vue';
import PageShell from '../../components/PageShell.vue';
import LoadState from '../../components/LoadState.vue';
import { request } from '../../lib/api';
import { refreshUnread } from '../../lib/session';
import { useScreen } from '../../lib/screen';
import { t, dateTime } from '../../lib/i18n';
import { messageCopy, type Message } from '../../lib/inbox';
const filters = [{ key: 'all', title: 'All' }, { key: 'unread', title: 'Unread' }, { key: 'business', title: 'Business notifications' }, { key: 'platform', title: 'Platform notifications' }];
const filter = ref('all'); const page = ref(1); const items = ref<Message[]>([]); const hasMore = ref(false); const busy = ref(false); const actionFailed = ref(false);
async function load() { const data = await request<{ items: Message[]; hasMore: boolean }>(`/messages?filter=${filter.value}&page=${page.value}`); items.value = data.items; hasMore.value = data.hasMore; await refreshUnread(); }
const { loading, failed, refresh } = useScreen(load);
function select(key: string) { filter.value = key; page.value = 1; void refresh(); }
function paginate(delta: number) { page.value += delta; void refresh(); }
function openMessage(id: string) { uni.navigateTo({ url: '/pages/messages/detail?id=' + id }); }
async function allRead() { busy.value = true; actionFailed.value = false; try { await request('/messages/read-all', 'POST'); await refreshUnread(); await refresh(); } catch { actionFailed.value = true; } finally { busy.value = false; } }
</script>
<template>
  <PageShell :title="t('Messages')" back="/pages/account/index">
    <view class="toolbar"><button v-for="item in filters" :key="item.key" class="filter" :class="{ selected: filter === item.key }" :disabled="loading" @click="select(item.key)">{{ t(item.title) }}</button></view>
    <view class="flex" style="justify-content:flex-end"><button class="filter" style="flex:none" :disabled="busy" @click="allRead">{{ t('Mark all as read') }}</button></view>
    <text v-if="actionFailed" class="error">{{ t('Could not update messages. Please try again.') }}</text>
    <LoadState :loading="loading" :failed="failed" @retry="refresh">
      <view v-if="!items.length" class="empty">{{ t('No messages yet') }}</view>
      <view v-for="message in items" :key="message.id" class="row" role="button" @click="openMessage(message.id)">
        <view class="flex"><text class="message-title">{{ messageCopy(message).title }}</text><view v-if="!message.readAt" class="dot" /></view>
        <text class="body muted" style="margin:10px 0">{{ messageCopy(message).body.slice(0, 160) }}</text><text class="muted">{{ dateTime(message.time) }}</text>
      </view>
      <view class="pagination"><button class="filter" :disabled="page === 1" @click="paginate(-1)">{{ t('Previous') }}</button><button class="filter" :disabled="!hasMore" @click="paginate(1)">{{ t('Next') }}</button></view>
    </LoadState>
  </PageShell>
</template>

// resources/js/pages/user/Messages.tsx
import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';
import { t, dateTime, useClientTranslation } from '@/i18n';
import { UserLayout } from '@/layouts/UserLayout';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { Button } from '@/components/ui/button';
import { messageCopy, type InboxMessage } from '@/lib/inbox';

type MessagePage = {
    data: InboxMessage[];
    prev_page_url: string | null;
    next_page_url: string | null;
};
export default function Messages({ messages, filter }: { messages: MessagePage; filter: string }) {
    useClientTranslation();
    const [busy, setBusy] = useState(false);
    const [failed, setFailed] = useState(false);
    return (
        <UserLayout>
            <Head title={t('Messages')} />
            <UserPageHeader title={t('Messages')} backHref="/account" />
            <div className="mb-4 mt-5 space-y-2">
                <div className="grid grid-cols-4 gap-1">
                    {(['all', 'unread', 'business', 'platform'] as const).map((key) => (
                        <Link
                            key={key}
                            href={`/messages?filter=${key}`}
                            onNetworkError={() => {
                                setFailed(true);
                                return false;
                            }}
                            onHttpException={() => {
                                setFailed(true);
                                return false;
                            }}
                            aria-current={filter === key ? 'page' : undefined}
                            className={`flex min-h-11 items-center justify-center rounded-full px-2 py-2 text-center text-sm ${filter === key ? 'bg-[var(--user-primary-soft)] text-[var(--user-primary)]' : 'text-muted-foreground'}`}
                        >
                            {t(
                                {
                                    all: 'All',
                                    unread: 'Unread',
                                    business: 'Business notifications',
                                    platform: 'Platform notifications',
                                }[key],
                            )}
                        </Link>
                    ))}
                </div>
                <div className="flex justify-end">
                    <Button
                        variant="ghost"
                        disabled={busy}
                        className="ml-auto"
                        onClick={() => {
                            setBusy(true);
                            setFailed(false);
                            router.post(
                                '/messages/read-all',
                                {},
                                {
                                    preserveScroll: true,
                                    onSuccess: () => window.dispatchEvent(new Event('inbox-read')),
                                    onError: () => setFailed(true),
                                    onNetworkError: () => {
                                        setFailed(true);
                                        return false;
                                    },
                                    onHttpException: () => {
                                        setFailed(true);
                                        return false;
                                    },
                                    onFinish: () => setBusy(false),
                                },
                            );
                        }}
                    >
                        {t('Mark all as read')}
                    </Button>
                </div>
            </div>
            {failed && (
                <p role="alert" className="text-sm text-destructive">
                    {t('Could not update messages. Please try again.')}
                </p>
            )}
            {messages.data.length === 0 ? (
                <p className="py-16 text-center text-muted-foreground">{t('No messages yet')}</p>
            ) : (
                <ul className="divide-y">
                    {messages.data.map((message) => {
                        const copy = messageCopy(message);
                        return (
                            <li key={message.id}>
                                <Link href={`/messages/${message.id}`} className="block py-5">
                                    <div className="flex items-start gap-2">
                                        <h2
                                            className={`min-w-0 flex-1 break-words ${message.readAt ? 'font-medium' : 'font-semibold'}`}
                                        >
                                            {copy.title}
                                        </h2>
                                        {!message.readAt && (
                                            <span
                                                className="mt-2 size-2 shrink-0 rounded-full bg-[var(--user-primary)]"
                                                aria-label={t('Unread')}
                                            />
                                        )}
                                    </div>
                                    <p className="mt-2 line-clamp-2 break-words text-sm leading-6 text-muted-foreground">
                                        {copy.body}
                                    </p>
                                    <p className="mt-2 text-xs text-muted-foreground">
                                        {dateTime(message.time)}
                                    </p>
                                </Link>
                            </li>
                        );
                    })}
                </ul>
            )}
            <nav className="mt-5 flex justify-between" aria-label={t('Pagination')}>
                {messages.prev_page_url ? (
                    <Link
                        href={messages.prev_page_url}
                        onNetworkError={() => {
                            setFailed(true);
                            return false;
                        }}
                        className="p-3 text-sm"
                    >
                        {t('Previous')}
                    </Link>
                ) : (
                    <span />
                )}
                {messages.next_page_url && (
                    <Link
                        href={messages.next_page_url}
                        onNetworkError={() => {
                            setFailed(true);
                            return false;
                        }}
                        className="p-3 text-sm"
                    >
                        {t('Next')}
                    </Link>
                )}
            </nav>
        </UserLayout>
    );
}
