// mobile/uni-app/src/screens/SecurityDepositHistory.vue
<script setup lang="ts">
import PageShell from '../components/PageShell.vue';
import { t, dateTime } from '../lib/i18n';
import { go } from '../lib/navigation';
import { displayMoney } from '../generated/exact-amount';
defineProps<{
    page: {
        history: {
            data: {
                id: string;
                amount: string;
                asset: string;
                state: string;
                requestedAt: string;
            }[];
            currentPage: number;
            lastPage: number;
        };
    };
}>();
const labels: Record<string, string> = {
    pending: 'Refund checks pending',
    completed: 'Security deposit refunded',
    cancelled: 'Refund request cancelled',
};
</script>
<template>
    <PageShell :title="t('Security deposit history')" back="/security-deposit" active="assets"
        ><view v-if="!page.history.data.length" class="empty">{{
            t('No security deposit history yet.')
        }}</view
        ><view v-for="row in page.history.data" :key="row.id" class="refund-row"
            ><view
                ><text class="refund-label">{{ t(labels[row.state]) }}</text
                ><text class="refund-time">{{ dateTime(row.requestedAt) }}</text></view
            ><text class="refund-amount">{{ displayMoney(row.amount) }} {{ row.asset }}</text></view
        ><view v-if="page.history.lastPage > 1" class="pagination"
            ><button
                class="secondary"
                :disabled="page.history.currentPage <= 1"
                @click="
                    go('/security-deposit/history?page=' + (page.history.currentPage - 1), true)
                "
            >
                {{ t('Previous') }}</button
            ><text>{{ page.history.currentPage }} / {{ page.history.lastPage }}</text
            ><button
                class="secondary"
                :disabled="page.history.currentPage >= page.history.lastPage"
                @click="
                    go('/security-deposit/history?page=' + (page.history.currentPage + 1), true)
                "
            >
                {{ t('Next') }}
            </button></view
        ></PageShell
    >
</template>
<style scoped>
.refund-row {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 16px;
    padding: 16px 0;
    border-bottom: 1px solid #e2e7e4;
    font-size: 14px;
}
.refund-label {
    display: block;
    font-weight: 500;
}
.refund-time {
    display: block;
    margin-top: 8px;
    font-size: 12px;
    color: #68736e;
}
.refund-amount {
    font-weight: 600;
    flex-shrink: 0;
}
.pagination {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 16px;
    margin-top: 24px;
    font-size: 14px;
}
</style>

// resources/js/pages/user/SecurityDepositHistory.tsx
import { Head, router } from '@inertiajs/react';
import { t, dateTime, useClientTranslation } from '@/i18n';
import { UserLayout } from '@/layouts/UserLayout';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { MoneyDisplay } from '@/components/user/UserMoney';
import { Button } from '@/components/ui/button';
import type { MoneyAmount } from '@/types/global';

type History = {
    data: {
        id: string;
        amount: MoneyAmount;
        asset: string;
        state: 'pending' | 'completed' | 'cancelled';
        requestedAt: string;
    }[];
    currentPage: number;
    lastPage: number;
};
const labels = {
    pending: 'Refund checks pending',
    completed: 'Security deposit refunded',
    cancelled: 'Refund request cancelled',
};

export default function SecurityDepositHistory({ history }: { history: History }) {
    useClientTranslation();
    const navigate = (page: number) =>
        router.get(
            '/security-deposit/history',
            { page },
            { only: ['history'], preserveState: true, preserveScroll: true },
        );
    return (
        <UserLayout>
            <Head title={t('Security deposit history')} />
            <div className="space-y-6 sm:space-y-8">
                <UserPageHeader
                    title={t('Security deposit history')}
                    backHref="/security-deposit"
                />
                {history.data.length === 0 ? (
                    <p className="py-6 text-center text-sm text-muted-foreground">
                        {t('No security deposit history yet.')}
                    </p>
                ) : (
                    <ul className="divide-y">
                        {history.data.map((row) => (
                            <li
                                key={row.id}
                                className="flex items-start justify-between gap-4 py-4"
                            >
                                <div className="min-w-0 space-y-2">
                                    <p className="text-sm font-medium">{t(labels[row.state])}</p>
                                    <time
                                        dateTime={row.requestedAt}
                                        className="block text-xs text-muted-foreground"
                                    >
                                        {dateTime(row.requestedAt)}
                                    </time>
                                </div>
                                <span className="shrink-0 text-sm font-semibold tabular-nums">
                                    <MoneyDisplay amount={row.amount} asset={row.asset} compact />
                                </span>
                            </li>
                        ))}
                    </ul>
                )}
                {history.lastPage > 1 && (
                    <div className="flex items-center justify-center gap-4">
                        <Button
                            variant="secondary"
                            size="sm"
                            disabled={history.currentPage <= 1}
                            onClick={() => navigate(history.currentPage - 1)}
                        >
                            {t('Previous')}
                        </Button>
                        <span className="text-sm tabular-nums">
                            {history.currentPage} / {history.lastPage}
                        </span>
                        <Button
                            variant="secondary"
                            size="sm"
                            disabled={history.currentPage >= history.lastPage}
                            onClick={() => navigate(history.currentPage + 1)}
                        >
                            {t('Next')}
                        </Button>
                    </div>
                )}
            </div>
        </UserLayout>
    );
}
