// mobile/uni-app/src/screens/Security.vue
<script setup lang="ts">
import { useSensitiveScreen } from '../lib/sensitive';
import { computed, reactive, ref, onBeforeUnmount, watch } from 'vue';
import PageShell from '../components/PageShell.vue';
import FormField from '../components/FormField.vue';
import FormErrors from '../components/FormErrors.vue';
import ConfirmCheck from '../components/ConfirmCheck.vue';
import UiIcon from '../components/UiIcon.vue';
import { t } from '../lib/i18n';
import { session, bootstrap } from '../lib/session';
import { useAction, requestId } from '../lib/client';
import { go } from '../lib/navigation';
type Challenge = {
    id: string;
    channel: string;
    destination: string;
    expiresAt: string;
    resendAt?: string;
    deliveryUncertain: boolean;
};
const props = defineProps<{
    page: {
        kycStatus: string;
        information: { canEdit: boolean; email: string | null; challenge: Challenge | null };
    };
}>();
const emit = defineEmits<{ reload: [] }>();
const action = useAction(),
    expanded = ref(props.page.information.challenge ? 'EMAIL' : ''),
    editing = ref(false),
    now = ref(Date.now());
const form = reactive({
    display_name: session.value?.user?.displayName ?? '',
    new_contact: '',
    current_password: '',
    password: '',
    password_confirmation: '',
    code: '',
    confirmed: false,
    request_id: requestId(),
});
const timer = setInterval(() => (now.value = Date.now()), 1000);
onBeforeUnmount(() => {
    clearInterval(timer);
    form.current_password = '';
    form.password = '';
    form.password_confirmation = '';
    form.code = '';
});
const challenge = computed(() => props.page.information.challenge);
watch(
    () => challenge.value?.id,
    () => {
        editing.value = false;
        form.code = '';
        form.confirmed = false;
    },
);
const remaining = computed(() =>
    Math.max(0, Math.ceil((Date.parse(challenge.value?.expiresAt ?? '') - now.value) / 1000)),
);
const resendRemaining = computed(() =>
    Math.max(
        0,
        Math.ceil(
            (Date.parse(challenge.value?.resendAt ?? challenge.value?.expiresAt ?? '') -
                now.value) /
                1000,
        ),
    ),
);
const remainingLabel = computed(() =>
    remaining.value > 0
        ? t('Code expires in {{seconds}}s', { seconds: remaining.value })
        : t('Verification code expired. Request a new code.'),
);
const resendLabel = computed(() =>
    resendRemaining.value > 0
        ? t('Request a new code in {{seconds}}s', { seconds: resendRemaining.value })
        : t('Request a new code'),
);
useSensitiveScreen(() => {
    form.current_password = '';
    form.password = '';
    form.password_confirmation = '';
    form.code = '';
    form.confirmed = false;
    expanded.value = '';
});
const rows = computed(() => [
    {
        id: 'name',
        title: 'Display name',
        value: session.value?.user?.displayName || t('Account user'),
        icon: 'account',
    },
    {
        id: 'EMAIL',
        title: 'Email address',
        value: props.page.information.email || t('Not linked'),
        icon: 'mail',
    },
    { id: 'password', title: 'Change password', value: '••••••••', icon: 'lock-keyhole' },
    {
        id: 'sessions',
        title: 'Sign out other devices',
        value: t('Keep this device signed in'),
        icon: 'monitor-x',
    },
]);
const verification = computed(() =>
    t(
        (
            {
                APPROVED: 'Verified',
                PENDING: 'Under review',
                RESUBMISSION_REQUIRED: 'Action required',
                REJECTED: 'Verification could not be approved',
            } as Record<string, string>
        )[props.page.kycStatus] ?? 'Not verified',
    ),
);
function expand(id: string) {
    if (action.pending.value) return;
    expanded.value = expanded.value === id ? '' : id;
    action.errors.value = {};
    form.current_password = '';
    form.password = '';
    form.password_confirmation = '';
    form.confirmed = false;
}
function newContact() {
    editing.value = true;
    form.request_id = requestId();
    action.errors.value = {};
    form.code = '';
    form.confirmed = false;
}
async function submit() {
    let path = '',
        data: Record<string, unknown> = {};
    if (expanded.value === 'name') {
        path = '/account/information/name';
        data = { display_name: form.display_name };
    } else if (expanded.value === 'EMAIL') {
        if (challenge.value && !editing.value) {
            path = '/account/information/contacts/' + challenge.value.id + '/verify';
            data = { code: form.code, confirmed: form.confirmed };
        } else {
            path = '/account/information/contacts';
            data = {
                channel: 'EMAIL',
                new_contact: form.new_contact,
                current_password: form.current_password,
                request_id: form.request_id,
            };
        }
    } else if (expanded.value === 'password') {
        path = '/account/security/password';
        data = {
            current_password: form.current_password,
            password: form.password,
            password_confirmation: form.password_confirmation,
        };
    } else {
        path = '/account/security/sessions/revoke';
        data = { current_password: form.current_password, confirmed: form.confirmed };
    }
    await action.submit(path, data, {
        navigate: false,
        success: async () => {
            form.current_password = '';
            form.password = '';
            form.password_confirmation = '';
            form.code = '';
            form.confirmed = false;
            editing.value = false;
            await bootstrap();
            emit('reload');
        },
    });
}
</script>
<template>
    <PageShell :title="t('Account and security')" back="/account" active="account"
        ><view class="security-content"
            ><view class="verification-row" @click="go('/kyc?from=account-security')"
                ><UiIcon name="scan-face" :size="20" /><view class="grow"
                    ><text class="block">{{ t('Identity verification') }}</text
                    ><text class="muted small">{{ verification }}</text></view
                ><text class="green small">{{
                    t(
                        ['NOT_SUBMITTED', 'RESUBMISSION_REQUIRED'].includes(page.kycStatus)
                            ? 'Go to verification'
                            : 'View details',
                    )
                }}</text
                ><UiIcon name="chevron-right" :size="16" /></view
            ><view class="security-card"
                ><view v-for="item in rows" :key="item.id" class="security-section"
                    ><button
                        class="security-toggle"
                        :disabled="
                            !['password', 'sessions'].includes(item.id) && !page.information.canEdit
                        "
                        :aria-expanded="expanded === item.id"
                        @click="expand(item.id)"
                    >
                        <UiIcon :name="item.icon" :size="20" /><view class="grow"
                            ><text class="row-label">{{ t(item.title) }}</text
                            ><text class="row-value">{{ item.value }}</text></view
                        ><UiIcon name="chevron-down" :size="16" />
                    </button>
                    <form v-if="expanded === item.id" class="security-form" @submit="submit">
                        <FormErrors :errors="action.errors.value" /><template
                            v-if="item.id === 'name'"
                            ><FormField
                                v-model="form.display_name"
                                :label="t('Display name')"
                                :maxlength="80"
                            /><button
                                class="primary wide"
                                form-type="submit"
                                :disabled="action.pending.value"
                            >
                                {{ t('Save name') }}
                            </button></template
                        ><template v-else-if="item.id === 'EMAIL'"
                            ><template v-if="challenge && !editing"
                                ><text class="copy"
                                    >{{ t('New login contact') }}: {{ challenge.destination }}</text
                                ><text class="copy muted">{{
                                    t(
                                        challenge.deliveryUncertain
                                            ? 'Delivery is not confirmed. If a code arrives, use it here; wait until it expires before resending.'
                                            : 'Enter the verification code sent to your new email address.',
                                    )
                                }}</text
                                ><text class="copy muted">{{ remainingLabel }}</text
                                ><FormField
                                    v-model="form.code"
                                    :label="t('Email verification code')"
                                    type="number"
                                    :maxlength="6"
                                /><ConfirmCheck
                                    v-model="form.confirmed"
                                    :label="
                                        t(
                                            'I confirm replacing this login contact. The old contact will no longer work for login.',
                                        )
                                    "
                                /><button
                                    class="primary wide"
                                    form-type="submit"
                                    :disabled="
                                        action.pending.value || !form.confirmed || remaining === 0
                                    "
                                >
                                    {{ t('Confirm contact change') }}</button
                                ><button
                                    class="text-button"
                                    :disabled="action.pending.value || resendRemaining > 0"
                                    @click="newContact"
                                >
                                    {{ resendLabel }}</button
                                ><button
                                    class="text-button"
                                    :disabled="action.pending.value"
                                    @click="newContact"
                                >
                                    {{ t('Change contact details') }}
                                </button></template
                            ><template v-else
                                ><text class="copy muted">{{
                                    t(
                                        'Verify your current password, then enter the code sent to your new email address to save the change.',
                                    )
                                }}</text
                                ><FormField
                                    v-model="form.new_contact"
                                    :label="t('New email address')"
                                    :disabled="action.pending.value"
                                    @update:model-value="form.request_id = requestId()"
                                /><FormField
                                    v-model="form.current_password"
                                    :label="t('Current password')"
                                    password
                                    :maxlength="1024"
                                /><button
                                    class="primary wide"
                                    form-type="submit"
                                    :disabled="action.pending.value"
                                >
                                    {{
                                        t(
                                            action.pending.value
                                                ? 'Sending…'
                                                : 'Send email verification code',
                                        )
                                    }}
                                </button></template
                            ></template
                        ><template v-else
                            ><text class="copy muted">{{
                                t(
                                    item.id === 'password'
                                        ? 'Changing your password requires other devices to sign in again. This device stays signed in.'
                                        : 'Other devices will be blocked on their next request. Your password and administrator login are unchanged.',
                                )
                            }}</text
                            ><FormField
                                v-model="form.current_password"
                                :label="t('Current password')"
                                password
                                :maxlength="1024"
                            /><template v-if="item.id === 'password'"
                                ><FormField
                                    v-model="form.password"
                                    :label="t('New password')"
                                    :description="t('At least 6 characters.')"
                                    password
                                    :maxlength="1024" /><FormField
                                    v-model="form.password_confirmation"
                                    :label="t('Confirm new password')"
                                    password
                                    :maxlength="1024" /></template
                            ><ConfirmCheck
                                v-else
                                v-model="form.confirmed"
                                :label="
                                    t('I confirm signing out all other devices for this account.')
                                "
                            /><button
                                class="primary wide"
                                form-type="submit"
                                :disabled="
                                    action.pending.value ||
                                    (item.id === 'sessions' && !form.confirmed)
                                "
                            >
                                {{
                                    t(
                                        item.id === 'password'
                                            ? 'Change password'
                                            : 'Sign out other devices',
                                    )
                                }}
                            </button></template
                        >
                    </form></view
                ></view
            ></view
        ></PageShell
    >
</template>
<style scoped>
.security-content {
    max-width: 672px;
    margin: auto;
}
.verification-row {
    display: flex;
    gap: 12px;
    align-items: center;
    min-height: 60px;
    padding: 12px 16px;
    border: 1px solid #e2e7e4;
    border-radius: 14px;
    background: white;
    font-size: 14px;
    margin-bottom: 24px;
}
.grow {
    min-width: 0;
    flex: 1;
}
.block {
    display: block;
}
.small {
    font-size: 12px;
}
.security-card {
    overflow: hidden;
    border: 1px solid #e2e7e4;
    border-radius: 24px;
    background: white;
}
.security-section {
    border-bottom: 1px solid #e2e7e4;
}
.security-section:last-child {
    border: 0;
}
.security-toggle {
    display: flex;
    align-items: center;
    gap: 12px;
    min-height: 96px;
    padding: 20px;
    width: 100%;
    text-align: left;
    background: none;
    border-radius: 0;
    line-height: 24px;
}
.security-toggle[disabled] {
    opacity: 0.5;
}
.row-label {
    display: block;
    font-size: 14px;
    color: #68736e;
}
.row-value {
    display: block;
    margin-top: 4px;
    font-size: 16px;
    font-weight: 500;
    overflow-wrap: anywhere;
}
.security-form {
    padding: 0 20px 24px;
}
.copy {
    display: block;
    font-size: 14px;
    line-height: 1.6;
    margin-bottom: 16px;
}
.wide {
    width: 100%;
    border-radius: 999px;
    padding: 10px 20px;
    min-height: 44px;
    font-size: 14px;
    line-height: 24px;
}
.text-button {
    width: 100%;
    background: none;
    font-size: 14px;
    padding: 10px;
    line-height: 24px;
    margin-top: 8px;
}
.text-button[disabled] {
    opacity: 0.5;
}
</style>

// resources/js/pages/user/Security.tsx
import { t, useClientTranslation, errorMessage } from '@/i18n';
import { Head, useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import {
    ChevronDown,
    Mail,
    LockKeyhole,
    UserRoundPen,
    MonitorX,
    type LucideIcon,
} from 'lucide-react';
import type { SharedProps } from '@/types/global';
import {
    ContactForm,
    NameForm,
    type ContactChallenge,
} from '@/components/user/AccountInformationForms';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { FormField } from '@/components/ui/form-field';
import { Input } from '@/components/ui/input';
import { AccountVerificationLink } from '@/components/user/AccountVerificationLink';
import { UserLayout } from '@/layouts/UserLayout';

type Information = {
    canEdit: boolean;
    email: string | null;
    challenge: ContactChallenge | null;
};

export default function Security({
    information,
    kycStatus,
}: {
    information: Information;
    kycStatus: string;
}) {
    useClientTranslation();
    const { auth } = usePage<SharedProps>().props;
    const [expanded, setExpanded] = useState<string | null>(
        information.challenge?.channel === 'EMAIL' ? 'EMAIL' : null,
    );
    const items: { id: string; title: string; value: string; icon: LucideIcon }[] = [
        {
            id: 'name',
            title: t('Display name'),
            value: auth.user?.displayName || t('Account user'),
            icon: UserRoundPen,
        },
        {
            id: 'EMAIL',
            title: t('Email address'),
            value: information.email || t('Not linked'),
            icon: Mail,
        },
        { id: 'password', title: t('Change password'), value: '••••••••', icon: LockKeyhole },
        {
            id: 'sessions',
            title: t('Sign out other devices'),
            value: t('Keep this device signed in'),
            icon: MonitorX,
        },
    ];
    return (
        <UserLayout>
            <Head title={t('Account and security')} />
            <div className="mx-auto max-w-2xl space-y-6">
                <UserPageHeader title={t('Account and security')} backHref="/account" />
                <AccountVerificationLink status={kycStatus} fromSecurity />
                <div className="overflow-hidden rounded-3xl border bg-surface">
                    {items.map(({ id, title, value, icon: Icon }) => (
                        <section key={id} className="border-b last:border-0">
                            <h2>
                                <button
                                    type="button"
                                    className="flex min-h-24 w-full items-center gap-3 px-5 py-5 text-left disabled:opacity-50 sm:px-6"
                                    disabled={
                                        !['password', 'sessions'].includes(id) &&
                                        !information.canEdit
                                    }
                                    aria-expanded={expanded === id}
                                    aria-controls={`information-${id}`}
                                    onClick={() => setExpanded(expanded === id ? null : id)}
                                >
                                    <Icon
                                        className="size-5 shrink-0 text-[var(--user-primary)]"
                                        aria-hidden="true"
                                    />
                                    <span className="min-w-0 flex-1">
                                        <span className="block text-sm text-muted-foreground">
                                            {title}
                                        </span>
                                        <span className="mt-1 block font-medium break-all">
                                            {value}
                                        </span>
                                    </span>
                                    <ChevronDown
                                        className={`size-4 shrink-0 text-muted-foreground ${expanded === id ? 'rotate-180' : ''}`}
                                        aria-hidden="true"
                                    />
                                </button>
                            </h2>
                            <div
                                id={`information-${id}`}
                                hidden={expanded !== id}
                                className="px-5 pb-6 sm:px-6"
                            >
                                {id === 'name' && <NameForm name={auth.user?.displayName ?? ''} />}
                                {id === 'EMAIL' && (
                                    <ContactForm channel={id} challenge={information.challenge} />
                                )}
                                {id === 'password' && <PasswordForm />}
                                {id === 'sessions' && <RevokeSessionsForm />}
                            </div>
                        </section>
                    ))}
                </div>
            </div>
        </UserLayout>
    );
}

function PasswordForm() {
    useClientTranslation();
    const form = useForm({ current_password: '', password: '', password_confirmation: '' });
    const formError = (form.errors as Record<string, string>).form;
    return (
        <form
            className="space-y-5"
            onSubmit={(event) => {
                event.preventDefault();
                form.post('/account/security/password', {
                    onSuccess: () => form.reset(),
                });
            }}
        >
            <p className="text-sm text-muted-foreground">
                {t(
                    'Changing your password requires other devices to sign in again. This device stays signed in.',
                )}
            </p>
            {formError && (
                <Alert className="border-red-200 bg-red-50 text-red-800">
                    <AlertTitle>{t('Password not changed')}</AlertTitle>
                    <AlertDescription>{errorMessage(formError)}</AlertDescription>
                </Alert>
            )}
            <FormField
                id="current_password"
                label={t('Current password')}
                error={errorMessage(form.errors.current_password)}
            >
                <Input
                    id="current_password"
                    type="password"
                    autoComplete="current-password"
                    value={form.data.current_password}
                    onChange={(event) => form.setData('current_password', event.target.value)}
                    required
                />
            </FormField>
            <FormField
                id="password"
                label={t('New password')}
                description={t('At least 6 characters.')}
                error={errorMessage(form.errors.password)}
            >
                <Input
                    id="password"
                    type="password"
                    autoComplete="new-password"
                    value={form.data.password}
                    onChange={(event) => form.setData('password', event.target.value)}
                    required
                />
            </FormField>
            <FormField id="password_confirmation" label={t('Confirm new password')}>
                <Input
                    id="password_confirmation"
                    type="password"
                    autoComplete="new-password"
                    value={form.data.password_confirmation}
                    onChange={(event) => form.setData('password_confirmation', event.target.value)}
                    required
                />
            </FormField>
            <Button className="w-full sm:w-auto" type="submit" disabled={form.processing}>
                {t('Change password')}
            </Button>
        </form>
    );
}

function RevokeSessionsForm() {
    const form = useForm({ current_password: '', confirmed: false });
    return (
        <form
            className="space-y-4"
            onSubmit={(event) => {
                event.preventDefault();
                form.post('/account/security/sessions/revoke', {
                    preserveScroll: true,
                    onSuccess: () => form.reset(),
                });
            }}
        >
            <p className="text-sm text-muted-foreground">
                {t(
                    'Other devices will be blocked on their next request. Your password and administrator login are unchanged.',
                )}
            </p>
            {Object.keys(form.errors).length > 0 && (
                <div role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">
                    {Object.values(form.errors).map((error, index) => (
                        <p key={index}>{errorMessage(error)}</p>
                    ))}
                </div>
            )}
            <FormField id="revoke_current_password" label={t('Current password')}>
                <Input
                    id="revoke_current_password"
                    type="password"
                    autoComplete="current-password"
                    required
                    value={form.data.current_password}
                    onChange={(event) => form.setData('current_password', event.target.value)}
                />
            </FormField>
            <label className="flex items-start gap-3 text-sm leading-6">
                <input
                    type="checkbox"
                    className="mt-1 size-4 shrink-0 accent-[var(--user-primary)]"
                    required
                    checked={form.data.confirmed}
                    onChange={(event) => form.setData('confirmed', event.target.checked)}
                />
                <span>{t('I confirm signing out all other devices for this account.')}</span>
            </label>
            <Button
                type="submit"
                className="w-full"
                disabled={form.processing || !form.data.confirmed}
            >
                {t('Sign out other devices')}
            </Button>
        </form>
    );
}
