// mobile/uni-app/src/screens/Topup.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import PageShell from '../components/PageShell.vue';
import StatusBanner from '../components/StatusBanner.vue';
import FormField from '../components/FormField.vue';
import FormErrors from '../components/FormErrors.vue';
import { t, dateTime } from '../lib/i18n';
import { go } from '../lib/navigation';
import { useAction, requestId } from '../lib/client';
import { exactAmount, meetsTopupMinimum } from '../generated/exact-amount';
const props = defineProps<{
    page: {
        available: { amount: string; asset: string } | null;
        wallet: { id: string; asset: string } | null;
        topupAvailable: boolean;
        minimum: string;
        orders: {
            id: string;
            expectedAmount: string;
            asset: string;
            status: string;
            createdAt: string;
        }[];
    };
}>();
const action = useAction(),
    amount = ref(''),
    intent = ref(requestId());
const valid = computed(() => meetsTopupMinimum(amount.value, props.page.minimum));
async function submit() {
    await action.submit('/wallet/top-ups', {
        request_id: intent.value,
        requested_amount: amount.value,
    });
}
</script>
<template>
    <PageShell :title="t('Top up')" back="/dashboard" active="assets"
        ><view v-if="page.available" class="available-hero"
            ><text class="muted">{{ t('Available balance') }}</text
            ><text class="available-value"
                >{{ exactAmount(page.available.amount) }} {{ page.available.asset }}</text
            ></view
        ><FormErrors :errors="action.errors.value" /><StatusBanner
            v-if="!page.topupAvailable || !page.wallet"
            :title="t('Top-up unavailable')"
            :description="t('An active verified USDT wallet is required for TRC20 top-ups.')"
            tone="warning"
        />
        <form v-else class="topup-card" @submit="submit">
            <FormField
                v-model="amount"
                :label="t('Amount') + ' · USDT'"
                placeholder="100.00"
                type="digit"
                :disabled="action.pending.value"
                @update:model-value="intent = requestId()"
            /><text class="hint"
                >{{ t('Minimum deposit') }}: {{ exactAmount(page.minimum) }} USDT ·
                {{ t('TRC20 · No top-up fee') }}</text
            ><button
                class="primary wide"
                form-type="submit"
                :disabled="!valid || action.pending.value"
            >
                {{ t(action.pending.value ? 'Creating instructions…' : 'Continue') }}
            </button>
        </form>
        <text class="section-title">{{ t('Top-up history') }}</text
        ><view v-if="!page.orders.length" class="empty"
            ><text class="block">{{ t('No top-ups yet') }}</text
            ><text>{{ t('Your top-up history will appear here.') }}</text></view
        ><view
            v-for="order in page.orders"
            :key="order.id"
            class="order-row"
            @click="go('/wallet/top-ups/' + order.id + '/return')"
            ><view
                ><text class="block">{{ t('USDT top up') }}</text
                ><text class="muted small">{{ dateTime(order.createdAt) }}</text></view
            ><view class="order-value"
                ><text class="block">{{ exactAmount(order.expectedAmount) }} {{ order.asset }}</text
                ><text class="muted small">{{ t(order.status) }}</text></view
            ></view
        ></PageShell
    >
</template>
<style scoped>
.available-hero {
    padding: 24px 0;
    text-align: center;
}
.available-value {
    display: block;
    margin-top: 12px;
    font-size: 32px;
    font-weight: 600;
    overflow-wrap: anywhere;
}
.topup-card {
    padding: 20px;
    border: 1px solid #e2e7e4;
    background: white;
    border-radius: 24px;
}
.hint {
    display: block;
    font-size: 12px;
    color: #68736e;
    line-height: 20px;
}
.wide {
    width: 100%;
    margin-top: 20px;
    min-height: 44px;
    padding: 10px 20px;
    line-height: 24px;
    border-radius: 999px;
}
.section-title {
    display: block;
    font-size: 18px;
    font-weight: 600;
    margin: 24px 0 16px;
}
.order-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 16px 0;
    border-bottom: 1px solid #e2e7e4;
    font-size: 14px;
}
.order-value {
    text-align: right;
    font-weight: 600;
    overflow-wrap: anywhere;
}
.block {
    display: block;
}
.small {
    font-size: 12px;
}
</style>

// resources/js/pages/user/Topup.tsx
import { meetsTopupMinimum, exactAmount } from '@/lib/exact-amount';
import { t, useClientTranslation, dateTime } from '@/i18n';
import { Head, router } from '@inertiajs/react';
import { useRef, useState } from 'react';
import { MoneyDisplay } from '@/components/shared/MoneyDisplay';
import { UserBalanceHero } from '@/components/user/UserBalanceHero';
import { UserEmptyState } from '@/components/user/UserEmptyState';
import { UserListRow } from '@/components/user/UserListRow';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { UserSection } from '@/components/user/UserSection';
import { UserStatusBanner } from '@/components/user/UserStatusBanner';
import { Button } from '@/components/ui/button';
import { FormField } from '@/components/ui/form-field';
import { Input } from '@/components/ui/input';
import { UserLayout } from '@/layouts/UserLayout';
import type { MoneyAmount } from '@/types/global';

type OrderStatus =
    | 'WAITING'
    | 'CONFIRMING'
    | 'ADDING_FUNDS'
    | 'PROCESSING'
    | 'COMPLETED'
    | 'FAILED'
    | 'CANCELLED'
    | 'EXPIRED';
type Order = {
    id: string;
    reference: string;
    requestedAmount: MoneyAmount;
    expectedAmount: MoneyAmount;
    asset: string;
    status: OrderStatus;
    createdAt: string;
};
type Props = {
    available: { amount: MoneyAmount; asset: string } | null;
    wallet: { id: string; asset: string } | null;
    topupAvailable: boolean;
    minimum: string;
    orders: Order[];
};

const statusLabel = (status: OrderStatus) =>
    ({
        WAITING: 'Waiting for payment',
        CONFIRMING: 'Confirming transaction',
        ADDING_FUNDS: 'Adding funds to wallet',
        PROCESSING: 'Processing',
        COMPLETED: 'Top-up complete',
        FAILED: 'Failed',
        CANCELLED: 'Cancelled',
        EXPIRED: 'Top-up expired',
    })[status];

export default function Topup({ available, wallet, topupAvailable, orders, minimum }: Props) {
    useClientTranslation();
    const [amount, setAmount] = useState('');
    const [processing, setProcessing] = useState(false);
    const requestId = useRef(crypto.randomUUID());
    const canContinue = meetsTopupMinimum(amount, minimum);

    const submit = () => {
        if (!wallet || !canContinue || processing) return;
        setProcessing(true);
        router.post(
            '/wallet/top-ups',
            { request_id: requestId.current, requested_amount: amount },
            { onFinish: () => setProcessing(false) },
        );
    };

    return (
        <UserLayout>
            <Head title={t('Top up')} />
            <div className="space-y-6 sm:space-y-8">
                <UserPageHeader title={t('Top up')} backHref="/dashboard" />
                {available ? (
                    <UserBalanceHero
                        amount={available.amount}
                        asset={available.asset}
                        assetLabel="USDT"
                    />
                ) : null}
                {!topupAvailable || !wallet ? (
                    <UserStatusBanner
                        tone="warning"
                        title={t('Top-up unavailable')}
                        description={t(
                            'An active verified USDT wallet is required for TRC20 top-ups.',
                        )}
                    />
                ) : (
                    <form
                        className="rounded-[var(--user-radius-lg)] border bg-surface p-5 sm:p-7"
                        onSubmit={(event) => {
                            event.preventDefault();
                            submit();
                        }}
                    >
                        <FormField label={t('Amount')} id="topup-amount">
                            <div className="flex items-center gap-3">
                                <Input
                                    id="topup-amount"
                                    inputMode="decimal"
                                    autoComplete="off"
                                    placeholder="100.00"
                                    value={amount}
                                    disabled={processing}
                                    onChange={(event) => setAmount(event.target.value)}
                                />
                                <span className="text-sm font-semibold">USDT</span>
                            </div>
                        </FormField>
                        <p className="mt-3 text-xs leading-5 text-muted-foreground">
                            {t('Minimum deposit')}: {exactAmount(minimum)} {'USDT'} ·{' '}
                            {t('TRC20 · No top-up fee')}
                        </p>
                        <Button className="mt-5 w-full" disabled={!canContinue || processing}>
                            {processing ? t('Creating instructions…') : t('Continue')}
                        </Button>
                    </form>
                )}
                <UserSection title={t('Top-up history')}>
                    {orders.length === 0 ? (
                        <UserEmptyState
                            title={t('No top-ups yet')}
                            description={t('Your top-up history will appear here.')}
                        />
                    ) : (
                        <div className="divide-y">
                            {orders.map((order) => (
                                <UserListRow
                                    key={order.id}
                                    href={`/wallet/top-ups/${order.id}/return`}
                                    title={t('USDT top up')}
                                    description={dateTime(order.createdAt)}
                                    value={
                                        <span className="text-right">
                                            <span className="block font-semibold">
                                                <MoneyDisplay
                                                    amount={order.expectedAmount}
                                                    asset={order.asset}
                                                    compact
                                                />
                                            </span>
                                            <span className="text-xs text-muted-foreground">
                                                {t(statusLabel(order.status))}
                                            </span>
                                        </span>
                                    }
                                />
                            ))}
                        </div>
                    )}
                </UserSection>
            </div>
        </UserLayout>
    );
}
