// mobile/uni-app/src/screens/Transfer.vue
<script setup lang="ts">
import { useSensitiveScreen } from '../lib/sensitive';
import { computed, reactive, ref, onBeforeUnmount } from 'vue';
import PageShell from '../components/PageShell.vue';
import FormField from '../components/FormField.vue';
import FormErrors from '../components/FormErrors.vue';
import SelectField from '../components/SelectField.vue';
import ConfirmCheck from '../components/ConfirmCheck.vue';
import UiIcon from '../components/UiIcon.vue';
import { t, dateTime } from '../lib/i18n';
import { session } from '../lib/session';
import { useAction, requestId } from '../lib/client';
import { go } from '../lib/navigation';
import { exactAmount } from '../generated/exact-amount';
type Draft = { request_id: string; recipient_account_id: string; amount: string; asset: string };
type Receipt = {
    id: string;
    requestId: string;
    amount: string;
    asset: string;
    sent: boolean;
    senderAccountId: string;
    recipientAccountId: string;
    createdAt: string;
};
const props = defineProps<{
    page: {
        accountId: string;
        assets: { asset: string; amount: string; scale: number; available: boolean }[];
        transferAvailable: boolean;
        receipt: Receipt | null;
    };
}>();
const scales: Record<string, number> = { USDT: 8, USDC: 6, ETH: 18, BTC: 8 };
const key = `wallet-transfer:${session.value?.tenant.id}:${props.page.accountId}`;
function validAmount(amount: string, asset: string) {
    return (
        asset in scales &&
        new RegExp('^(?:0|[1-9][0-9]{0,11})(?:\\.[0-9]{1,' + scales[asset] + '})?$').test(amount) &&
        /[1-9]/.test(amount)
    );
}
function readDraft(): Draft | null {
    try {
        const d = uni.getStorageSync(key);
        return d &&
            typeof d === 'object' &&
            typeof d.request_id === 'string' &&
            /^[a-f0-9-]{36}$/.test(d.request_id) &&
            typeof d.recipient_account_id === 'string' &&
            /^\d{12}$/.test(d.recipient_account_id) &&
            typeof d.amount === 'string' &&
            typeof d.asset === 'string' &&
            validAmount(d.amount, d.asset)
            ? d
            : null;
    } catch {
        return null;
    }
}
const draft = readDraft();
if (props.page.receipt && props.page.receipt.requestId === draft?.request_id)
    uni.removeStorageSync(key);
const form = reactive({
    request_id: draft?.request_id ?? requestId(),
    recipient_account_id: draft?.recipient_account_id ?? '',
    amount: draft?.amount ?? '',
    asset: draft?.asset ?? 'USDT',
    current_password: '',
    confirmed: false,
});
const action = useAction(),
    reviewing = ref(!!draft),
    attempted = ref(!!draft);
const selected = computed(() => props.page.assets.find((a) => a.asset === form.asset));
useSensitiveScreen(() => {
    form.current_password = '';
    form.confirmed = false;
});
function changed() {
    form.request_id = requestId();
    form.confirmed = false;
    action.errors.value = {};
}
function edit() {
    if (action.pending.value || attempted.value) return;
    reviewing.value = false;
    form.current_password = '';
    form.confirmed = false;
    form.request_id = requestId();
}
async function submit() {
    if (action.pending.value) return;
    if (!reviewing.value) {
        if (!validAmount(form.amount, form.asset)) {
            action.errors.value = { amount: t('Enter a positive transfer amount.') };
            return;
        }
        if (
            !/^\d{12}$/.test(form.recipient_account_id) ||
            form.recipient_account_id === props.page.accountId
        ) {
            action.errors.value = {
                recipient_account_id: t(
                    'The recipient is unavailable. Check the account ID and company.',
                ),
            };
            return;
        }
        action.errors.value = {};
        reviewing.value = true;
        return;
    }
    if (!form.confirmed || !form.current_password) return;
    try {
        uni.setStorageSync(key, {
            request_id: form.request_id,
            recipient_account_id: form.recipient_account_id,
            amount: form.amount,
            asset: form.asset,
        });
        if (readDraft()?.request_id !== form.request_id) throw Error();
    } catch {
        action.errors.value = {
            form: t('Transfer retry details could not be saved. Please enable browser storage.'),
        };
        return;
    }
    attempted.value = true;
    await action.submit('/wallet/transfers', { ...form });
    if (action.failureStatus.value === 422) {
        attempted.value = false;
        uni.removeStorageSync(key);
    }
    form.current_password = '';
    form.confirmed = false;
}
</script>
<template>
    <PageShell :title="t('Transfer')" back="/dashboard" active="assets"
        ><view v-if="page.receipt" class="transfer-receipt"
            ><view class="receipt-summary"
                ><view class="receipt-icon"><UiIcon name="circle-check" :size="40" /></view
                ><text class="receipt-title">{{ t('Transfer completed.') }}</text
                ><text class="receipt-amount"
                    >{{ exactAmount(page.receipt.amount) }} {{ page.receipt.asset }}</text
                ></view
            ><view class="receipt-details"
                ><view
                    v-for="item in [
                        { label: 'Sender account ID', value: page.receipt.senderAccountId },
                        { label: 'Recipient account ID', value: page.receipt.recipientAccountId },
                        { label: 'Time', value: dateTime(page.receipt.createdAt) },
                        { label: 'Transfer reference', value: page.receipt.id },
                    ]"
                    :key="item.label"
                    ><text>{{ t(item.label) }}</text
                    ><text selectable>{{ item.value }}</text></view
                ></view
            ><view class="receipt-actions"
                ><button class="primary" @click="go('/wallet/transfer', true)">
                    {{ t('New transfer') }}</button
                ><button class="secondary" @click="go('/dashboard')">
                    {{ t('Back to home') }}
                </button></view
            ></view
        ><text v-else-if="!page.transferAvailable" class="muted">{{
            t('Both accounts need active verified wallets in the same currency.')
        }}</text>
        <form v-else @submit="submit">
            <view class="transfer-balance"
                ><text class="muted">{{ t('Available balance') }}</text
                ><text class="balance-amount"
                    >{{ exactAmount(selected?.amount ?? '0') }} {{ form.asset }}</text
                ></view
            ><FormErrors :errors="action.errors.value" /><template v-if="!reviewing"
                ><SelectField
                    v-model="form.asset"
                    :label="t('Currency')"
                    :options="page.assets.map((a) => ({ value: a.asset, label: a.asset }))"
                    @update:model-value="
                        () => {
                            form.amount = '';
                            changed();
                        }
                    "
                /><FormField
                    v-model="form.recipient_account_id"
                    :label="t('Recipient account ID')"
                    type="number"
                    :maxlength="12"
                    @update:model-value="changed"
                /><FormField
                    v-model="form.amount"
                    :label="t('Transfer amount')"
                    :description="form.asset"
                    type="digit"
                    @update:model-value="changed"
                /><text v-if="!selected?.available" class="muted">{{
                    t('Both accounts need active verified wallets in the same currency.')
                }}</text
                ><button class="primary" form-type="submit" :disabled="!selected?.available">
                    {{ t('Review transfer') }}
                </button></template
            ><template v-else
                ><view class="transfer-review"
                    ><text class="review-title">{{ t('Review transfer') }}</text
                    ><text>{{ t('Recipient account ID') }}: {{ form.recipient_account_id }}</text
                    ><text
                        >{{ t('Transfer amount') }}: {{ exactAmount(form.amount) }}
                        {{ form.asset }}</text
                    ><text class="review-note">{{
                        t(
                            'The same amount will be credited to the recipient. Check the account ID carefully; completed transfers cannot be cancelled here.',
                        )
                    }}</text></view
                ><FormField
                    v-model="form.current_password"
                    :label="t('Current password')"
                    password
                    :maxlength="1024"
                    :disabled="action.pending.value"
                /><ConfirmCheck
                    v-model="form.confirmed"
                    :label="t('I have checked the recipient and amount and confirm this transfer.')"
                    :disabled="action.pending.value"
                /><view class="transfer-buttons"
                    ><button
                        class="primary"
                        form-type="submit"
                        :disabled="
                            action.pending.value || !form.confirmed || !form.current_password
                        "
                    >
                        {{ t('Confirm transfer') }}</button
                    ><button
                        class="secondary"
                        :disabled="action.pending.value || attempted"
                        @click="edit"
                    >
                        {{ t('Edit') }}
                    </button></view
                ><text v-if="attempted" class="retry-copy">{{
                    t(
                        'If the result is unclear, retry this same transfer. Do not start a new request.',
                    )
                }}</text></template
            >
        </form></PageShell
    >
</template>
<style scoped>
.transfer-balance {
    margin-bottom: 20px;
}
.balance-amount {
    display: block;
    font-size: 30px;
    line-height: 36px;
    font-weight: 600;
    overflow-wrap: anywhere;
}
.transfer-review {
    display: flex;
    flex-direction: column;
    gap: 12px;
    border: 1px solid #e2e7e4;
    border-radius: 12px;
    padding: 16px;
    margin-bottom: 20px;
    overflow-wrap: anywhere;
}
.review-title {
    font-weight: 600;
}
.review-note {
    font-size: 14px;
    line-height: 1.6;
}
.transfer-buttons {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
}
.primary,
.secondary {
    min-height: 44px;
    border-radius: 999px;
    padding: 10px 24px;
    font-size: 14px;
    line-height: 24px;
}
.retry-copy {
    display: block;
    margin-top: 20px;
    font-size: 14px;
    color: #68736e;
    line-height: 1.6;
}
.transfer-receipt {
    max-width: 480px;
    margin: auto;
}
.receipt-summary {
    text-align: center;
    padding: 32px 12px 28px;
}
.receipt-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 64px;
    height: 64px;
    margin: 0 auto 20px;
    border-radius: 50%;
    background: #e7f7ef;
    color: #1b8a61;
}
.receipt-title {
    display: block;
    font-size: 20px;
    font-weight: 600;
}
.receipt-amount {
    display: block;
    font-size: 32px;
    font-weight: 600;
    line-height: 1.3;
    margin-top: 16px;
    overflow-wrap: anywhere;
}
.receipt-details {
    border-top: 1px solid #e2e7e4;
}
.receipt-details > view {
    display: grid;
    grid-template-columns: 1fr 1.3fr;
    gap: 20px;
    padding: 18px 0;
    border-bottom: 1px solid #e2e7e4;
    font-size: 14px;
}
.receipt-details > view > text:first-child {
    color: #68736e;
}
.receipt-details > view > text:last-child {
    text-align: right;
    overflow-wrap: anywhere;
}
.receipt-actions {
    display: grid;
    gap: 12px;
    margin-top: 28px;
}
</style>

// resources/js/pages/user/Transfer.tsx
import { useEffect, useState } from 'react';
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { CheckCircle2 } from 'lucide-react';
import { t, useClientTranslation, errorMessage, dateTime } from '@/i18n';
import { UserLayout } from '@/layouts/UserLayout';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { FormField } from '@/components/ui/form-field';
import {
    Select,
    SelectTrigger,
    SelectValue,
    SelectContent,
    SelectItem,
} from '@/components/ui/select';
import type { SharedProps } from '@/types/global';

const scales: Record<string, number> = { USDT: 8, USDC: 6, ETH: 18, BTC: 8 };
const amountPattern = (asset: string) =>
    `(?:0|[1-9][0-9]{0,11})(?:\\.[0-9]{1,${scales[asset] ?? 8}})?`;
const exactAmount = (amount: string) =>
    amount.includes('.') ? amount.replace(/0+$/, '').replace(/\.$/, '') : amount;
type Draft = { request_id: string; recipient_account_id: string; amount: string; asset: string };
type Asset = { asset: string; amount: string; scale: number; available: boolean };
type Receipt = {
    id: string;
    requestId: string;
    amount: string;
    asset: string;
    sent: boolean;
    senderAccountId: string;
    recipientAccountId: string;
    createdAt: string;
};
function readDraft(key: string): Draft | null {
    try {
        const value: unknown = JSON.parse(sessionStorage.getItem(key) ?? 'null');
        if (!value || typeof value !== 'object') return null;
        const draft = value as Partial<Draft>;
        return typeof draft.request_id === 'string' &&
            /^[0-9a-f-]{36}$/.test(draft.request_id) &&
            typeof draft.recipient_account_id === 'string' &&
            /^\d{12}$/.test(draft.recipient_account_id) &&
            typeof draft.amount === 'string' &&
            typeof draft.asset === 'string' &&
            Object.hasOwn(scales, draft.asset) &&
            new RegExp(`^${amountPattern(draft.asset)}$`).test(draft.amount)
            ? (draft as Draft)
            : null;
    } catch {
        return null;
    }
}

export default function Transfer({
    accountId,
    assets,
    transferAvailable,
    receipt,
}: {
    accountId: string;
    assets: Asset[];
    transferAvailable: boolean;
    receipt: Receipt | null;
}) {
    useClientTranslation();
    const { tenant } = usePage<SharedProps>().props;
    const storageKey = `wallet-transfer:${tenant?.id}:${accountId}`;
    const [draft] = useState(() => readDraft(storageKey));
    const [reviewing, setReviewing] = useState(draft !== null);
    const [attempted, setAttempted] = useState(draft !== null);
    const form = useForm({
        request_id: draft?.request_id ?? crypto.randomUUID(),
        recipient_account_id: draft?.recipient_account_id ?? '',
        amount: draft?.amount ?? '',
        asset: draft?.asset ?? 'USDT',
        current_password: '',
        confirmed: false,
        form: '',
    });
    const selected = assets.find((asset) => asset.asset === form.data.asset);
    useEffect(() => {
        try {
            if (receipt && receipt.requestId === readDraft(storageKey)?.request_id)
                sessionStorage.removeItem(storageKey);
        } catch {
            // The immutable receipt remains authoritative if browser storage is blocked.
        }
    }, [receipt, storageKey]);
    return (
        <UserLayout handledSuccessMessage={receipt ? 'Transfer completed.' : undefined}>
            <Head title={t('Transfer')} />
            <div className="space-y-6">
                <UserPageHeader title={t('Transfer')} backHref="/dashboard" />
                {receipt ? (
                    <section className="transfer-receipt" aria-labelledby="transfer-result-title">
                        <div className="transfer-receipt-summary" role="status">
                            <span className="transfer-receipt-icon">
                                <CheckCircle2 aria-hidden="true" />
                            </span>
                            <h2 id="transfer-result-title">{t('Transfer completed.')}</h2>
                            <p className="transfer-receipt-amount break-all">
                                {exactAmount(receipt.amount)} {receipt.asset}
                            </p>
                        </div>
                        <dl className="transfer-receipt-details">
                            <div>
                                <dt>{t('Sender account ID')}</dt>
                                <dd className="tabular-nums">{receipt.senderAccountId}</dd>
                            </div>
                            <div>
                                <dt>{t('Recipient account ID')}</dt>
                                <dd className="tabular-nums">{receipt.recipientAccountId}</dd>
                            </div>
                            <div>
                                <dt>{t('Time')}</dt>
                                <dd>{dateTime(receipt.createdAt)}</dd>
                            </div>
                            <div className="transfer-receipt-reference">
                                <dt>{t('Transfer reference')}</dt>
                                <dd>{receipt.id}</dd>
                            </div>
                        </dl>
                        <div className="transfer-receipt-actions">
                            <Button asChild>
                                <Link href="/wallet/transfer">{t('New transfer')}</Link>
                            </Button>
                            <Button asChild variant="secondary">
                                <Link href="/dashboard">{t('Back to home')}</Link>
                            </Button>
                        </div>
                    </section>
                ) : !transferAvailable ? (
                    <p role="status">
                        {t('Both accounts need active verified wallets in the same currency.')}
                    </p>
                ) : (
                    <form
                        className="space-y-5"
                        onSubmit={(event) => {
                            event.preventDefault();
                            if (form.processing) return;
                            if (!reviewing) {
                                if (
                                    !new RegExp(`^${amountPattern(form.data.asset)}$`).test(
                                        form.data.amount,
                                    ) ||
                                    !/[1-9]/.test(form.data.amount)
                                ) {
                                    form.setError('amount', 'Enter a positive transfer amount.');
                                    return;
                                }
                                if (form.data.recipient_account_id === accountId) {
                                    form.setError(
                                        'recipient_account_id',
                                        'The recipient is unavailable. Check the account ID and company.',
                                    );
                                    return;
                                }
                                form.clearErrors();
                                setReviewing(true);
                                return;
                            }
                            if (!form.data.confirmed || !form.data.current_password) return;
                            try {
                                sessionStorage.setItem(
                                    storageKey,
                                    JSON.stringify({
                                        request_id: form.data.request_id,
                                        recipient_account_id: form.data.recipient_account_id,
                                        amount: form.data.amount,
                                        asset: form.data.asset,
                                    }),
                                );
                            } catch {
                                form.setError(
                                    'form',
                                    'Transfer retry details could not be saved. Please enable browser storage.',
                                );
                                return;
                            }
                            setAttempted(true);
                            form.post('/wallet/transfers', {
                                preserveScroll: true,
                                onError: () => setAttempted(false),
                                onFinish: () => form.reset('current_password', 'confirmed'),
                            });
                        }}
                    >
                        <div>
                            <p className="text-sm text-muted-foreground">
                                {t('Available balance')}
                            </p>
                            <p className="text-3xl font-semibold break-all">
                                {exactAmount(selected?.amount ?? '0')} {form.data.asset}
                            </p>
                        </div>
                        {!reviewing ? (
                            <>
                                <FormField
                                    id="transfer-asset"
                                    label={t('Currency')}
                                    error={errorMessage(form.errors.asset)}
                                >
                                    <Select
                                        value={form.data.asset}
                                        onValueChange={(asset) => {
                                            form.setData((data) => ({
                                                ...data,
                                                asset,
                                                amount: '',
                                                current_password: '',
                                                confirmed: false,
                                            }));
                                            form.clearErrors();
                                        }}
                                    >
                                        <SelectTrigger id="transfer-asset">
                                            <SelectValue />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {assets.map((asset) => (
                                                <SelectItem key={asset.asset} value={asset.asset}>
                                                    {asset.asset}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </FormField>
                                <FormField
                                    id="recipient-account-id"
                                    label={t('Recipient account ID')}
                                    error={errorMessage(form.errors.recipient_account_id)}
                                >
                                    <Input
                                        id="recipient-account-id"
                                        inputMode="numeric"
                                        pattern="[0-9]{12}"
                                        maxLength={12}
                                        required
                                        value={form.data.recipient_account_id}
                                        onChange={(e) =>
                                            form.setData(
                                                'recipient_account_id',
                                                e.target.value.replace(/\D/g, ''),
                                            )
                                        }
                                    />
                                </FormField>
                                <FormField
                                    id="transfer-amount"
                                    label={t('Transfer amount')}
                                    error={errorMessage(form.errors.amount)}
                                    description={form.data.asset}
                                >
                                    <Input
                                        id="transfer-amount"
                                        inputMode="decimal"
                                        pattern={amountPattern(form.data.asset)}
                                        required
                                        value={form.data.amount}
                                        onChange={(e) => form.setData('amount', e.target.value)}
                                    />
                                </FormField>
                                {!selected?.available && (
                                    <p role="status">
                                        {t(
                                            'Both accounts need active verified wallets in the same currency.',
                                        )}
                                    </p>
                                )}
                                <Button type="submit" disabled={!selected?.available}>
                                    {t('Review transfer')}
                                </Button>
                            </>
                        ) : (
                            <>
                                <div className="rounded-xl border p-4 space-y-3">
                                    <h2 className="font-semibold">{t('Review transfer')}</h2>
                                    <p>
                                        {t('Recipient account ID')}:{' '}
                                        <span className="font-mono">
                                            {form.data.recipient_account_id}
                                        </span>
                                    </p>
                                    <p className="break-all">
                                        {t('Transfer amount')}: {exactAmount(form.data.amount)}{' '}
                                        {form.data.asset}
                                    </p>
                                    <p className="text-sm">
                                        {t(
                                            'The same amount will be credited to the recipient. Check the account ID carefully; completed transfers cannot be cancelled here.',
                                        )}
                                    </p>
                                </div>
                                <FormField
                                    id="transfer-password"
                                    label={t('Current password')}
                                    error={errorMessage(form.errors.current_password)}
                                >
                                    <Input
                                        id="transfer-password"
                                        type="password"
                                        autoComplete="current-password"
                                        value={form.data.current_password}
                                        onChange={(e) =>
                                            form.setData('current_password', e.target.value)
                                        }
                                        required
                                    />
                                </FormField>
                                <label className="flex min-h-11 gap-3 items-start text-sm">
                                    <Checkbox
                                        className="shrink-0 min-h-5!"
                                        checked={form.data.confirmed}
                                        onCheckedChange={(value) =>
                                            form.setData('confirmed', value === true)
                                        }
                                    />
                                    <span>
                                        {t(
                                            'I have checked the recipient and amount and confirm this transfer.',
                                        )}
                                    </span>
                                </label>
                                <div className="flex flex-wrap gap-3">
                                    <Button
                                        type="submit"
                                        disabled={
                                            form.processing ||
                                            !form.data.confirmed ||
                                            !form.data.current_password
                                        }
                                    >
                                        {t('Confirm transfer')}
                                    </Button>
                                    <Button
                                        type="button"
                                        variant="secondary"
                                        disabled={form.processing || attempted}
                                        onClick={() => {
                                            setReviewing(false);
                                            form.reset('current_password', 'confirmed');
                                        }}
                                    >
                                        {t('Edit')}
                                    </Button>
                                </div>
                                {attempted && (
                                    <p className="text-sm text-muted-foreground">
                                        {t(
                                            'If the result is unclear, retry this same transfer. Do not start a new request.',
                                        )}
                                    </p>
                                )}
                            </>
                        )}
                        {Object.entries(form.errors)
                            .filter(
                                ([key]) =>
                                    key !== 'current_password' &&
                                    (reviewing ||
                                        !['amount', 'recipient_account_id'].includes(key)),
                            )
                            .map(([key, message]) => (
                                <p role="alert" className="text-sm text-danger" key={key}>
                                    {errorMessage(message)}
                                </p>
                            ))}
                    </form>
                )}
            </div>
        </UserLayout>
    );
}
