// mobile/uni-app/src/screens/Withdraw.vue
<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import PageShell from '../components/PageShell.vue';
import FormField from '../components/FormField.vue';
import FormErrors from '../components/FormErrors.vue';
import WithdrawalAmounts from '../components/WithdrawalAmounts.vue';
import { t } from '../lib/i18n';
import { go } from '../lib/navigation';
import { useAction, requestId } from '../lib/client';
import {
    displayMoney,
    withdrawalPercentageFee,
    withdrawalRemainder,
    withdrawalReceiveAmount,
} from '../generated/exact-amount';
const props = defineProps<{
    page: {
        available: { amount: string; asset: string };
        network: string;
        feePercent: string | null;
    };
}>();
const form = reactive({ request_id: requestId(), address: '', amount: '' }),
    review = ref(false),
    reviewedFee = ref('0'),
    action = useAction();
const validAddress = computed(() => /^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(form.address.trim())),
    remaining = computed(() => withdrawalRemainder(form.amount, props.page.available.amount)),
    calculatedFee = computed(() =>
        withdrawalPercentageFee(form.amount, props.page.feePercent, 'USDT'),
    ),
    fee = computed(() => (review.value ? reviewedFee.value : (calculatedFee.value ?? '0'))),
    receive = computed(() => withdrawalReceiveAmount(form.amount, fee.value));
const canReview = computed(
    () =>
        calculatedFee.value !== null &&
        validAddress.value &&
        remaining.value !== null &&
        receive.value !== null,
);
const addressError = computed(() =>
    form.address && !validAddress.value ? t('Enter a valid TRON address.') : '',
);
const amountError = computed(() =>
    form.amount && remaining.value === null
        ? withdrawalRemainder(form.amount, '999999999999.99999999') === null
            ? t('Enter a positive amount with at most 2 decimal places.')
            : t('Your available balance is not enough for this withdrawal.')
        : form.amount && receive.value === null
          ? t('Withdrawal amount must be greater than the fee.')
          : '',
);
const uncertain = ref(false);
function changed() {
    if (uncertain.value) return;
    form.request_id = requestId();
}
function openReview() {
    if (canReview.value) {
        reviewedFee.value = calculatedFee.value!;
        review.value = true;
    }
}
async function submit() {
    if (!canReview.value) return;
    uncertain.value = true;
    const result = await action.submit('/wallet/withdrawals', {
        ...form,
        address: form.address.trim(),
        confirmed: true,
        expected_fee: reviewedFee.value,
    });
    if (result) {
        form.address = '';
        form.amount = '';
        uncertain.value = false;
    } else if (action.failureStatus.value === 422) {
        uncertain.value = false;
        review.value = false;
    }
}
</script>
<template>
    <PageShell :title="t('Withdraw')" back="/dashboard" active="assets"
        ><view class="withdraw"
            ><button class="history-link" @click="go('/wallet/withdrawals')">
                {{ t('Withdrawal history') }}</button
            ><FormErrors :errors="action.errors.value" /><template v-if="!review"
                ><view
                    ><text class="muted small">{{ t('Available') }}</text
                    ><text class="balance"
                        >{{ displayMoney(page.available.amount) }} {{ page.available.asset }}</text
                    ></view
                >
                <form @submit="openReview">
                    <FormField
                        v-model="form.address"
                        :label="t('Withdrawal address')"
                        :placeholder="t('T...')"
                        :error="addressError"
                        :disabled="action.pending.value || uncertain"
                        @update:model-value="changed"
                    /><FormField
                        v-model="form.amount"
                        :label="t('Amount')"
                        type="digit"
                        placeholder="0.00"
                        :error="amountError"
                        :disabled="action.pending.value || uncertain"
                        @update:model-value="changed"
                    /><view class="network"
                        ><text class="muted">{{ t('Network') }}</text
                        ><text>USDT ({{ page.network }})</text></view
                    ><text v-if="page.feePercent === null" class="error">{{
                        t('Not configured')
                    }}</text
                    ><WithdrawalAmounts :fee="fee" :receive="receive" /><button
                        class="primary submit"
                        form-type="submit"
                        :disabled="!canReview || action.pending.value"
                    >
                        {{ t('Withdraw') }}
                    </button>
                </form></template
            ><view v-else class="review"
                ><text class="muted small">{{ t('You are withdrawing') }}</text
                ><text class="balance">{{ displayMoney(form.amount) }} USDT</text
                ><view class="details"
                    ><view class="row"
                        ><text class="muted">{{ t('Network') }}</text
                        ><text>{{ page.network }}</text></view
                    ><view class="address"
                        ><text class="muted">{{ t('Address') }}</text
                        ><text>{{ form.address.trim() }}</text></view
                    ><view class="row"
                        ><text class="muted">{{ t('Available after') }}</text
                        ><text
                            >{{ remaining === null ? '—' : displayMoney(remaining) }} USDT</text
                        ></view
                    ></view
                ><WithdrawalAmounts :fee="fee" :receive="receive" /><text class="warning">{{
                    t(
                        'Check the address and amount carefully. Transfers sent to an incorrect address cannot be recovered. Your request will be reviewed before payment.',
                    )
                }}</text
                ><view class="buttons"
                    ><button
                        class="secondary"
                        :disabled="action.pending.value || uncertain"
                        @click="review = false"
                    >
                        {{ t('Back') }}</button
                    ><button
                        class="primary"
                        :disabled="!canReview || action.pending.value"
                        @click="submit"
                    >
                        {{ t(action.pending.value ? 'Submitting…' : 'Confirm withdrawal') }}
                    </button></view
                ></view
            ></view
        ></PageShell
    >
</template>
<style scoped>
.withdraw {
    display: flex;
    flex-direction: column;
    gap: 24px;
}
.history-link {
    background: none;
    font-size: 14px;
    font-weight: 600;
    padding: 0;
    margin: 0 0 0 auto;
    color: #68736e;
}
.small {
    font-size: 14px;
    display: block;
}
.balance {
    display: block;
    font-size: 30px;
    line-height: 36px;
    font-weight: 600;
    margin-top: 4px;
    overflow-wrap: anywhere;
}
.network,
.row {
    display: flex;
    justify-content: space-between;
    gap: 16px;
    font-size: 14px;
}
.network {
    padding: 12px 16px;
    border-radius: 8px;
    background: #f0f3f1;
    margin-bottom: 20px;
}
.withdraw form .submit {
    display: flex;
    width: max-content;
    margin: 20px auto 0;
    min-width: 100px;
}
.review {
    background: white;
    border: 1px solid #e2e7e4;
    border-radius: 16px;
    padding: 20px;
}
.details {
    margin: 24px 0 16px;
    border-block: 1px solid #e2e7e4;
}
.row,
.address {
    padding: 16px 0;
    border-bottom: 1px solid #e2e7e4;
}
.row:last-child {
    border: 0;
}
.address {
    font-size: 14px;
    display: flex;
    flex-direction: column;
    gap: 8px;
    overflow-wrap: anywhere;
}
.warning {
    display: block;
    font-size: 14px;
    line-height: 24px;
    color: #68736e;
    margin-top: 16px;
}
.buttons {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 12px;
    margin-top: 24px;
}
.buttons button {
    margin: 0;
}
.error {
    color: #b42318;
}
</style>

// resources/js/pages/user/Withdraw.tsx
import {
    displayMoney,
    withdrawalPercentageFee,
    withdrawalRemainder,
    withdrawalReceiveAmount,
} from '@/lib/exact-amount';
import { WithdrawalAmounts } from '@/components/user/WithdrawalAmounts';
import { t, useClientTranslation, errorMessage } from '@/i18n';
import { Head, Link, useForm } from '@inertiajs/react';
import { History } from 'lucide-react';
import { useState } from 'react';
import { MoneyDisplay } from '@/components/shared/MoneyDisplay';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { Button } from '@/components/ui/button';
import { FormField } from '@/components/ui/form-field';
import { Input } from '@/components/ui/input';
import { UserLayout } from '@/layouts/UserLayout';
import type { MoneyAmount } from '@/types/global';

export default function Withdraw({
    available,
    network,
    feePercent,
}: {
    available: { amount: MoneyAmount; asset: string };
    network: string;
    feePercent: string | null;
}) {
    useClientTranslation();
    const [reviewing, setReviewing] = useState(false);
    const [reviewedFee, setReviewedFee] = useState('0');
    // Unkeyed form: never remember the raw address in history or persistent storage.
    const withdrawal = useForm<{
        request_id: string;
        address: string;
        amount: string;
        confirmed: boolean;
        form?: string;
    }>({
        request_id: crypto.randomUUID(),
        address: '',
        amount: '',
        confirmed: false,
    });
    const normalizedAddress = withdrawal.data.address.trim();
    const validAddress = /^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(normalizedAddress);
    const availableAfter = withdrawalRemainder(withdrawal.data.amount, available.amount);
    const calculatedFee = withdrawalPercentageFee(withdrawal.data.amount, feePercent, 'USDT');
    const fee = reviewing ? reviewedFee : (calculatedFee ?? '0');
    const receiveAmount = withdrawalReceiveAmount(withdrawal.data.amount, fee);
    const canReview =
        calculatedFee !== null && validAddress && availableAfter !== null && receiveAmount !== null;
    const addressError =
        withdrawal.data.address && !validAddress ? t('Enter a valid TRON address.') : undefined;
    const amountError =
        withdrawal.data.amount && availableAfter === null
            ? withdrawalRemainder(withdrawal.data.amount, '999999999999.99999999') === null
                ? t('Enter a positive amount with at most 2 decimal places.')
                : t('Your available balance is not enough for this withdrawal.')
            : withdrawal.data.amount && receiveAmount === null
              ? t('Withdrawal amount must be greater than the fee.')
              : undefined;

    return (
        <UserLayout>
            <Head title={t('Withdraw USDT')} />
            <div className="space-y-6 sm:space-y-8">
                <div className="relative">
                    <UserPageHeader title={t('Withdraw')} backHref="/dashboard" />
                    <Link
                        href="/wallet/withdrawals"
                        className="absolute right-0 top-0 inline-flex min-h-11 items-center gap-1.5 text-sm font-semibold text-muted-foreground hover:text-foreground"
                    >
                        <History className="size-4" aria-hidden="true" />
                        {t('Withdrawal history')}
                    </Link>
                </div>
                {!reviewing ? (
                    <>
                        <div>
                            <p className="text-sm text-muted-foreground">{t('Available')}</p>
                            <p className="mt-1 text-3xl font-semibold">
                                <MoneyDisplay {...available} compact />
                            </p>
                        </div>
                        <form
                            className="space-y-5"
                            onSubmit={(event) => {
                                event.preventDefault();
                                if (canReview) {
                                    setReviewedFee(calculatedFee!);
                                    setReviewing(true);
                                }
                            }}
                        >
                            <FormField
                                id="withdrawal-address"
                                label={t('Withdrawal address')}
                                error={errorMessage(withdrawal.errors.address) || addressError}
                            >
                                <Input
                                    id="withdrawal-address"
                                    value={withdrawal.data.address}
                                    onChange={(event) =>
                                        withdrawal.setData('address', event.target.value)
                                    }
                                    placeholder={t('T...')}
                                    autoComplete="off"
                                    autoCapitalize="none"
                                    spellCheck={false}
                                    maxLength={100}
                                    required
                                />
                            </FormField>
                            <FormField
                                id="withdrawal-amount"
                                label={t('Amount')}
                                error={errorMessage(withdrawal.errors.amount) || amountError}
                            >
                                <Input
                                    id="withdrawal-amount"
                                    inputMode="decimal"
                                    value={withdrawal.data.amount}
                                    onChange={(event) =>
                                        withdrawal.setData('amount', event.target.value)
                                    }
                                    placeholder="0.00"
                                    maxLength={15}
                                    required
                                />
                            </FormField>
                            <div className="flex justify-between gap-4 rounded-lg bg-muted px-4 py-3 text-sm">
                                <span className="text-muted-foreground">{t('Network')}</span>
                                <span className="font-medium">USDT ({network})</span>
                            </div>
                            {feePercent === null && (
                                <p className="text-sm text-destructive">{t('Not configured')}</p>
                            )}
                            <WithdrawalAmounts fee={fee} receive={receiveAmount} />
                            {withdrawal.errors.form && (
                                <p role="alert" className="text-sm text-destructive">
                                    {errorMessage(withdrawal.errors.form)}
                                </p>
                            )}
                            <div className="flex justify-center">
                                <Button disabled={!canReview || withdrawal.processing}>
                                    {t('Withdraw')}
                                </Button>
                            </div>
                        </form>
                    </>
                ) : (
                    <section className="rounded-[var(--user-radius-lg)] border bg-surface p-5 sm:p-7">
                        <p className="text-sm text-muted-foreground">{t('You are withdrawing')}</p>
                        <p className="mt-2 text-3xl font-semibold">
                            {displayMoney(withdrawal.data.amount)} USDT
                        </p>
                        <dl className="mt-6 divide-y border-y text-sm">
                            <div className="flex justify-between gap-4 py-4">
                                <dt className="text-muted-foreground">{t('Network')}</dt>
                                <dd className="font-medium">{network}</dd>
                            </div>
                            <div className="flex flex-col gap-2 py-4">
                                <dt className="text-muted-foreground">{t('Address')}</dt>
                                <dd className="break-all font-medium">{normalizedAddress}</dd>
                            </div>
                            <div className="flex justify-between gap-4 py-4">
                                <dt className="text-muted-foreground">{t('Available after')}</dt>
                                <dd className="font-medium">
                                    {availableAfter === null ? '—' : displayMoney(availableAfter)}{' '}
                                    USDT
                                </dd>
                            </div>
                        </dl>
                        <div className="mt-4">
                            <WithdrawalAmounts fee={fee} receive={receiveAmount} />
                        </div>
                        <p className="mt-4 text-sm leading-6 text-muted-foreground">
                            {t(
                                'Check the address and amount carefully. Transfers sent to an incorrect address cannot be recovered. Your request will be reviewed before payment.',
                            )}
                        </p>
                        <div className="mt-6 flex flex-wrap justify-center gap-3">
                            <Button
                                type="button"
                                variant="secondary"
                                disabled={withdrawal.processing}
                                onClick={() => setReviewing(false)}
                            >
                                {t('Back')}
                            </Button>
                            <Button
                                disabled={!canReview || withdrawal.processing}
                                onClick={() => {
                                    withdrawal.transform((data) => ({
                                        ...data,
                                        address: normalizedAddress,
                                        confirmed: true,
                                        expected_fee: reviewedFee,
                                    }));
                                    withdrawal.post('/wallet/withdrawals', {
                                        onError: () => setReviewing(false),
                                        onSuccess: () =>
                                            withdrawal.reset('address', 'amount', 'confirmed'),
                                    });
                                }}
                            >
                                {withdrawal.processing ? t('Submitting…') : t('Confirm withdrawal')}
                            </Button>
                        </div>
                    </section>
                )}
            </div>
        </UserLayout>
    );
}
