// resources/js/pages/user/Login.tsx
import { t, useClientTranslation, errorMessage } from '@/i18n';
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { ArrowLeft, Eye, EyeOff } from 'lucide-react';
import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { userThemeStyle } from '@/lib/user-theme';
import type { SharedProps } from '@/types/global';
import { useLocaleSync } from '@/i18n/useLocaleSync';
import { LanguageSwitcher } from '@/components/user/LanguageSwitcher';
import { AuthBrand } from '@/components/user/AuthBrand';

export default function Login() {
    useClientTranslation();
    useLocaleSync();
    const form = useForm({ identifier: '', password: '' });
    const { tenant, flash } = usePage<SharedProps>().props;
    const [visible, setVisible] = useState(false);
    return (
        <div
            className="user-theme min-h-screen bg-background text-foreground"
            style={userThemeStyle(tenant?.branding.primaryColor)}
        >
            <Head title={t('Sign in')} />
            <main className="user-auth-shell user-auth-designed">
                <div className="user-auth-banner user-auth-banner-promotional">
                    <div className="flex w-full items-center justify-between">
                        <Link
                            href="/"
                            aria-label={t('Back to home')}
                            className="grid size-11 place-items-center"
                        >
                            <ArrowLeft className="size-7" />
                        </Link>
                        <LanguageSwitcher />
                    </div>
                    <AuthBrand tenant={tenant} promotional />
                </div>
                <div className="user-auth-content">
                    {flash.success && (
                        <p
                            role="status"
                            className="mb-4 rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-800"
                        >
                            {t(flash.success)}
                        </p>
                    )}
                    <h1 className="sr-only">{t('Sign in')}</h1>
                    <form
                        className="space-y-3"
                        onSubmit={(event) => {
                            event.preventDefault();
                            form.post('/login');
                        }}
                    >
                        <div className="user-auth-field">
                            <label className="sr-only" htmlFor="identifier">
                                {t('Email')}
                            </label>
                            <Input
                                id="identifier"
                                type="email"
                                autoComplete="username"
                                inputMode="email"
                                placeholder={t('Email')}
                                value={form.data.identifier}
                                onChange={(event) => form.setData('identifier', event.target.value)}
                                aria-invalid={Boolean(form.errors.identifier)}
                                required
                            />
                        </div>
                        {form.errors.identifier ? (
                            <p className="px-5 text-sm text-danger" role="alert">
                                {errorMessage(form.errors.identifier)}
                            </p>
                        ) : null}
                        <div className="user-auth-field">
                            <label className="sr-only" htmlFor="password">
                                {t('Password')}
                            </label>
                            <Input
                                id="password"
                                className="pr-20!"
                                type={visible ? 'text' : 'password'}
                                autoComplete="current-password"
                                placeholder={t('Password')}
                                value={form.data.password}
                                onChange={(event) => form.setData('password', event.target.value)}
                                aria-invalid={Boolean(form.errors.password)}
                                required
                            />
                            <button
                                type="button"
                                aria-label={visible ? t('Hide password') : t('Show password')}
                                onClick={() => setVisible(!visible)}
                            >
                                {visible ? (
                                    <Eye className="mx-auto size-6" />
                                ) : (
                                    <EyeOff className="mx-auto size-6" />
                                )}
                            </button>
                        </div>
                        {form.errors.password ? (
                            <p className="px-5 text-sm text-danger" role="alert">
                                {errorMessage(form.errors.password)}
                            </p>
                        ) : null}
                        <button
                            className="user-auth-submit"
                            aria-label={t('Sign in')}
                            type="submit"
                            disabled={
                                form.processing || !form.data.identifier || !form.data.password
                            }
                        >
                            {form.processing ? t('Signing in…') : t('Sign in')}
                        </button>
                    </form>
                    <Link
                        className="mt-5 block text-center text-sm text-muted-foreground underline underline-offset-4"
                        href="/forgot-password"
                    >
                        {t('Forgot password?')}
                    </Link>
                    <Link className="user-auth-register" href="/register">
                        {t('Register')}
                    </Link>
                </div>
            </main>
        </div>
    );
}

// mobile/uni-app/src/pages/login/index.vue
<script setup lang="ts">
import { useSensitiveScreen } from '../../lib/sensitive';
import { ref } from 'vue';
import { onShow } from '@dcloudio/uni-app';
import { bootstrap, login, session } from '../../lib/session';
import { t } from '../../lib/i18n';
import { go, home } from '../../lib/navigation';
import { explainError } from '../../lib/client';
import AuthLayout from '../../components/AuthLayout.vue';
import FormErrors from '../../components/FormErrors.vue';
import UiIcon from '../../components/UiIcon.vue';
const email = ref(''),
    password = ref(''),
    show = ref(false),
    pending = ref(false),
    errors = ref<Record<string, string>>({});
onShow(async () => {
    try {
        await bootstrap();
        if (session.value?.user)
            home(session.value.restricted ? '/account/restricted' : '/dashboard');
    } catch (e) {
        errors.value = explainError(e);
    }
});
useSensitiveScreen(() => {
    password.value = '';
    show.value = false;
});
async function submit() {
    if (pending.value || !email.value || !password.value) return;
    pending.value = true;
    errors.value = {};
    try {
        await login(email.value, password.value);
        password.value = '';
        home(session.value?.restricted ? '/account/restricted' : '/dashboard');
    } catch (e) {
        errors.value = explainError(e);
    } finally {
        pending.value = false;
    }
}
</script>
<template>
    <AuthLayout login
        ><FormErrors :errors="errors" />
        <form @submit="submit">
            <view class="login-fields"
                ><input
                    v-model="email"
                    class="login-input"
                    :placeholder="t('Email')"
                    :aria-label="t('Email address')"
                    :disabled="pending"
                    :maxlength="255"
                /><view class="password-field"
                    ><input
                        v-model="password"
                        class="login-input"
                        :password="!show"
                        :placeholder="t('Password')"
                        :aria-label="t('Password')"
                        :disabled="pending"
                        :maxlength="1024"
                        @confirm="submit" /><button
                        class="password-toggle"
                        :aria-label="t(show ? 'Hide password' : 'Show password')"
                        @click="show = !show"
                    >
                        <UiIcon :name="show ? 'eye' : 'eye-off'" :size="24" /></button></view
                ><button
                    class="auth-submit"
                    form-type="submit"
                    :disabled="pending || !email || !password"
                >
                    {{ t(pending ? 'Signing in…' : 'Sign in') }}
                </button></view
            >
        </form>
        <button class="forgot-link" @click="go('/forgot-password')">
            {{ t('Forgot password?') }}</button
        ><button class="register-button" @click="go('/register')">
            {{ t('Register') }}
        </button></AuthLayout
    >
</template>
<style scoped>
.login-fields {
    display: flex;
    flex-direction: column;
    gap: 12px;
}
.login-input {
    box-sizing: border-box;
    width: 100%;
    height: 54px;
    min-height: 54px;
    border: 1px solid #e2ded4;
    border-radius: 14px;
    padding: 0 18px;
    background: white;
    font-size: 16px;
    color: #25241f;
}
.password-field {
    position: relative;
}
.password-field .login-input {
    padding-right: 56px;
}
.password-toggle {
    position: absolute;
    right: 24px;
    top: 5px;
    width: 44px;
    height: 44px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: transparent;
    padding: 0;
}
.auth-submit {
    width: 100%;
    min-height: 54px;
    border-radius: 14px;
    background: #25241f;
    color: white;
    padding: 13px 16px;
    font-size: 17px;
    line-height: 1.5;
}
.auth-submit[disabled] {
    background: #e4e0d5;
    color: #787264;
}
.forgot-link {
    display: block;
    text-align: center;
    text-decoration: underline;
    text-underline-offset: 4px;
    font-size: 14px;
    color: #7d8780;
    background: transparent;
    margin: 20px auto 0;
    padding: 0;
    line-height: 20px;
}
.register-button {
    margin-top: 24px;
    width: 100%;
    min-height: 52px;
    border: 1px solid #d3cbbc;
    border-radius: 14px;
    background: transparent;
    font-size: 16px;
    color: #25241f;
    display: flex;
    justify-content: center;
    align-items: center;
}
</style>
