// resources/js/pages/user/AssetHistory.tsx
import { ArrowDownLeft, ArrowUpRight } from 'lucide-react';
import { Head, Link, router } from '@inertiajs/react';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { UserLayout } from '@/layouts/UserLayout';
import { t, dateTime, useClientTranslation } from '@/i18n';
import { exactAmount } from '@/lib/exact-amount';
export default function AssetHistory({
    selectedAsset,
    balances,
    rows,
}: {
    selectedAsset: string;
    balances: { asset: string; available: string }[];
    rows: {
        data: { asset: string; id: string; amount: string; time: string; kind: string }[];
        next_page_url: string | null;
        prev_page_url: string | null;
    };
}) {
    useClientTranslation();
    return (
        <UserLayout>
            <Head title={t('Funds activity')} />
            <div className="wealth-currency-header mb-5">
                <UserPageHeader
                    title={
                        selectedAsset === 'ALL'
                            ? t('Funds activity')
                            : t('{{asset}} funds account', { asset: selectedAsset })
                    }
                    backHref={selectedAsset === 'ALL' ? '/account' : '/dashboard'}
                    action={
                        <select
                            id="funds-asset"
                            aria-label={t('Select currency')}
                            value={selectedAsset}
                            className="max-w-28 rounded-lg border bg-surface px-2 py-2 text-base"
                            onChange={(e) => router.get('/funds', { asset: e.target.value })}
                        >
                            <option value="ALL">{t('All currencies')}</option>
                            {balances.map((b) => (
                                <option key={b.asset}>{b.asset}</option>
                            ))}
                        </select>
                    }
                />
            </div>
            <section className="mb-5 rounded-2xl bg-gradient-to-br from-emerald-100 to-lime-50 p-5 text-slate-900">
                <h2 className="mb-3 text-sm font-medium">{t('Available funds')}</h2>
                <dl className={selectedAsset === 'ALL' ? 'grid grid-cols-2 gap-4' : ''}>
                    {balances
                        .filter((b) => selectedAsset === 'ALL' || b.asset === selectedAsset)
                        .map((b) => (
                            <div key={b.asset}>
                                <dt className="text-xs text-slate-600">{b.asset}</dt>
                                <dd className="mt-1 break-all text-xl font-semibold tabular-nums">
                                    {exactAmount(b.available)}
                                </dd>
                            </div>
                        ))}
                </dl>
            </section>
            <h2 className="mb-3 font-semibold">{t('Funds movements')}</h2>
            {rows.data.length === 0 && (
                <p className="py-8 text-center text-muted-foreground">{t('No activity yet')}</p>
            )}
            <div className="divide-y rounded-2xl border border-black/5 bg-surface px-4 shadow-sm">
                {rows.data.map((r) => {
                    const debit = r.amount.startsWith('-');
                    const Icon = debit ? ArrowUpRight : ArrowDownLeft;
                    const value = exactAmount(r.amount);
                    return (
                        <div key={r.id} className="flex items-start gap-3 py-4 text-sm">
                            <span
                                className={`mt-1 flex size-9 shrink-0 items-center justify-center rounded-full ${debit ? 'bg-muted text-slate-600' : 'bg-emerald-50 text-emerald-700'}`}
                            >
                                <Icon className="size-4" aria-hidden="true" />
                            </span>
                            <div className="min-w-0 flex-1">
                                <div className="flex flex-wrap items-start justify-between gap-x-3 gap-y-1">
                                    <p className="font-medium">{t(r.kind)}</p>
                                    <p
                                        className={`min-w-0 break-all font-semibold tabular-nums ${debit ? 'text-foreground' : 'text-emerald-700'}`}
                                    >
                                        {debit || value === '0' ? value : `+${value}`}{' '}
                                        <span className="whitespace-nowrap">{r.asset}</span>
                                    </p>
                                </div>
                                <div className="mt-1 flex flex-wrap justify-between gap-x-3 gap-y-1 text-xs text-muted-foreground">
                                    <p>{dateTime(r.time)}</p>
                                    <p>{t(debit ? 'Wallet debit' : 'Wallet credit')}</p>
                                </div>
                            </div>
                        </div>
                    );
                })}
            </div>
            <div className="mt-5 flex justify-between">
                {rows.prev_page_url && (
                    <Link className="min-h-11 py-3" href={rows.prev_page_url}>
                        {t('Previous')}
                    </Link>
                )}
                {rows.next_page_url && (
                    <Link className="min-h-11 py-3" href={rows.next_page_url}>
                        {t('Next')}
                    </Link>
                )}
            </div>
        </UserLayout>
    );
}

// mobile/uni-app/src/screens/AssetHistory.vue
<script setup lang="ts">
import { computed } from 'vue';
import PageShell from '../components/PageShell.vue';
import SelectField from '../components/SelectField.vue';
import ActivityList from '../components/ActivityList.vue';
import { t } from '../lib/i18n';
import { go } from '../lib/navigation';
import { exactAmount } from '../generated/exact-amount';
const props = defineProps<{
    page: {
        selectedAsset: string;
        balances: { asset: string; available: string }[];
        rows: {
            data: { asset: string; id: string; amount: string; time: string; kind: string }[];
            next_page_url: string | null;
            prev_page_url: string | null;
        };
    };
}>();
const title = computed(() =>
    props.page.selectedAsset === 'ALL'
        ? t('Funds activity')
        : t('{{asset}} funds account', { asset: props.page.selectedAsset }),
);
</script>
<template>
    <PageShell
        :title="title"
        :back="page.selectedAsset === 'ALL' ? '/account' : '/dashboard'"
        active="assets"
        ><SelectField
            :model-value="page.selectedAsset"
            :label="t('Select currency')"
            :options="[
                { value: 'ALL', label: t('All currencies') },
                ...page.balances.map((b) => ({ value: b.asset, label: b.asset })),
            ]"
            @update:model-value="(value) => go('/funds?asset=' + value, true)"
        /><view class="funds-summary"
            ><text class="summary-label">{{ t('Available funds') }}</text
            ><view class="balances" :class="{ all: page.selectedAsset === 'ALL' }"
                ><view
                    v-for="balance in page.balances.filter(
                        (b) => page.selectedAsset === 'ALL' || b.asset === page.selectedAsset,
                    )"
                    :key="balance.asset"
                    ><text class="small">{{ balance.asset }}</text
                    ><text class="amount">{{ exactAmount(balance.available) }}</text></view
                ></view
            ></view
        ><text class="section-title">{{ t('Funds movements') }}</text
        ><view class="history-panel"><ActivityList :items="page.rows.data" /></view
        ><view class="pagination"
            ><button
                v-if="page.rows.prev_page_url"
                class="text-button"
                @click="go(page.rows.prev_page_url, true)"
            >
                {{ t('Previous') }}</button
            ><view v-else /><button
                v-if="page.rows.next_page_url"
                class="text-button"
                @click="go(page.rows.next_page_url, true)"
            >
                {{ t('Next') }}
            </button></view
        ></PageShell
    >
</template>
<style scoped>
.funds-summary {
    padding: 20px;
    border-radius: 16px;
    background: linear-gradient(135deg, #d1fae5, #f7fee7);
    margin-bottom: 20px;
    color: #0f172a;
}
.summary-label {
    display: block;
    margin-bottom: 12px;
    font-size: 14px;
    font-weight: 500;
}
.balances.all {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
}
.small {
    display: block;
    font-size: 12px;
    color: #475569;
}
.amount {
    display: block;
    margin-top: 4px;
    font-size: 20px;
    font-weight: 600;
    line-height: 28px;
    overflow-wrap: anywhere;
}
.section-title {
    display: block;
    font-size: 16px;
    font-weight: 600;
    margin-bottom: 12px;
}
.history-panel {
    background: white;
    border: 1px solid #0000000d;
    border-radius: 16px;
    padding: 0 16px;
    box-shadow: 0 1px 2px #0000000d;
}
.pagination {
    display: flex;
    justify-content: space-between;
    margin-top: 20px;
}
.text-button {
    min-height: 44px;
    padding: 12px 0;
    background: none;
    font-size: 14px;
    line-height: 20px;
}
</style>
