// resources/js/pages/user/PromotionRewardDetails.tsx
import { promotionLevel } from '@/lib/paid-promotion';
import { Head, Link } from '@inertiajs/react';
import { UserLayout } from '@/layouts/UserLayout';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { t, dateTime, useClientTranslation } from '@/i18n';
import { exactAmount } from '@/lib/exact-amount';
export default function PromotionRewardDetails({
    details: d,
}: {
    details: {
        kind: string;
        rank: number;
        page: number;
        hasMore: boolean;
        items: {
            id: string;
            direct: boolean;
            rate: string;
            amount: string;
            sourceAmount: string;
            occurredAt: string;
            accountId: string;
        }[];
    };
}) {
    useClientTranslation();
    const url = (page: number) => `/promotion/rewards?kind=${d.kind}&rank=${d.rank}&page=${page}`;
    return (
        <UserLayout>
            <Head title={t('Commission details')} />
            <UserPageHeader
                title={t(
                    d.kind === 'ANNUAL'
                        ? 'Annual fee commission details'
                        : 'Activation commission details',
                )}
                backHref="/promotion/invitations"
            />
            <p className="mb-4">{promotionLevel(d.rank)}</p>
            {d.items.map((r) => (
                <div key={r.id} className="space-y-2 border-b py-4 text-sm">
                    <div className="flex justify-between gap-3">
                        <span>
                            {r.accountId} · {t(r.direct ? 'Direct' : 'Indirect')}
                        </span>
                        <strong>{exactAmount(r.amount)} USDT</strong>
                    </div>
                    <p>
                        {t('Source amount')}: {exactAmount(r.sourceAmount)} {'USDT'} ·{' '}
                        {t(d.kind === 'ANNUAL' ? 'Reward rate' : 'Reward difference')}:{' '}
                        {exactAmount(r.rate)} {d.kind === 'ANNUAL' ? '%' : 'USDT'}
                    </p>
                    <p className="text-xs text-muted-foreground">{dateTime(r.occurredAt)}</p>
                </div>
            ))}
            {!d.items.length && <p>{t('No activity yet')}</p>}
            <div className="mt-5 flex justify-between">
                {d.page > 1 && <Link href={url(d.page - 1)}>{t('Previous')}</Link>}
                {d.hasMore && <Link href={url(d.page + 1)}>{t('Next')}</Link>}
            </div>
        </UserLayout>
    );
}

// mobile/uni-app/src/screens/PromotionRewardDetails.vue
<script setup lang="ts">
import PageShell from '../components/PageShell.vue';
import ReportPagination from '../components/ReportPagination.vue';
import { t, dateTime } from '../lib/i18n';
import { go } from '../lib/navigation';
import { promotionLevel } from '../lib/promotion';
import { exactAmount } from '../generated/exact-amount';
const props = defineProps<{
    page: {
        details: {
            kind: string;
            rank: number;
            page: number;
            hasMore: boolean;
            items: {
                id: string;
                direct: boolean;
                rate: string;
                amount: string;
                sourceAmount: string;
                occurredAt: string;
                accountId: string;
            }[];
        };
    };
}>();
function paginate(page: number) {
    go(
        '/promotion/rewards?kind=' +
            props.page.details.kind +
            '&rank=' +
            props.page.details.rank +
            '&page=' +
            page,
        true,
    );
}
</script>
<template>
    <PageShell
        :title="
            t(
                page.details.kind === 'ANNUAL'
                    ? 'Annual fee commission details'
                    : 'Activation commission details',
            )
        "
        back="/promotion/invitations"
        active="account"
        ><text class="rank">{{ promotionLevel(page.details.rank) }}</text
        ><view v-for="row in page.details.items" :key="row.id" class="reward-row"
            ><view class="between"
                ><text>{{ row.accountId }} · {{ t(row.direct ? 'Direct' : 'Indirect') }}</text
                ><text class="strong">{{ exactAmount(row.amount) }} USDT</text></view
            ><text
                >{{ t('Source amount') }}: {{ exactAmount(row.sourceAmount) }} USDT ·
                {{ t(page.details.kind === 'ANNUAL' ? 'Reward rate' : 'Reward difference') }}:
                {{ exactAmount(row.rate) }}
                {{ page.details.kind === 'ANNUAL' ? '%' : 'USDT' }}</text
            ><text class="date muted">{{ dateTime(row.occurredAt) }}</text></view
        ><text v-if="!page.details.items.length">{{ t('No activity yet') }}</text
        ><ReportPagination
            :page="page.details.page"
            :has-more="page.details.hasMore"
            @change="paginate"
    /></PageShell>
</template>
<style scoped>
.rank {
    display: block;
    margin-bottom: 16px;
}
.reward-row {
    display: flex;
    flex-direction: column;
    gap: 8px;
    border-bottom: 1px solid #e1e7dd;
    padding: 16px 0;
    font-size: 14px;
    line-height: 22px;
}
.between {
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 12px;
}
.strong {
    font-weight: 600;
}
.date {
    font-size: 12px;
}
</style>
