// resources/js/pages/user/PromotionHub.tsx
import { AcademyPosters } from '@/components/user/AcademyPosters';
import { InvitationPoster } from '@/components/user/InvitationPoster';
import { Head, Link, router, usePage } from '@inertiajs/react';
import { useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, Users, BookOpen, Copy, Share2, Check } from 'lucide-react';
import { UserLayout } from '@/layouts/UserLayout';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { Button } from '@/components/ui/button';
import { AnnualRebateProgress } from '@/components/user/AnnualRebateProgress';
import type { PaidPromotionData } from '@/components/user/PaidPromotionSummary';
import { promotionLevel, promotionUnits } from '@/lib/paid-promotion';
import { t, dateTime, errorMessage, useClientTranslation } from '@/i18n';
import type { SharedProps } from '@/types/global';
import '../../../css/promotion.css';

type Benefits = Pick<
    PaidPromotionData,
    | 'manualLevel'
    | 'levels'
    | 'rank'
    | 'percent'
    | 'reward'
    | 'membershipStatus'
    | 'previousCycle'
    | 'cycle'
    | 'pending'
    | 'progress'
    | 'upgradeEligibility'
> & { hasClaims: boolean };
type Home = {
    posterBackground: string | null;
    paid: Benefits;
    invitationCode: string;
    canPurchase: boolean;
};

// Whole-unit presentation only. Non-integer configured fees are marked approximate;
// the payment review continues to show the full server quote precision.
function annualFeeLabel(amount: string): string {
    const units = promotionUnits(amount);
    const rounded = ((units + 50000000n) / 100000000n).toString();
    return `${units % 100000000n === 0n ? '' : '≈ '}${rounded.replace(/\B(?=(\d{3})+(?!\d))/g, ',')} USDT`;
}

export default function PromotionHub({
    home,
    section = 'overview',
}: {
    home: Home;
    section?: 'overview' | 'rules';
}) {
    useClientTranslation();
    const p = home.paid;
    const ranks = [...new Set([0, p.rank, ...p.levels.map((level) => level.rank)])].sort(
        (a, b) => a - b,
    );
    const { errors } = usePage<SharedProps>().props;
    const track = useRef<HTMLDivElement>(null);
    const shareDock = useRef<HTMLDivElement>(null);
    const [shareDockHeight, setShareDockHeight] = useState(64);
    const [selected, setSelected] = useState(p.rank);
    const [busy, setBusy] = useState(false);
    const submitting = useRef(false);
    const intents = useRef(new Map<string, string>());
    const [shareState, setShareState] = useState<'idle' | 'copied' | 'shared' | 'failed'>('idle');
    const [sharing, setSharing] = useState(false);
    const link = `${window.location.origin}/register?invite=${encodeURIComponent(home.invitationCode)}`;
    const title = section === 'rules' ? 'U Card Academy' : 'Promotion center';
    const select = (rank: number, behavior: ScrollBehavior = 'smooth') => {
        const node = track.current;
        const card = node?.querySelector<HTMLElement>(`[data-rank="${rank}"]`);
        if (!node || !card) return;
        node.scrollTo({
            left: card.offsetLeft - (node.clientWidth - card.offsetWidth) / 2,
            behavior,
        });
        setSelected(rank);
    };
    useEffect(() => {
        select(p.rank, 'instant');
    }, [p.rank, section]);
    useEffect(() => {
        const node = shareDock.current;
        if (!node) return;
        const measure = () => setShareDockHeight(node.getBoundingClientRect().height);
        measure();
        const observer = new ResizeObserver(measure);
        observer.observe(node);
        return () => observer.disconnect();
    }, [section]);
    const quote = (id: string) => {
        if (submitting.current || p.manualLevel || p.pending || !home.canPurchase) return;
        const requestId = intents.current.get(id) ?? crypto.randomUUID();
        intents.current.set(id, requestId);
        submitting.current = true;
        setBusy(true);
        router.post(
            '/promotion/quotes',
            { level_id: id, request_id: requestId },
            {
                preserveScroll: true,
                onError: () => intents.current.delete(id),
                onSuccess: () => intents.current.delete(id),
                onFinish: () => {
                    submitting.current = false;
                    setBusy(false);
                },
            },
        );
    };
    const copy = async () => {
        setShareState('idle');
        try {
            await navigator.clipboard.writeText(link);
            setShareState('copied');
        } catch {
            setShareState('failed');
        }
    };
    const share = async () => {
        setSharing(true);
        setShareState('idle');
        try {
            if (navigator.share) {
                await navigator.share({ title: t('Invitation to join'), url: link });
                setShareState('shared');
            } else await copy();
        } catch (error) {
            if (!(error instanceof Error && error.name === 'AbortError')) await copy();
        } finally {
            setSharing(false);
        }
    };
    return (
        <UserLayout>
            <Head title={t(title)} />
            <div
                className={`promotion-page promotion-hub${section === 'rules' ? ' academy-page' : ''}`}
                style={section === 'overview' ? { paddingBottom: shareDockHeight + 16 } : undefined}
            >
                <UserPageHeader title={t(title)} backHref="/account" />
                {section === 'rules' ? (
                    <AcademyPosters />
                ) : (
                    <>
                        <div ref={shareDock} className="promotion-share-dock">
                            <div className="grid grid-cols-2 gap-3">
                                <InvitationPoster
                                    link={link}
                                    code={home.invitationCode}
                                    background={home.posterBackground}
                                />
                                <Button
                                    className="w-full rounded-full"
                                    onClick={() => void share()}
                                    disabled={sharing}
                                >
                                    <Share2 className="size-4" />
                                    {t('Share invitation link')}
                                </Button>
                            </div>
                            <p
                                role="status"
                                className="flex items-center gap-2 text-xs text-muted-foreground"
                            >
                                {shareState === 'copied' && (
                                    <>
                                        <Check className="size-4" />
                                        {t('Copied')}
                                    </>
                                )}
                                {shareState === 'shared' && t('Invitation link shared.')}
                                {shareState === 'failed' &&
                                    t('Could not copy. Copy the link below manually.')}
                            </p>
                            {shareState === 'failed' && (
                                <input
                                    readOnly
                                    value={link}
                                    aria-label={t('Invitation link')}
                                    onFocus={(e) => e.target.select()}
                                    className="w-full min-w-0 rounded-xl border p-3 text-xs"
                                />
                            )}
                        </div>
                        {Object.entries(errors ?? {}).map(([key, message]) => (
                            <p key={key} role="alert" className="text-sm text-destructive">
                                {errorMessage(message)}
                            </p>
                        ))}
                        <section aria-label={t('Promotion level benefits')}>
                            <div
                                ref={track}
                                className="promotion-level-track"
                                tabIndex={0}
                                aria-label={t('Swipe to compare levels')}
                                onKeyDown={(e) => {
                                    if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') {
                                        e.preventDefault();
                                        select(
                                            ranks[
                                                Math.max(
                                                    0,
                                                    Math.min(
                                                        ranks.length - 1,
                                                        ranks.indexOf(selected) +
                                                            (e.key === 'ArrowRight' ? 1 : -1),
                                                    ),
                                                )
                                            ]!,
                                        );
                                    }
                                }}
                                onScroll={() => {
                                    const node = track.current;
                                    if (!node) return;
                                    const center = node.scrollLeft + node.clientWidth / 2;
                                    const cards = Array.from(
                                        node.querySelectorAll<HTMLElement>('[data-rank]'),
                                    );
                                    const closest = cards.reduce<HTMLElement | null>(
                                        (best, card) =>
                                            !best ||
                                            Math.abs(
                                                card.offsetLeft + card.offsetWidth / 2 - center,
                                            ) <
                                                Math.abs(
                                                    best.offsetLeft + best.offsetWidth / 2 - center,
                                                )
                                                ? card
                                                : best,
                                        null,
                                    );
                                    if (closest) setSelected(Number(closest.dataset.rank));
                                }}
                            >
                                {ranks.map((rank) => {
                                    const offer = p.levels.find((l) => l.rank === rank);
                                    const current = p.rank === rank;
                                    const fee =
                                        rank === 0
                                            ? '0'
                                            : current && p.cycle
                                              ? p.cycle.tariff
                                              : offer?.fee;
                                    const percent = current ? p.percent : offer?.percent;
                                    const reward =
                                        rank === 0 ? '20' : current ? p.reward : offer?.reward;
                                    const canUpgrade =
                                        !p.manualLevel &&
                                        !!offer &&
                                        rank > p.rank &&
                                        (!p.cycle ||
                                            promotionUnits(offer.fee) >
                                                promotionUnits(p.cycle.tariff));
                                    return (
                                        <article
                                            key={rank}
                                            data-rank={rank}
                                            className={`promotion-level-card ${current ? 'is-current' : ''}`}
                                            aria-label={promotionLevel(rank)}
                                        >
                                            <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-2">
                                                <div className="min-w-0">
                                                    <h2 className="break-words">
                                                        {promotionLevel(rank)}
                                                    </h2>
                                                    {current && (
                                                        <span className="mt-2 inline-block rounded-full border border-current/20 px-2 py-0.5 text-xs">
                                                            {t('Current level')}
                                                        </span>
                                                    )}
                                                </div>
                                                <p className="promotion-level-price whitespace-nowrap text-right text-sm font-semibold leading-6 tabular-nums">
                                                    {rank === 0 || (current && p.manualLevel) ? (
                                                        t('No annual fee')
                                                    ) : fee !== undefined ? (
                                                        <>
                                                            {annualFeeLabel(fee)}{' '}
                                                            <span className="text-xs font-normal opacity-75">
                                                                {t('per year')}
                                                            </span>
                                                        </>
                                                    ) : (
                                                        t('Not configured')
                                                    )}
                                                </p>
                                            </div>
                                            <div className="mt-3 grid grid-cols-2 gap-3 border-t border-current/15 pt-3">
                                                <div>
                                                    <p className="text-xs leading-5 opacity-75">
                                                        {t('Direct activation standard')}
                                                    </p>
                                                    <p className="mt-1 break-words text-lg font-semibold">
                                                        {reward ?? '—'}{' '}
                                                        <span className="text-xs font-normal">
                                                            USDT
                                                        </span>
                                                    </p>
                                                </div>
                                                <div>
                                                    <p className="text-xs leading-5 opacity-75">
                                                        {t('Annual fee reward rate')}
                                                    </p>
                                                    <p className="mt-1 text-lg font-semibold">
                                                        {rank === 0
                                                            ? '—'
                                                            : percent === undefined
                                                              ? '—'
                                                              : `${percent}%`}
                                                    </p>
                                                </div>
                                            </div>
                                            {current && p.cycle && p.progress && (
                                                <div className="mt-3">
                                                    <AnnualRebateProgress progress={p.progress} />
                                                </div>
                                            )}
                                            <div className="mt-auto pt-3">
                                                {current ? (
                                                    <p className="text-xs leading-5">
                                                        {p.cycle
                                                            ? t('Valid until {{time}}', {
                                                                  time: dateTime(p.cycle.endsAt),
                                                              })
                                                            : t('Your current benefits')}
                                                    </p>
                                                ) : rank < p.rank ? (
                                                    <p className="text-xs">
                                                        {t('Downgrades are not available.')}
                                                    </p>
                                                ) : !offer?.enabled || !canUpgrade ? (
                                                    <p className="text-xs">
                                                        {t('Currently unavailable for purchase')}
                                                    </p>
                                                ) : (
                                                    <Button
                                                        className="w-full"
                                                        disabled={
                                                            busy ||
                                                            p.pending ||
                                                            !home.canPurchase ||
                                                            !offer.selectable
                                                        }
                                                        onClick={() => quote(offer.id)}
                                                    >
                                                        {t(
                                                            p.membershipStatus === 'EXPIRED'
                                                                ? 'Renew or reactivate'
                                                                : p.rank > 0
                                                                  ? 'Upgrade to this level'
                                                                  : 'Apply for this level',
                                                        )}
                                                    </Button>
                                                )}
                                            </div>
                                            {offer?.unavailableReason && !current && (
                                                <p className="px-4 pb-4 text-xs text-muted-foreground">
                                                    {t(offer.unavailableReason)}
                                                </p>
                                            )}
                                        </article>
                                    );
                                })}
                            </div>
                            <div className="mt-3 flex items-center justify-between gap-2">
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    disabled={selected === 0}
                                    aria-label={t('Previous level')}
                                    onClick={() =>
                                        select(ranks[Math.max(0, ranks.indexOf(selected) - 1)]!)
                                    }
                                >
                                    <ChevronLeft className="size-4" />
                                </Button>
                                <div
                                    className="flex min-w-0 flex-wrap justify-center gap-0"
                                    aria-label={t('Choose promotion level')}
                                >
                                    {ranks.map((rank) => (
                                        <button
                                            key={rank}
                                            className="grid min-h-11 w-6 place-items-center"
                                            aria-label={promotionLevel(rank)}
                                            aria-current={selected === rank ? 'true' : undefined}
                                            onClick={() => select(rank)}
                                        >
                                            <span
                                                className={`h-1.5 rounded-full ${selected === rank ? 'w-5 bg-primary' : 'w-1.5 bg-primary/20'}`}
                                            />
                                        </button>
                                    ))}
                                </div>
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    disabled={selected === ranks[ranks.length - 1]}
                                    aria-label={t('Next level')}
                                    onClick={() =>
                                        select(
                                            ranks[
                                                Math.min(
                                                    ranks.length - 1,
                                                    ranks.indexOf(selected) + 1,
                                                )
                                            ]!,
                                        )
                                    }
                                >
                                    <ChevronRight className="size-4" />
                                </Button>
                            </div>
                            <p className="text-center text-xs text-muted-foreground">
                                {t('Swipe to compare levels')}
                            </p>
                            {p.manualLevel && (
                                <p className="mt-3 text-sm text-muted-foreground">
                                    {t(
                                        'Your promotion level is managed by the platform. No annual payment is needed. Contact support to change it.',
                                    )}
                                </p>
                            )}
                            {!home.canPurchase && (
                                <p className="mt-3 text-xs leading-5 text-muted-foreground">
                                    {t(
                                        'An active verified USDT wallet is required to purchase a level.',
                                    )}
                                </p>
                            )}
                            {p.pending && (
                                <p role="status" className="mt-3 rounded-xl bg-muted p-3 text-sm">
                                    {t('Annual fee return is processing. Try upgrading shortly.')}{' '}
                                    <Link
                                        href="/promotion/membership#rebate-history"
                                        className="underline"
                                    >
                                        {t('Fee rebate history')}
                                    </Link>
                                </p>
                            )}
                        </section>
                        <nav className="grid grid-cols-2 gap-3" aria-label={t('Promotion details')}>
                            {[
                                {
                                    href: '/promotion/invitations',
                                    label: 'Invitation data',
                                    Icon: Users,
                                },
                                {
                                    href: '/promotion/rules',
                                    label: 'U Card Academy',
                                    Icon: BookOpen,
                                },
                            ].map(({ href, label, Icon }) => (
                                <Link
                                    key={href}
                                    href={href}
                                    className="flex min-w-0 items-center gap-3 rounded-2xl border bg-surface p-4 text-sm font-medium"
                                >
                                    <Icon className="size-5 shrink-0 text-primary" />
                                    <span className="flex-1 break-words">{t(label)}</span>
                                    <ChevronRight className="size-4 shrink-0" />
                                </Link>
                            ))}
                        </nav>
                        <section>
                            <h2>{t('Invitation steps')}</h2>
                            <ol className="promotion-invite-steps">
                                {[
                                    'Share your invitation link with a friend.',
                                    'Your friend registers through the link and joins your team.',
                                    'After a successful security deposit or promotion annual fee payment, rewards follow your valid level and the commission rules.',
                                ].map((step, i) => (
                                    <li key={step}>
                                        <span aria-hidden="true">{i + 1}</span>
                                        <p>{t(step)}</p>
                                    </li>
                                ))}
                            </ol>
                        </section>
                        <section className="space-y-3 pb-4">
                            <div className="flex items-center justify-between gap-3">
                                <div>
                                    <p className="text-xs text-muted-foreground">
                                        {t('Invitation code')}
                                    </p>
                                    <p className="mt-1 text-xl font-semibold tracking-widest">
                                        {home.invitationCode}
                                    </p>
                                </div>
                                <Button variant="ghost" onClick={() => void copy()}>
                                    <Copy className="size-4" />
                                    {t('Copy invitation link')}
                                </Button>
                            </div>
                        </section>
                    </>
                )}
            </div>
        </UserLayout>
    );
}

// mobile/uni-app/src/screens/PromotionHub.vue
<script setup lang="ts">
import { computed, ref, nextTick, watch, onMounted, getCurrentInstance } from 'vue';
import { onResize } from '@dcloudio/uni-app';
import PageShell from '../components/PageShell.vue';
import UiIcon from '../components/UiIcon.vue';
import FormErrors from '../components/FormErrors.vue';
import AnnualRebateProgress from '../components/AnnualRebateProgress.vue';
import InvitationPoster from '../components/InvitationPoster.vue';
import { invitationUrl } from '../lib/origin';
import { useAction, requestId } from '../lib/client';
import { t, dateTime, locale } from '../lib/i18n';
import { go } from '../lib/navigation';
import { promotionLevel, promotionUnits } from '../lib/promotion';
import type { PaidPromotionData } from '../lib/promotion-types';
type Benefits = Pick<
    PaidPromotionData,
    | 'manualLevel'
    | 'levels'
    | 'rank'
    | 'percent'
    | 'reward'
    | 'membershipStatus'
    | 'previousCycle'
    | 'cycle'
    | 'pending'
    | 'progress'
    | 'upgradeEligibility'
> & { hasClaims: boolean };
const props = defineProps<{
    page: {
        home: {
            posterBackground: string | null;
            paid: Benefits;
            invitationCode: string;
            canPurchase: boolean;
        };
    };
}>();
const poster = ref<InstanceType<typeof InvitationPoster> | null>(null);
const home = computed(() => props.page.home),
    p = computed(() => home.value.paid),
    ranks = computed(() =>
        [...new Set([0, p.value.rank, ...p.value.levels.map((l) => l.rank)])].sort((a, b) => a - b),
    ),
    selected = ref(ranks.value.indexOf(p.value.rank)),
    action = useAction(),
    intents = new Map<string, string>(),
    shareState = ref(''),
    sharing = ref(false);
const link = computed(() => invitationUrl(home.value.invitationCode));
const offers = computed(() =>
    ranks.value.map((rank) => {
        const offer = p.value.levels.find((l) => l.rank === rank),
            current = rank === p.value.rank;
        const fee = rank === 0 ? '0' : current && p.value.cycle ? p.value.cycle.tariff : offer?.fee;
        return {
            rank,
            offer,
            current,
            fee,
            percent: current ? p.value.percent : offer?.percent,
            reward: rank === 0 ? '20' : current ? p.value.reward : offer?.reward,
            canUpgrade:
                !p.value.manualLevel &&
                !!offer &&
                rank > p.value.rank &&
                (!p.value.cycle ||
                    promotionUnits(offer.fee) > promotionUnits(p.value.cycle.tariff)),
        };
    }),
);
function feeLabel(amount: string) {
    const units = promotionUnits(amount),
        rounded = ((units + 50000000n) / 100000000n).toString();
    return (
        (units % 100000000n === 0n ? '' : '≈ ') +
        rounded.replace(/\B(?=(\d{3})+(?!\d))/g, ',') +
        ' USDT'
    );
}
const instance = getCurrentInstance();
const levelHeight = ref(210);
function measureLevels() {
    levelHeight.value = 0;
    nextTick(() =>
        uni
            .createSelectorQuery()
            .in(instance?.proxy)
            .selectAll('.level-card')
            .boundingClientRect((rects: any) => {
                if (Array.isArray(rects) && rects.length)
                    levelHeight.value = Math.ceil(Math.max(...rects.map((r) => r.height))) + 8;
            })
            .exec(),
    );
}
onMounted(measureLevels);
watch([offers, locale], measureLevels);
onResize(measureLevels);
const expiry = computed(() =>
    p.value.cycle
        ? t('Valid until {{time}}', { time: dateTime(p.value.cycle.endsAt) })
        : t('Your current benefits'),
);
async function quote(id: string) {
    if (action.pending.value || p.value.manualLevel || p.value.pending || !home.value.canPurchase)
        return;
    const key = intents.get(id) ?? requestId();
    intents.set(id, key);
    const result = await action.submit('/promotion/quotes', { level_id: id, request_id: key });
    if (result) intents.delete(id);
}
async function copy() {
    try {
        await new Promise<void>((resolve, reject) =>
            uni.setClipboardData({
                data: link.value,
                showToast: false,
                success: () => resolve(),
                fail: reject,
            }),
        );
        shareState.value = 'copied';
    } catch {
        shareState.value = 'failed';
    }
}
async function share() {
    sharing.value = true;
    shareState.value = '';
    try {
        // #ifdef H5
        if (navigator.share) {
            await navigator.share({ title: t('Invitation to join'), url: link.value });
            shareState.value = 'shared';
            return;
        }
        // #endif
        // #ifdef APP-PLUS
        await new Promise<void>((resolve, reject) =>
            uni.shareWithSystem({
                type: 'text',
                summary: t('Invitation to join') + ' ' + link.value,
                href: link.value,
                success: () => resolve(),
                fail: reject,
            }),
        );
        shareState.value = 'shared';
        return;
        // #endif
        await copy();
    } catch (e) {
        if (!(e instanceof Error && e.name === 'AbortError')) await copy();
    } finally {
        sharing.value = false;
    }
}
</script>
<template>
    <PageShell :title="t('Promotion center')" back="/account" active="account" white
        ><view class="hub"
            ><FormErrors :errors="action.errors.value" /><view
                ><swiper
                    class="level-swiper"
                    :style="{ height: Math.max(210, levelHeight) + 'px' }"
                    :current="selected"
                    :previous-margin="'24px'"
                    :next-margin="'24px'"
                    @change="selected = $event.detail.current"
                    ><swiper-item v-for="offer in offers" :key="offer.rank"
                        ><view
                            class="level-card"
                            :class="{ current: offer.current }"
                            :style="{ minHeight: Math.max(0, levelHeight - 8) + 'px' }"
                            ><view class="card-heading"
                                ><view
                                    ><text class="level-name">{{ promotionLevel(offer.rank) }}</text
                                    ><text v-if="offer.current" class="current-label">{{
                                        t('Current level')
                                    }}</text></view
                                ><text class="price"
                                    >{{
                                        offer.rank === 0 || (offer.current && p.manualLevel)
                                            ? t('No annual fee')
                                            : offer.fee === undefined
                                              ? t('Not configured')
                                              : feeLabel(offer.fee)
                                    }}
                                    <text
                                        v-if="
                                            offer.rank > 0 &&
                                            !(offer.current && p.manualLevel) &&
                                            offer.fee !== undefined
                                        "
                                        class="small"
                                        >{{ t('per year') }}</text
                                    ></text
                                ></view
                            ><view class="benefits"
                                ><view
                                    ><text class="small">{{ t('Direct activation standard') }}</text
                                    ><text class="benefit"
                                        >{{ offer.reward ?? '—' }}
                                        <text class="small">USDT</text></text
                                    ></view
                                ><view
                                    ><text class="small">{{ t('Annual fee reward rate') }}</text
                                    ><text class="benefit">{{
                                        offer.rank === 0 || offer.percent === undefined
                                            ? '—'
                                            : offer.percent + '%'
                                    }}</text></view
                                ></view
                            ><AnnualRebateProgress
                                v-if="offer.current && p.cycle && p.progress"
                                :progress="p.progress"
                            /><view class="card-footer"
                                ><text v-if="offer.current" class="small">{{ expiry }}</text
                                ><text v-else-if="offer.rank < p.rank" class="small">{{
                                    t('Downgrades are not available.')
                                }}</text
                                ><text
                                    v-else-if="!offer.offer?.enabled || !offer.canUpgrade"
                                    class="small"
                                    >{{ t('Currently unavailable for purchase') }}</text
                                ><button
                                    v-else
                                    class="primary"
                                    :disabled="
                                        action.pending.value ||
                                        p.pending ||
                                        !home.canPurchase ||
                                        !offer.offer.selectable
                                    "
                                    @click="quote(offer.offer.id)"
                                >
                                    {{
                                        t(
                                            p.membershipStatus === 'EXPIRED'
                                                ? 'Renew or reactivate'
                                                : p.rank > 0
                                                  ? 'Upgrade to this level'
                                                  : 'Apply for this level',
                                        )
                                    }}
                                </button></view
                            ><text
                                v-if="offer.offer?.unavailableReason && !offer.current"
                                class="small"
                                >{{ t(offer.offer.unavailableReason) }}</text
                            ></view
                        ></swiper-item
                    ></swiper
                ><view class="switcher"
                    ><button :disabled="selected === 0" @click="selected--">‹</button
                    ><view class="dots"
                        ><button
                            v-for="(rank, i) in ranks"
                            :key="rank"
                            :aria-label="promotionLevel(rank)"
                            @click="selected = i"
                        >
                            <view :class="{ selected: selected === i }" /></button></view
                    ><button :disabled="selected === ranks.length - 1" @click="selected++">
                        ›
                    </button></view
                ><text class="swipe-note muted">{{ t('Swipe to compare levels') }}</text
                ><text v-if="p.manualLevel" class="note muted">{{
                    t(
                        'Your promotion level is managed by the platform. No annual payment is needed. Contact support to change it.',
                    )
                }}</text
                ><text v-if="!home.canPurchase" class="note muted">{{
                    t('An active verified USDT wallet is required to purchase a level.')
                }}</text
                ><view v-if="p.pending" class="pending"
                    ><text>{{ t('Annual fee return is processing. Try upgrading shortly.') }}</text
                    ><button class="link" @click="go('/promotion/membership')">
                        {{ t('Fee rebate history') }}
                    </button></view
                ></view
            ><view class="destinations"
                ><button
                    v-for="entry in [
                        { href: '/promotion/invitations', label: 'Invitation data', icon: 'users' },
                        { href: '/promotion/rules', label: 'U Card Academy', icon: 'book-open' },
                    ]"
                    :key="entry.href"
                    @click="go(entry.href)"
                >
                    <UiIcon :name="entry.icon" color="#27866d" :size="20" /><text>{{
                        t(entry.label)
                    }}</text
                    ><UiIcon name="chevron-right" :size="16" /></button></view
            ><view
                ><text class="heading">{{ t('Invitation steps') }}</text
                ><view class="invite-steps"
                    ><view
                        v-for="(step, i) in [
                            'Share your invitation link with a friend.',
                            'Your friend registers through the link and joins your team.',
                            'After a successful security deposit or promotion annual fee payment, rewards follow your valid level and the commission rules.',
                        ]"
                        :key="step"
                        ><text class="step-number">{{ i + 1 }}</text
                        ><text>{{ t(step) }}</text></view
                    ></view
                ></view
            ><view class="invitation-code"
                ><view
                    ><text class="small muted">{{ t('Invitation code') }}</text
                    ><text class="code">{{ home.invitationCode }}</text></view
                ><button class="copy" @click="copy">
                    <UiIcon name="copy" :size="16" />{{ t('Copy invitation link') }}
                </button></view
            ><view class="share-dock"
                ><view class="share-buttons"
                    ><button class="primary" @click="poster?.generate()">
                        <UiIcon name="image" color="#ffffff" :size="16" /><text>{{
                            t('Invitation poster')
                        }}</text></button
                    ><button class="primary" :disabled="sharing" @click="share">
                        <UiIcon name="share2" color="#ffffff" :size="16" /><text>{{
                            t('Share invitation link')
                        }}</text>
                    </button></view
                ><text v-if="shareState" class="small muted">{{
                    t(
                        shareState === 'copied'
                            ? 'Copied'
                            : shareState === 'shared'
                              ? 'Invitation link shared.'
                              : 'Could not copy. Copy the link below manually.',
                    )
                }}</text
                ><text v-if="shareState === 'failed'" class="link-text" selectable>{{
                    link
                }}</text></view
            ></view
        ><InvitationPoster
            ref="poster"
            :link="link"
            :code="home.invitationCode"
            :background="home.posterBackground"
    /></PageShell>
</template>
<style scoped>
.hub {
    display: flex;
    flex-direction: column;
    gap: 20px;
    font-size: 14px;
    padding-bottom: 110px;
}
.level-swiper {
    margin: 0;
}
.level-card {
    box-sizing: border-box;
    margin: 2px 6px 6px;
    display: flex;
    flex-direction: column;
    border-radius: 16px;
    border: 1px solid #e8dec5;
    padding: 16px;
    background: #faf5e7;
    color: #193b31;
}
.level-card.current {
    background: #193b31;
    color: #fff0bb;
    border-color: #c7ac6b;
}
.card-heading {
    display: grid;
    grid-template-columns: minmax(0, 1fr) auto;
    gap: 8px;
    align-items: start;
}
.level-name {
    font-size: 16px;
    line-height: 24px;
    font-weight: 600;
    overflow-wrap: anywhere;
}
.price {
    font-size: 14px;
    font-weight: 600;
    line-height: 24px;
    text-align: right;
    max-width: 145px;
}
.small {
    font-size: 12px;
    font-weight: 400;
    line-height: 20px;
}
.current-label {
    display: block;
    width: fit-content;
    margin-top: 8px;
    border-radius: 999px;
    border: 1px solid #fff0bb;
    padding: 2px 8px;
    font-size: 12px;
    line-height: 16px;
}
.benefits {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
    margin-top: 12px;
    padding-top: 12px;
    border-top: 1px solid currentColor;
}
.benefits > view > .small {
    opacity: 0.75;
}
.benefit {
    display: block;
    font-size: 18px;
    font-weight: 600;
    margin-top: 4px;
}
.card-footer {
    margin-top: auto;
    padding-top: 12px;
}
.card-footer button {
    width: 100%;
    font-size: 14px;
}
.switcher {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
    margin-top: 12px;
}
.switcher button {
    background: none;
    margin: 0;
    padding: 0;
    width: 44px;
    height: 44px;
    line-height: 44px;
    font-size: 24px;
}
.dots {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
}
.dots button {
    width: 24px;
    display: flex;
    justify-content: center;
    align-items: center;
}
.dots view {
    width: 6px;
    height: 6px;
    border-radius: 999px;
    background: #42a88c33;
}
.dots view.selected {
    width: 20px;
    background: #42a88c;
}
.swipe-note {
    display: block;
    text-align: center;
    font-size: 12px;
    line-height: 20px;
}
.note {
    display: block;
    margin-top: 12px;
    font-size: 12px;
    line-height: 20px;
}
.pending {
    padding: 12px;
    border-radius: 12px;
    background: #f0f3f1;
    margin-top: 12px;
}
.link {
    display: inline;
    background: none;
    padding: 0;
    text-decoration: underline;
    font-size: 14px;
    line-height: 22px;
}
.destinations {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
}
.destinations button {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 16px;
    border-radius: 16px;
    border: 1px solid #e2e7e4;
    background: white;
    font-size: 14px;
    line-height: 20px;
    text-align: left;
    margin: 0;
}
.destinations text {
    flex: 1;
    overflow-wrap: anywhere;
}
.heading {
    font-weight: 600;
    font-size: 16px;
}
.invite-steps {
    margin: 20px 0;
    display: flex;
    flex-direction: column;
}
.invite-steps > view {
    display: flex;
    gap: 12px;
    align-items: start;
    line-height: 1.8;
    font-size: 13px;
    position: relative;
    padding-bottom: 24px;
}
.invite-steps > view:not(:last-child)::before {
    content: '';
    position: absolute;
    top: 24px;
    bottom: 0;
    left: 11px;
    border-left: 1px dashed #a9c7b9;
}
.step-number {
    width: 24px;
    height: 24px;
    background: #e3f0e9;
    color: #254235;
    border-radius: 50%;
    text-align: center;
    flex-shrink: 0;
    font-size: 12px;
}
.invitation-code {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding-bottom: 16px;
}
.code {
    display: block;
    font-size: 20px;
    letter-spacing: 0.1em;
    font-weight: 600;
    margin-top: 4px;
}
.copy {
    display: flex;
    align-items: center;
    gap: 8px;
    background: none;
    font-size: 14px;
    padding: 0;
    line-height: 22px;
}
.share-dock {
    position: fixed;
    bottom: calc(clamp(64px, 14.133cqw, 106px) + env(safe-area-inset-bottom));
    left: 50%;
    transform: translateX(-50%);
    width: 100%;
    max-width: 750px;
    box-sizing: border-box;
    background: white;
    border-top: 1px solid #e2e7e4;
    padding: 8px min(4.267cqw, 32px);
    z-index: 30;
}
.share-buttons {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
}
.share-buttons > .primary {
    gap: 8px;
    width: 100%;
    border-radius: 999px;
    font-size: clamp(16px, 3.2cqw, 24px);
    line-height: 1.5;
    padding: 4px 24px;
    min-height: clamp(48px, 10.667cqw, 80px);
}
.share-buttons :deep(button text) {
    font-size: inherit;
    line-height: 1.5;
}
.share-dock > .small {
    display: block;
    margin-top: 8px;
}
.link-text {
    display: block;
    font-size: 12px;
    overflow-wrap: anywhere;
    margin-top: 8px;
}
</style>
