// resources/js/pages/user/TopupStatus.tsx
import { DepositInstructions } from '@/components/user/DepositInstructions';
import { t, useClientTranslation } from '@/i18n';
import { Head, Link, router } from '@inertiajs/react';
import { CheckCircle2, Clock3, XCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { MoneyDisplay } from '@/components/shared/MoneyDisplay';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { Button } from '@/components/ui/button';

import { UserLayout } from '@/layouts/UserLayout';
import type { MoneyAmount } from '@/types/global';

type Status =
    | 'WAITING'
    | 'CONFIRMING'
    | 'ADDING_FUNDS'
    | 'PROCESSING'
    | 'COMPLETED'
    | 'FAILED'
    | 'CANCELLED'
    | 'EXPIRED';
type Props = {
    depositFlow?: boolean;
    order: {
        id: string;
        requestedAmount: MoneyAmount;
        expectedAmount: MoneyAmount;
        amount: MoneyAmount;
        asset: string;
        status: Status;
        paymentDetected: boolean;
        network: string | null;
        depositAddress: string | null;
        expiresAt: string | null;
        mockSimulationAvailable: boolean;
    };
};

function remaining(expiresAt: string | null): string {
    if (!expiresAt) return '';
    const seconds = Math.max(0, Math.floor((new Date(expiresAt).getTime() - Date.now()) / 1000));
    return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;
}

export default function TopupStatus({ order, depositFlow = false }: Props) {
    useClientTranslation();
    const [countdown, setCountdown] = useState(() => remaining(order.expiresAt));
    const [simulating, setSimulating] = useState(false);
    const processing = ['WAITING', 'CONFIRMING', 'ADDING_FUNDS', 'PROCESSING'].includes(
        order.status,
    );
    useEffect(() => {
        if (!processing) return;
        const timer = window.setInterval(() => {
            setCountdown(remaining(order.expiresAt));
            router.reload({ only: ['order'] });
        }, 4000);
        return () => window.clearInterval(timer);
    }, [order.expiresAt, processing]);

    const completed = order.status === 'COMPLETED';
    const expired = order.status === 'EXPIRED';
    const failed = ['FAILED', 'CANCELLED'].includes(order.status);
    const trc20 = order.network === 'TRON' && order.depositAddress;
    const backHref = depositFlow ? '/security-deposit' : '/dashboard';

    if (trc20 && !completed && !failed) {
        return (
            <UserLayout>
                <Head title={t('Top up')} />
                <div className="mx-auto max-w-lg space-y-6">
                    <UserPageHeader title={t('Top up')} backHref={backHref} />
                    <DepositInstructions
                        asset={order.asset}
                        amount={order.expectedAmount}
                        network={order.network}
                        address={order.depositAddress}
                        state={
                            expired || countdown === '00:00'
                                ? 'Top-up expired'
                                : order.paymentDetected
                                  ? 'Payment detected'
                                  : 'Waiting for payment'
                        }
                        expiresAt={order.expiresAt}
                        payable={!expired && !order.paymentDetected && countdown !== '00:00'}
                        newHref={
                            depositFlow
                                ? '/security-deposit'
                                : '/assets/operate?asset=USDT&mode=deposit'
                        }
                    >
                        {order.mockSimulationAvailable && (
                            <Button
                                disabled={simulating}
                                onClick={() => {
                                    setSimulating(true);
                                    router.post(
                                        `/__mock/topups/${order.id}/complete`,
                                        {},
                                        {
                                            preserveScroll: true,
                                            onFinish: () => setSimulating(false),
                                        },
                                    );
                                }}
                            >
                                {simulating ? t('Simulating…') : t('Simulate demo payment')}
                            </Button>
                        )}
                    </DepositInstructions>
                </div>
            </UserLayout>
        );
    }

    const Icon = completed ? CheckCircle2 : failed || expired ? XCircle : Clock3;
    return (
        <UserLayout>
            <Head title={t('Top-up status')} />
            <div className="space-y-6">
                <UserPageHeader title={t('Top-up status')} backHref={backHref} />
                <section className="rounded-[var(--user-radius-lg)] border bg-surface p-6 text-center sm:p-10">
                    <Icon
                        className={`mx-auto size-12 ${completed ? 'text-success' : failed || expired ? 'text-danger' : 'text-warning'}`}
                    />
                    <h1 className="mt-5 text-xl font-semibold">
                        {completed
                            ? t('Top-up complete')
                            : expired
                              ? t('Top-up expired')
                              : failed
                                ? t("Payment wasn't completed")
                                : t('Adding funds to wallet')}
                    </h1>
                    <p className="mt-2 text-sm text-muted-foreground">
                        {completed
                            ? t('The full exact transfer is now available in your wallet.')
                            : expired
                              ? t(
                                    'Create a new top-up to continue. No new amount was generated automatically.',
                                )
                              : failed
                                ? t('No funds were added to your wallet.')
                                : t(
                                      'Your payment is confirmed and the wallet credit is being completed.',
                                  )}
                    </p>
                    <p className="mt-5 text-lg font-semibold">
                        <MoneyDisplay
                            amount={order.expectedAmount ?? order.amount}
                            asset={order.asset}
                            compact
                        />
                    </p>
                    <Button asChild className="mt-6 w-full sm:w-auto">
                        <Link
                            href={
                                depositFlow
                                    ? '/security-deposit'
                                    : expired
                                      ? '/wallet/top-up'
                                      : '/dashboard'
                            }
                        >
                            {depositFlow
                                ? t('Security deposit')
                                : expired
                                  ? t('Create new top-up')
                                  : t('Back to home')}
                        </Link>
                    </Button>
                </section>
            </div>
        </UserLayout>
    );
}

// mobile/uni-app/src/screens/TopupStatus.vue
<script setup lang="ts">
import { computed, ref, onBeforeUnmount } from 'vue';
import { onShow, onHide } from '@dcloudio/uni-app';
import PageShell from '../components/PageShell.vue';
import DepositInstructions from '../components/DepositInstructions.vue';
import UiIcon from '../components/UiIcon.vue';
import { t } from '../lib/i18n';
import { go } from '../lib/navigation';
import { exactAmount } from '../generated/exact-amount';
const props = defineProps<{
    page: {
        depositFlow?: boolean;
        order: {
            id: string;
            expectedAmount: string;
            amount: string;
            asset: string;
            status: string;
            paymentDetected: boolean;
            network: string | null;
            depositAddress: string | null;
            expiresAt: string | null;
        };
    };
}>();
const emit = defineEmits<{ reload: [] }>();
const now = ref(Date.now()),
    visible = ref(true);
onShow(() => (visible.value = true));
onHide(() => (visible.value = false));
const timer = setInterval(() => {
    now.value = Date.now();
    if (
        visible.value &&
        ['WAITING', 'CONFIRMING', 'ADDING_FUNDS', 'PROCESSING'].includes(props.page.order.status)
    )
        emit('reload');
}, 4000);
onBeforeUnmount(() => clearInterval(timer));
const completed = computed(() => props.page.order.status === 'COMPLETED');
const expired = computed(
    () =>
        props.page.order.status === 'EXPIRED' ||
        (!completed.value &&
            props.page.order.expiresAt &&
            Date.parse(props.page.order.expiresAt) <= now.value),
);
const failed = computed(() => ['FAILED', 'CANCELLED'].includes(props.page.order.status));
const back = computed(() => (props.page.depositFlow ? '/security-deposit' : '/dashboard'));
const title = computed(() =>
    t(
        completed.value
            ? 'Funds added'
            : expired.value
              ? 'Top-up expired'
              : failed.value
                ? "Payment wasn't completed"
                : 'Adding funds to wallet',
    ),
);
const description = computed(() =>
    t(
        completed.value
            ? 'The full exact transfer is now available in your wallet.'
            : expired.value
              ? 'Create a new top-up to continue. No new amount was generated automatically.'
              : failed.value
                ? 'No funds were added to your wallet.'
                : 'Your payment is confirmed and the wallet credit is being completed.',
    ),
);
</script>
<template>
    <PageShell :title="t('Top up')" :back="back" active="assets"
        ><view class="topup-status"
            ><DepositInstructions
                v-if="
                    page.order.network === 'TRON' &&
                    page.order.depositAddress &&
                    !completed &&
                    !failed
                "
                :asset="page.order.asset"
                :amount="page.order.expectedAmount"
                :network="page.order.network"
                :address="page.order.depositAddress"
                :state="
                    expired
                        ? 'Top-up expired'
                        : page.order.paymentDetected
                          ? 'Payment detected'
                          : 'Waiting for payment'
                "
                :expires-at="page.order.expiresAt"
                :payable="!expired && !page.order.paymentDetected"
                :new-href="
                    page.depositFlow
                        ? '/security-deposit'
                        : '/assets/operate?asset=USDT&mode=deposit'
                "
            /><view v-else class="status-card"
                ><view class="status-icon"
                    ><UiIcon
                        :name="
                            completed
                                ? 'circle-check'
                                : failed || expired
                                  ? 'circle-alert'
                                  : 'history'
                        "
                        :size="40" /></view
                ><text class="status-title">{{ title }}</text
                ><text class="status-description">{{ description }}</text
                ><text class="status-amount"
                    >{{ exactAmount(page.order.expectedAmount ?? page.order.amount) }}
                    {{ page.order.asset }}</text
                ><button
                    class="primary"
                    @click="
                        go(
                            page.depositFlow
                                ? '/security-deposit'
                                : expired
                                  ? '/wallet/top-up'
                                  : '/dashboard',
                        )
                    "
                >
                    {{
                        t(
                            page.depositFlow
                                ? 'Security deposit'
                                : expired
                                  ? 'Create new top-up'
                                  : 'Back to home',
                        )
                    }}
                </button></view
            ></view
        ></PageShell
    >
</template>
<style scoped>
.topup-status {
    max-width: 512px;
    margin: auto;
}
.status-card {
    text-align: center;
    border: 1px solid #e2e7e4;
    border-radius: 24px;
    background: white;
    padding: 28px;
}
.status-icon {
    margin: auto auto 20px;
    width: 64px;
    height: 64px;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    background: #ecfdf5;
}
.status-title {
    display: block;
    font-size: 24px;
    font-weight: 600;
}
.status-description {
    display: block;
    font-size: 14px;
    color: #68736e;
    line-height: 24px;
    margin-top: 8px;
}
.status-amount {
    display: block;
    margin-top: 20px;
    font-size: 18px;
    font-weight: 600;
    overflow-wrap: anywhere;
}
.primary {
    margin-top: 24px;
    border-radius: 999px;
    min-height: 44px;
    padding: 10px 20px;
    font-size: 14px;
    line-height: 24px;
}
</style>
