// resources/js/pages/user/Wealth.tsx
import { ChevronRight } from 'lucide-react';
import { wealthState, wealthDate } from '@/lib/wealth-display';
import { useRef, useState } from 'react';
import { Head, Link, useForm, router } from '@inertiajs/react';
import { t, useClientTranslation, errorMessage } from '@/i18n';
import { UserLayout } from '@/layouts/UserLayout';
import { UserPageHeader } from '@/components/user/UserPageHeader';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { FormField } from '@/components/ui/form-field';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
} from '@/components/ui/dialog';
import { exactAmount } from '@/lib/exact-amount';

export type WealthSetting = {
    asset: string;
    minimum: string;
    revision: string | null;
    products: { months: number; rate: string; enabled: boolean }[];
    available: string;
    principal: string;
    interest: string;
    net: string;
};
export type WealthOrderData = {
    id: string;
    asset: string;
    principal: string;
    rate: string;
    months: number;
    status: string;
    displayStatus: string;
    startedAt: string;
    maturesAt: string;
    paid: string;
    returnAmount: string;
    clawback: string | null;
    closedAt: string | null;
    canCancel: boolean;
    canRedeem: boolean;
    maturityPolicy: 'AUTO_RETURN' | 'MANUAL_REDEEM_RENEW';
    redeemBefore: string | null;
    redeemBeforeLocal: string | null;
    previousOrderId: string | null;
    nextOrderId: string | null;
    timezone: string;
};
export function WealthNotice() {
    return (
        <div className="space-y-2 rounded-xl bg-muted p-4 text-sm leading-6">
            <p>
                {t(
                    'Interest is automatically paid to your balance every month. Paid interest is recovered on early withdrawal.',
                )}
            </p>
            <p>
                {t(
                    'Early withdrawal cancels the whole deposit. You receive principal minus interest already paid; including those payments, you recover your principal.',
                )}
            </p>
        </div>
    );
}
export default function Wealth({
    settings,
    orders,
    selectedAsset = 'USDT',
    view = 'deposit',
}: {
    settings: WealthSetting[];
    selectedAsset?: string;
    view?: 'details' | 'deposit' | 'withdraw';
    orders: { data: WealthOrderData[]; prev_page_url: string | null; next_page_url: string | null };
}) {
    useClientTranslation();
    const [asset, setAsset] = useState(selectedAsset);
    const [review, setReview] = useState(false);
    const reviewButton = useRef<HTMLFormElement>(null);
    const setting = settings.find((s) => s.asset === asset)!;
    const form = useForm({
        asset,
        months: 1,
        amount: '',
        revision: setting.revision ?? '',
        request_id: crypto.randomUUID(),
        confirmed: false,
    });
    const product = setting.products.find((p) => p.months === form.data.months)!;
    const resetReview = () => {
        setReview(false);
        form.setData('confirmed', false);
        form.setData('request_id', crypto.randomUUID());
    };
    const currencySelector = (
        <div className={view === 'deposit' ? 'space-y-2' : 'flex justify-end'}>
            <label
                htmlFor="wealth-asset"
                className={view === 'deposit' ? 'block text-sm font-medium' : 'sr-only'}
            >
                {t('Select currency')}
            </label>
            <select
                id="wealth-asset"
                className={
                    view === 'deposit'
                        ? 'w-full rounded-xl border bg-surface p-3 text-base'
                        : 'max-w-full rounded-lg border bg-surface px-3 py-2 text-base'
                }
                value={asset}
                disabled={form.processing}
                onChange={(e) => {
                    const s = settings.find((s) => s.asset === e.target.value)!;
                    setAsset(s.asset);
                    router.get(`/wealth/assets/${s.asset}`, { view }, { preserveScroll: true });
                    setReview(false);
                    form.setData({
                        asset: s.asset,
                        months: 1,
                        amount: '',
                        revision: s.revision ?? '',
                        request_id: crypto.randomUUID(),
                        confirmed: false,
                    });
                }}
            >
                {settings.map((s) => (
                    <option key={s.asset}>{s.asset}</option>
                ))}
            </select>
        </div>
    );
    return (
        <UserLayout>
            <Head title={t('Wealth management')} />
            <div className="space-y-5">
                <div className={view !== 'deposit' ? 'wealth-currency-header' : undefined}>
                    <UserPageHeader
                        title={
                            view === 'details'
                                ? t('{{asset}} wealth details', { asset })
                                : `${asset} · ${t(view === 'deposit' ? 'Wealth deposit action' : view === 'withdraw' ? 'Wealth withdraw action' : 'Wealth details action')}`
                        }
                        backHref="/wealth"
                        action={view !== 'deposit' ? currencySelector : undefined}
                    />
                </div>
                {view === 'withdraw' && <WealthNotice />}
                {view === 'deposit' && currencySelector}
                {view !== 'deposit' && (
                    <dl className="grid grid-cols-2 gap-4 rounded-xl bg-surface p-4 text-sm">
                        <div>
                            <dt className="text-xs text-muted-foreground">
                                {t('Current wealth principal')}
                            </dt>
                            <dd className="mt-1 break-all text-lg font-semibold tabular-nums">
                                <span className="block">{exactAmount(setting.principal)}</span>
                                <span className="block text-xs font-normal text-muted-foreground">
                                    {asset}
                                </span>
                            </dd>
                        </div>
                        <div>
                            <dt className="text-xs text-muted-foreground">
                                {t('Cumulative net earnings')}
                            </dt>
                            <dd className="mt-1 break-all text-lg font-semibold tabular-nums">
                                <span className="block">{exactAmount(setting.net)}</span>
                                <span className="block text-xs font-normal text-muted-foreground">
                                    {asset}
                                </span>
                            </dd>
                        </div>
                    </dl>
                )}
                {view === 'deposit' && (
                    <form
                        ref={reviewButton}
                        className="space-y-4 rounded-2xl bg-surface p-5"
                        onSubmit={(e) => {
                            e.preventDefault();
                            if (form.processing || review) return;
                            form.setData('revision', setting.revision ?? '');
                            form.setData('confirmed', false);
                            setReview(true);
                        }}
                    >
                        <p className="text-sm">
                            {t('Available balance: {{amount}}', {
                                amount: `${exactAmount(setting.available)} ${asset}`,
                            })}
                        </p>
                        <FormField id="wealth-term" label={t('Wealth term')}>
                            <select
                                id="wealth-term"
                                className="w-full rounded-xl border bg-surface p-3"
                                disabled={review || form.processing}
                                value={form.data.months}
                                onChange={(e) => {
                                    form.setData('months', Number(e.target.value));
                                    resetReview();
                                }}
                            >
                                {setting.products.map((p) => (
                                    <option key={p.months} value={p.months}>
                                        {t('{{months}} months · {{rate}}% annual rate', {
                                            months: p.months,
                                            rate: exactAmount(p.rate),
                                        })}
                                        {!p.enabled ? ` · ${t('Unavailable')}` : ''}
                                    </option>
                                ))}
                            </select>
                        </FormField>
                        <FormField id="wealth-amount" label={t('Deposit principal')}>
                            <Input
                                id="wealth-amount"
                                className="text-base"
                                value={form.data.amount}
                                inputMode="decimal"
                                required
                                disabled={review || form.processing}
                                onChange={(e) => {
                                    form.setData('amount', e.target.value);
                                    resetReview();
                                }}
                            />
                        </FormField>
                        {setting.minimum && (
                            <p className="text-sm text-muted-foreground">
                                {t('Minimum wealth deposit: {{amount}}', {
                                    amount: `${exactAmount(setting.minimum)} ${asset}`,
                                })}
                            </p>
                        )}
                        {!product.enabled && (
                            <p className="text-sm">
                                {t('This wealth product is not available for new deposits.')}
                            </p>
                        )}
                        {Object.values(form.errors).map((e, i) => (
                            <p key={i} role="alert" className="text-sm text-destructive">
                                {errorMessage(e)}
                            </p>
                        ))}
                        <Button
                            className="w-full"
                            type="submit"
                            disabled={
                                form.processing || !product.enabled || !setting.revision || review
                            }
                        >
                            {t('Review wealth deposit')}
                        </Button>
                    </form>
                )}
                <Dialog
                    open={view === 'deposit' && review}
                    onOpenChange={(open) => {
                        if (form.processing) return;
                        setReview(open);
                        if (!open) form.setData('confirmed', false);
                    }}
                >
                    <DialogContent
                        closeLabel={t('Close')}
                        closeDisabled={form.processing}
                        className="max-h-[85dvh] overflow-y-auto overflow-x-hidden overscroll-contain"
                        onCloseAutoFocus={(e) => {
                            e.preventDefault();
                            reviewButton.current
                                ?.querySelector<HTMLButtonElement>('button[type=submit]')
                                ?.focus();
                        }}
                        onEscapeKeyDown={(e) => {
                            if (form.processing) e.preventDefault();
                        }}
                        onInteractOutside={(e) => {
                            if (form.processing) e.preventDefault();
                        }}
                    >
                        <DialogHeader>
                            <DialogTitle className="pr-10">
                                {t('Confirm wealth deposit')}
                            </DialogTitle>
                            <DialogDescription className="break-words">
                                {t(
                                    'Review wealth deposit: {{amount}}, {{months}} months, {{rate}}% annual rate.',
                                    {
                                        amount: `${exactAmount(form.data.amount)} ${asset}`,
                                        months: product.months,
                                        rate: exactAmount(product.rate),
                                    },
                                )}
                            </DialogDescription>
                        </DialogHeader>
                        <form
                            className="space-y-4"
                            onSubmit={(e) => {
                                e.preventDefault();
                                if (form.processing || !form.data.confirmed) return;
                                form.post('/wealth/orders', {
                                    onSuccess: () => {
                                        setReview(false);
                                        form.setData('confirmed', false);
                                    },
                                    onError: () => {
                                        setReview(false);
                                        form.setData('confirmed', false);
                                    },
                                });
                            }}
                        >
                            <p className="text-sm">
                                {t(
                                    'Redeem principal on the maturity day before midnight in the order timezone. Otherwise, the same principal renews for the same term and rate. Paid interest stays in your wallet.',
                                )}
                            </p>
                            <p className="text-sm text-muted-foreground">
                                {t(
                                    'No extra interest accrues during the redemption window. Processing delays do not shift the next term.',
                                )}
                            </p>
                            <WealthNotice />
                            <label className="flex items-start gap-2 text-sm">
                                <input
                                    className="mt-1"
                                    type="checkbox"
                                    checked={form.data.confirmed}
                                    disabled={form.processing}
                                    required
                                    onChange={(e) => form.setData('confirmed', e.target.checked)}
                                />
                                {t('I confirm the term, interest rate and early withdrawal rules.')}
                            </label>
                            <div className="grid grid-cols-2 gap-3">
                                <Button
                                    type="button"
                                    variant="secondary"
                                    disabled={form.processing}
                                    onClick={() => {
                                        setReview(false);
                                        form.setData('confirmed', false);
                                    }}
                                >
                                    {t('Back')}
                                </Button>
                                <Button
                                    type="submit"
                                    disabled={
                                        form.processing ||
                                        !form.data.confirmed ||
                                        !product.enabled ||
                                        !setting.revision
                                    }
                                >
                                    {t('Confirm wealth deposit')}
                                </Button>
                            </div>
                        </form>
                    </DialogContent>
                </Dialog>
                {view !== 'deposit' && (
                    <>
                        <div className="flex items-center justify-between gap-3">
                            <h2 className="font-semibold">{t('Wealth deposit records')}</h2>
                            {view === 'details' && (
                                <Link
                                    href={`/wealth/assets/${asset}?view=deposit`}
                                    className="inline-flex min-h-11 shrink-0 items-center justify-center rounded-xl border border-emerald-700 bg-emerald-700 px-5 py-2 text-sm font-semibold text-white shadow-sm transition-colors hover:border-emerald-800 hover:bg-emerald-800 active:bg-emerald-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-600 focus-visible:ring-offset-2"
                                >
                                    {t('Wealth deposit action')}
                                </Link>
                            )}
                        </div>
                        {orders.data.length === 0 && (
                            <p className="text-sm text-muted-foreground">
                                {t(
                                    view === 'withdraw'
                                        ? 'No deposits available for early withdrawal.'
                                        : 'No wealth deposits yet.',
                                )}
                            </p>
                        )}
                        <div className="space-y-3">
                            {orders.data.map((o) => (
                                <Link
                                    className="block space-y-3 rounded-2xl border border-black/5 bg-surface p-4 shadow-sm transition hover:border-emerald-600/30 hover:shadow-md active:bg-emerald-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-600"
                                    key={o.id}
                                    href={`/wealth/orders/${o.id}?view=${view === 'withdraw' ? 'withdraw' : 'details'}`}
                                >
                                    <div className="flex flex-wrap items-start justify-between gap-2">
                                        <p className="min-w-0 break-all text-xl font-semibold tabular-nums">
                                            {exactAmount(o.principal)}{' '}
                                            <span className="text-sm font-medium">{o.asset}</span>
                                        </p>
                                        <span
                                            className={`max-w-full rounded-full px-2.5 py-1 text-xs ${o.displayStatus === 'ACTIVE' ? 'bg-emerald-50 text-emerald-800' : o.displayStatus === 'AWAITING_SETTLEMENT' ? 'bg-amber-50 text-amber-800' : 'bg-muted text-muted-foreground'}`}
                                        >
                                            {wealthState(o.displayStatus)}
                                        </span>
                                    </div>
                                    <div className="space-y-1">
                                        <p className="text-sm">
                                            {t('{{months}} months · {{rate}}% annual rate', {
                                                months: o.months,
                                                rate: exactAmount(o.rate),
                                            })}
                                        </p>
                                        <p className="text-xs text-muted-foreground">
                                            {t('Maturity date')}:{' '}
                                            {wealthDate(o.maturesAt, o.timezone)}
                                        </p>
                                        {o.redeemBeforeLocal && (
                                            <p className="text-xs text-muted-foreground">
                                                {t('Redeem before')}: {o.redeemBeforeLocal} (
                                                {o.timezone})
                                            </p>
                                        )}
                                    </div>
                                    <div className="flex flex-wrap items-end justify-between gap-3 border-t pt-3">
                                        <div className="min-w-0">
                                            <p className="text-xs text-muted-foreground">
                                                {t('Total interest paid')}
                                            </p>
                                            <p className="mt-1 break-all text-sm font-medium tabular-nums">
                                                {exactAmount(o.paid)} {o.asset}
                                            </p>
                                        </div>
                                        <span className="flex items-center gap-1 text-sm font-semibold text-emerald-700">
                                            {t(
                                                view === 'withdraw'
                                                    ? 'Wealth withdraw action'
                                                    : 'Wealth view details',
                                            )}
                                            <ChevronRight
                                                className="size-4 shrink-0"
                                                aria-hidden="true"
                                            />
                                        </span>
                                    </div>
                                </Link>
                            ))}
                        </div>
                        <div className="flex justify-between">
                            {orders.prev_page_url && (
                                <Link href={orders.prev_page_url}>{t('Previous')}</Link>
                            )}
                            {orders.next_page_url && (
                                <Link href={orders.next_page_url}>{t('Next')}</Link>
                            )}
                        </div>
                    </>
                )}
            </div>
        </UserLayout>
    );
}

// mobile/uni-app/src/screens/Wealth.vue
<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import PageShell from '../components/PageShell.vue';
import SelectField from '../components/SelectField.vue';
import FormField from '../components/FormField.vue';
import FormErrors from '../components/FormErrors.vue';
import ConfirmCheck from '../components/ConfirmCheck.vue';
import Modal from '../components/Modal.vue';
import WealthNotice from '../components/WealthNotice.vue';
import UiIcon from '../components/UiIcon.vue';
import { t } from '../lib/i18n';
import { go } from '../lib/navigation';
import { useAction, requestId } from '../lib/client';
import {
    wealthState,
    wealthDate,
    wealthTerm,
    type WealthSetting,
    type WealthOrder,
} from '../lib/wealth';
import { exactAmount } from '../generated/exact-amount';
const props = defineProps<{
    page: {
        settings: WealthSetting[];
        selectedAsset?: string;
        view?: 'details' | 'deposit' | 'withdraw';
        orders: { data: WealthOrder[]; prev_page_url: string | null; next_page_url: string | null };
    };
}>();
const view = computed(() => props.page.view ?? 'deposit'),
    asset = ref(props.page.selectedAsset ?? 'USDT'),
    review = ref(false),
    action = useAction();
const setting = computed(() => props.page.settings.find((s) => s.asset === asset.value)!);
const form = reactive({
    asset: asset.value,
    months: '1',
    amount: '',
    revision: setting.value.revision ?? '',
    request_id: requestId(),
    confirmed: false,
});
const product = computed(() =>
    setting.value.products.find((p) => p.months === Number(form.months)),
);
const title = computed(() =>
    view.value === 'details'
        ? t('{{asset}} wealth details', { asset: asset.value })
        : asset.value +
          ' · ' +
          t(view.value === 'deposit' ? 'Wealth deposit action' : 'Wealth withdraw action'),
);
const available = computed(() =>
    t('Available balance: {{amount}}', {
        amount: exactAmount(setting.value.available) + ' ' + asset.value,
    }),
);
const minimum = computed(() =>
    t('Minimum wealth deposit: {{amount}}', {
        amount: exactAmount(setting.value.minimum) + ' ' + asset.value,
    }),
);
const reviewDescription = computed(() =>
    t('Review wealth deposit: {{amount}}, {{months}} months, {{rate}}% annual rate.', {
        amount: exactAmount(form.amount) + ' ' + asset.value,
        months: product.value?.months ?? 1,
        rate: exactAmount(product.value?.rate ?? '0'),
    }),
);
function changed() {
    review.value = false;
    form.confirmed = false;
    form.request_id = requestId();
}
function selectCurrency(value: string) {
    asset.value = value;
    form.asset = value;
    form.months = '1';
    form.amount = '';
    form.revision = setting.value.revision ?? '';
    changed();
    if (view.value !== 'deposit') go('/wealth/assets/' + value + '?view=' + view.value, true);
}
function openReview() {
    if (action.pending.value || !product.value?.enabled || !setting.value.revision) return;
    form.revision = setting.value.revision;
    form.confirmed = false;
    review.value = true;
}
function closeReview() {
    if (action.pending.value) return;
    review.value = false;
    form.confirmed = false;
}
async function submit() {
    if (!form.confirmed || !product.value?.enabled) return;
    await action.submit('/wealth/orders', { ...form, months: Number(form.months) });
    review.value = false;
    form.confirmed = false;
}
function paidLabel(order: WealthOrder) {
    return t('Total interest paid') + ': ' + exactAmount(order.paid) + ' ' + order.asset;
}
</script>
<template>
    <PageShell :title="title" back="/wealth" active="assets"
        ><view class="wealth-page"
            ><WealthNotice v-if="view === 'withdraw'" /><SelectField
                :model-value="asset"
                :label="t('Select currency')"
                :options="page.settings.map((s) => ({ value: s.asset, label: s.asset }))"
                :disabled="action.pending.value || review"
                @update:model-value="selectCurrency"
            /><view v-if="view !== 'deposit'" class="wealth-totals"
                ><view
                    ><text class="small muted">{{ t('Current wealth principal') }}</text
                    ><text class="total">{{ exactAmount(setting.principal) }}</text
                    ><text class="small muted">{{ asset }}</text></view
                ><view
                    ><text class="small muted">{{ t('Cumulative net earnings') }}</text
                    ><text class="total">{{ exactAmount(setting.net) }}</text
                    ><text class="small muted">{{ asset }}</text></view
                ></view
            ><FormErrors :errors="action.errors.value" />
            <form v-if="view === 'deposit'" class="wealth-form" @submit="openReview">
                <text class="available">{{ available }}</text
                ><SelectField
                    v-model="form.months"
                    :label="t('Wealth term')"
                    :options="
                        setting.products.map((p) => ({
                            value: String(p.months),
                            label:
                                wealthTerm(p.months, exactAmount(p.rate)) +
                                (!p.enabled ? ' · ' + t('Unavailable') : ''),
                        }))
                    "
                    :disabled="review || action.pending.value"
                    @update:model-value="changed"
                /><FormField
                    v-model="form.amount"
                    :label="t('Deposit principal')"
                    type="digit"
                    :disabled="review || action.pending.value"
                    @update:model-value="changed"
                /><text v-if="setting.minimum" class="muted">{{ minimum }}</text
                ><text v-if="!product?.enabled" class="muted">{{
                    t('This wealth product is not available for new deposits.')
                }}</text
                ><button
                    class="primary wide"
                    form-type="submit"
                    :disabled="
                        action.pending.value ||
                        !product?.enabled ||
                        !setting.revision ||
                        review ||
                        !form.amount
                    "
                >
                    {{ t('Review wealth deposit') }}
                </button>
            </form>
            <Modal
                :open="view === 'deposit' && review"
                :title="t('Confirm wealth deposit')"
                :description="reviewDescription"
                :busy="action.pending.value"
                @close="closeReview"
                ><form @submit="submit">
                    <text class="review-copy">{{
                        t(
                            'Redeem principal on the maturity day before midnight in the order timezone. Otherwise, the same principal renews for the same term and rate. Paid interest stays in your wallet.',
                        )
                    }}</text
                    ><text class="review-copy muted">{{
                        t(
                            'No extra interest accrues during the redemption window. Processing delays do not shift the next term.',
                        )
                    }}</text
                    ><WealthNotice /><ConfirmCheck
                        v-model="form.confirmed"
                        :label="t('I confirm the term, interest rate and early withdrawal rules.')"
                        :disabled="action.pending.value"
                    /><view class="review-buttons"
                        ><button
                            class="secondary"
                            :disabled="action.pending.value"
                            @click="closeReview"
                        >
                            {{ t('Back') }}</button
                        ><button
                            class="primary"
                            form-type="submit"
                            :disabled="
                                action.pending.value ||
                                !form.confirmed ||
                                !product?.enabled ||
                                !setting.revision
                            "
                        >
                            {{ t('Confirm wealth deposit') }}
                        </button></view
                    >
                </form></Modal
            ><template v-if="view !== 'deposit'"
                ><view class="records-heading"
                    ><text>{{ t('Wealth deposit records') }}</text
                    ><button
                        v-if="view === 'details'"
                        class="deposit-link"
                        @click="go('/wealth/assets/' + asset + '?view=deposit')"
                    >
                        {{ t('Wealth deposit action') }}
                    </button></view
                ><text v-if="!page.orders.data.length" class="muted">{{
                    t(
                        view === 'withdraw'
                            ? 'No deposits available for early withdrawal.'
                            : 'No wealth deposits yet.',
                    )
                }}</text
                ><view class="order-list"
                    ><view
                        v-for="order in page.orders.data"
                        :key="order.id"
                        class="wealth-record"
                        @click="go('/wealth/orders/' + order.id + '?view=' + view)"
                        ><view class="order-heading"
                            ><text class="order-principal"
                                >{{ exactAmount(order.principal) }}
                                <text class="currency">{{ order.asset }}</text></text
                            ><text
                                class="order-state"
                                :class="{ active: order.displayStatus === 'ACTIVE' }"
                                >{{ wealthState(order.displayStatus) }}</text
                            ></view
                        ><text class="term">{{
                            wealthTerm(order.months, exactAmount(order.rate))
                        }}</text
                        ><text class="small muted"
                            >{{ wealthDate(order.startedAt, order.timezone) }} →
                            {{ wealthDate(order.maturesAt, order.timezone) }}</text
                        ><view class="order-footer"
                            ><text class="small muted">{{ paidLabel(order) }}</text
                            ><UiIcon name="chevron-right" :size="18" /></view></view></view
                ><view class="pagination"
                    ><button
                        v-if="page.orders.prev_page_url"
                        class="text-button"
                        @click="go(page.orders.prev_page_url, true)"
                    >
                        {{ t('Previous') }}</button
                    ><view v-else /><button
                        v-if="page.orders.next_page_url"
                        class="text-button"
                        @click="go(page.orders.next_page_url, true)"
                    >
                        {{ t('Next') }}
                    </button></view
                ></template
            ></view
        ></PageShell
    >
</template>
<style scoped>
.wealth-page :deep(.select-trigger) {
    border-radius: 999px;
    min-height: clamp(48px, 9.6cqw, 72px);
    padding-inline: 20px;
}
.wealth-page {
    display: flex;
    flex-direction: column;
    gap: 20px;
}
.wealth-page > :deep(.select-field) {
    margin: 0;
}
.wealth-totals {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
    padding: 16px;
    background: white;
    border-radius: 12px;
    font-size: 14px;
}
.small {
    display: block;
    font-size: 12px;
    line-height: 20px;
}
.total {
    display: block;
    margin-top: 4px;
    font-size: 18px;
    font-weight: 600;
    overflow-wrap: anywhere;
}
.wealth-form {
    background: white;
    border-radius: 16px;
    padding: 20px;
}
.available {
    display: block;
    font-size: 14px;
    margin-bottom: 16px;
}
.primary,
.secondary {
    min-height: 44px;
    padding: 10px 20px;
    border-radius: 999px;
    font-size: 14px;
    line-height: 24px;
}
.wide {
    width: 100%;
    margin-top: 16px;
}
.review-copy {
    display: block;
    font-size: 14px;
    line-height: 24px;
    margin-bottom: 16px;
}
.review-buttons {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
}
.records-heading {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    font-weight: 600;
}
.deposit-link {
    flex-shrink: 0;
    background: #047857;
    color: white;
    border: 1px solid #047857;
    border-radius: 12px;
    min-height: 44px;
    padding: 8px 20px;
    font-size: 14px;
    line-height: 24px;
    font-weight: 600;
}
.order-list {
    display: flex;
    flex-direction: column;
    gap: 12px;
}
.wealth-record {
    padding: 16px;
    background: white;
    border-radius: 16px;
    border: 1px solid #0000000d;
    box-shadow: 0 1px 2px #0000000d;
}
.order-heading {
    display: flex;
    flex-wrap: wrap;
    align-items: flex-start;
    justify-content: space-between;
    gap: 8px;
}
.order-principal {
    font-size: 20px;
    font-weight: 600;
    overflow-wrap: anywhere;
}
.currency {
    font-size: 14px;
    font-weight: 500;
}
.order-state {
    padding: 4px 10px;
    border-radius: 999px;
    background: #f0f3f1;
    color: #68736e;
    font-size: 12px;
}
.order-state.active {
    background: #ecfdf5;
    color: #065f46;
}
.term {
    display: block;
    margin-top: 12px;
    font-size: 14px;
}
.order-footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    margin-top: 12px;
}
.text-button {
    background: none;
    padding: 12px 0;
    font-size: 14px;
    line-height: 20px;
}
</style>
