// resources/js/components/user/DepositInstructions.tsx
import { assetNetworkLabel } from '@/lib/asset-network';
import { t, dateTime } from '@/i18n';
import { Link } from '@inertiajs/react';
import { QRCodeSVG } from 'qrcode.react';
import { toast } from 'sonner';
import { AssetIcon } from './AssetCenter';
import { Button } from '@/components/ui/button';
import { exactAmount } from '@/lib/exact-amount';
import { useState, useEffect, type ReactNode } from 'react';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
    DialogTrigger,
} from '@/components/ui/dialog';

export function DepositInstructions({
    asset,
    amount,
    network,
    address,
    state,
    expiresAt,
    payable,
    newHref,
    children,
}: {
    asset: string;
    amount: string;
    network?: string | null;
    address?: string | null;
    state: string;
    expiresAt?: string | null;
    payable: boolean;
    newHref: string;
    children?: ReactNode;
}) {
    const [open, setOpen] = useState(true);
    const [now, setNow] = useState(Date.now());
    useEffect(() => {
        const timer = window.setInterval(() => setNow(Date.now()), 1000);
        return () => window.clearInterval(timer);
    }, []);
    const seconds = expiresAt
        ? Math.max(0, Math.floor((new Date(expiresAt).getTime() - now) / 1000))
        : 0;
    const countdown = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;
    const copy = async (value: string, label: string) => {
        try {
            await navigator.clipboard.writeText(value);
            toast.success(t('{{label}} copied', { label: t(label) }));
        } catch {
            toast.error(t('Could not copy. Please select and copy the value manually.'));
        }
    };
    const networkLabel = assetNetworkLabel(network, asset);
    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <section className="space-y-4 rounded-2xl bg-surface p-5">
                <p className="font-semibold">{t(state)}</p>
                <p>
                    {exactAmount(amount)} {asset} · {networkLabel}
                </p>
                <DialogTrigger asChild>
                    <Button className="w-full">{t('View payment instructions')}</Button>
                </DialogTrigger>
                <Link href={newHref} className="block text-center text-sm underline">
                    {t('Start a new request')}
                </Link>
            </section>
            <DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-md">
                <DialogHeader>
                    <DialogTitle>
                        {t('Top up')} · {asset}
                    </DialogTitle>
                    <DialogDescription>
                        {t(
                            'Send the exact amount shown, including all decimals, using {{network}} only. The full amount will be credited with no identification fee; other amounts cannot be credited automatically.',
                            { network: networkLabel ?? '' },
                        )}
                    </DialogDescription>
                </DialogHeader>
                <section className="space-y-4">
                    <div className="flex items-center gap-3">
                        <AssetIcon asset={asset} />
                        <div>
                            <h2 className="font-semibold">{t(state)}</h2>
                            <p className="text-sm text-muted-foreground">
                                {asset} · {networkLabel}
                            </p>
                        </div>
                    </div>
                    <p className="text-xs text-muted-foreground">{t('Amount to send')}</p>
                    <p className="break-all text-3xl font-semibold">
                        {exactAmount(amount)} <span className="text-base">{asset}</span>
                    </p>
                    {payable && seconds > 0 && address ? (
                        <>
                            <div className="mx-auto w-fit rounded-xl bg-white p-3">
                                <QRCodeSVG value={address} size={176} marginSize={4} />
                            </div>
                            <p className="break-all rounded-xl bg-muted p-3 font-mono text-sm">
                                {address}
                            </p>
                            <div className="grid grid-cols-2 gap-3">
                                <Button
                                    variant="secondary"
                                    onClick={() => void copy(address, 'Address')}
                                >
                                    {t('Copy address')}
                                </Button>
                                <Button
                                    variant="secondary"
                                    onClick={() => void copy(exactAmount(amount), 'Amount')}
                                >
                                    {t('Copy amount')}
                                </Button>
                            </div>
                            <div className="space-y-1 rounded-xl bg-muted p-3 text-sm leading-6">
                                <p>
                                    {t(
                                        'After depositing to the address above 👆, your deposit succeeds after 3 network confirmations!',
                                    )}
                                </p>
                                <p>
                                    <Link href="/support" className="underline underline-offset-4">
                                        {t(
                                            'If your deposit has not arrived after 5 minutes, please contact customer support.',
                                        )}
                                    </Link>
                                </p>
                            </div>
                            {children}
                        </>
                    ) : null}
                    <dl className="divide-y text-sm">
                        <div className="flex justify-between py-3">
                            <dt>{t('Network')}</dt>
                            <dd>{networkLabel}</dd>
                        </div>
                        <div className="flex justify-between py-3">
                            <dt>{t('Wallet credit amount')}</dt>
                            <dd>
                                {exactAmount(amount)} {asset}
                            </dd>
                        </div>
                        <div className="flex justify-between py-3">
                            <dt>{t('Time remaining')}</dt>
                            <dd>{countdown}</dd>
                        </div>
                    </dl>
                    {expiresAt && (
                        <p className="text-xs text-muted-foreground">
                            {t('Valid until {{time}}', { time: dateTime(expiresAt) })}
                        </p>
                    )}
                    <Link href={newHref} className="block py-3 text-center text-sm underline">
                        {t('Start a new request')}
                    </Link>
                </section>
            </DialogContent>
        </Dialog>
    );
}

// mobile/uni-app/src/components/DepositInstructions.vue
<script setup lang="ts">
import { ref, computed, onBeforeUnmount } from 'vue';
import { t, dateTime } from '../lib/i18n';
import { go } from '../lib/navigation';
import { exactAmount } from '../generated/exact-amount';
import { assetNetworkLabel } from '../generated/asset-network';
import Modal from './Modal.vue';
import AssetIcon from './AssetIcon.vue';
import QrImage from './QrImage.vue';
const props = defineProps<{
    asset: string;
    amount: string;
    network?: string | null;
    address?: string | null;
    state: string;
    expiresAt?: string | null;
    payable: boolean;
    newHref: string;
}>();
const open = ref(true),
    now = ref(Date.now());
const timer = setInterval(() => (now.value = Date.now()), 1000);
onBeforeUnmount(() => clearInterval(timer));
const seconds = computed(() =>
    props.expiresAt ? Math.max(0, Math.floor((Date.parse(props.expiresAt) - now.value) / 1000)) : 0,
);
const countdown = computed(
    () =>
        String(Math.floor(seconds.value / 60)).padStart(2, '0') +
        ':' +
        String(seconds.value % 60).padStart(2, '0'),
);
const networkLabel = computed(() => assetNetworkLabel(props.network, props.asset));
const description = computed(() =>
    t(
        'Send the exact amount shown, including all decimals, using {{network}} only. The full amount will be credited with no identification fee; other amounts cannot be credited automatically.',
        { network: networkLabel.value ?? '' },
    ),
);
const expires = computed(() =>
    t('Valid until {{time}}', { time: dateTime(props.expiresAt ?? '') }),
);
function copy(value: string, label: string) {
    uni.setClipboardData({
        data: value,
        showToast: false,
        success: () =>
            uni.showToast({ title: t('{{label}} copied', { label: t(label) }), icon: 'none' }),
        fail: () =>
            uni.showToast({
                title: t('Could not copy. Please select and copy the value manually.'),
                icon: 'none',
            }),
    });
}
</script>
<template>
    <view class="deposit-card"
        ><text class="bold">{{ t(state) }}</text
        ><text>{{ exactAmount(amount) }} {{ asset }} · {{ networkLabel }}</text
        ><button class="primary" @click="open = true">{{ t('View payment instructions') }}</button
        ><text class="text-link" @click="go(newHref)">{{ t('Start a new request') }}</text></view
    ><Modal
        :open="open"
        :title="t('Top up') + ' · ' + asset"
        :description="description"
        @close="open = false"
        ><view class="deposit-details"
            ><view class="deposit-status"
                ><AssetIcon :asset="asset" /><view
                    ><text class="bold block">{{ t(state) }}</text
                    ><text class="muted">{{ asset }} · {{ networkLabel }}</text></view
                ></view
            ><text class="small muted">{{ t('Amount to send') }}</text
            ><text class="deposit-amount"
                >{{ exactAmount(amount) }} <text class="currency">{{ asset }}</text></text
            ><template v-if="payable && seconds > 0 && address"
                ><view class="qr"><QrImage :value="address" /></view
                ><text class="address" selectable>{{ address }}</text
                ><view class="copy-buttons"
                    ><button class="secondary" @click="copy(address, 'Address')">
                        {{ t('Copy address') }}</button
                    ><button class="secondary" @click="copy(exactAmount(amount), 'Amount')">
                        {{ t('Copy amount') }}
                    </button></view
                ><view class="deposit-note"
                    ><text>{{
                        t(
                            'After depositing to the address above 👆, your deposit succeeds after 3 network confirmations!',
                        )
                    }}</text
                    ><text class="text-link" @click="go('/support')">{{
                        t(
                            'If your deposit has not arrived after 5 minutes, please contact customer support.',
                        )
                    }}</text></view
                ></template
            ><view class="deposit-meta"
                ><view
                    ><text>{{ t('Network') }}</text
                    ><text>{{ networkLabel }}</text></view
                ><view
                    ><text>{{ t('Wallet credit amount') }}</text
                    ><text>{{ exactAmount(amount) }} {{ asset }}</text></view
                ><view
                    ><text>{{ t('Time remaining') }}</text
                    ><text>{{ countdown }}</text></view
                ></view
            ><text v-if="expiresAt" class="small muted">{{ expires }}</text
            ><text class="text-link" @click="go(newHref)">{{
                t('Start a new request')
            }}</text></view
        ></Modal
    >
</template>
<style scoped>
.deposit-card {
    display: flex;
    flex-direction: column;
    gap: 16px;
    padding: 20px;
    background: #fff;
    border-radius: 16px;
}
.bold {
    font-weight: 600;
}
.block {
    display: block;
}
.deposit-details {
    display: flex;
    flex-direction: column;
    gap: 16px;
}
.deposit-status {
    display: flex;
    align-items: center;
    gap: 12px;
}
.small {
    font-size: 12px;
}
.deposit-amount {
    font-size: 30px;
    font-weight: 600;
    overflow-wrap: anywhere;
    line-height: 36px;
}
.currency {
    font-size: 16px;
}
.qr {
    margin: 0 auto;
    padding: 12px;
    background: white;
    border-radius: 12px;
}
.address {
    display: block;
    overflow-wrap: anywhere;
    background: #f0f3f1;
    border-radius: 12px;
    padding: 12px;
    font-family: monospace;
    font-size: 14px;
}
.copy-buttons {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
}
.copy-buttons button {
    line-height: 24px;
    min-height: 44px;
    padding: 10px;
    font-size: 14px;
}
.deposit-note {
    display: flex;
    flex-direction: column;
    gap: 4px;
    background: #f0f3f1;
    border-radius: 12px;
    padding: 12px;
    font-size: 14px;
    line-height: 24px;
}
.text-link {
    display: block;
    text-decoration: underline;
    text-underline-offset: 4px;
    font-size: 14px;
    text-align: center;
}
.deposit-note .text-link {
    text-align: left;
}
.deposit-meta > view {
    display: flex;
    justify-content: space-between;
    gap: 12px;
    padding: 12px 0;
    font-size: 14px;
    border-bottom: 1px solid #e2e7e4;
}
.deposit-meta > view:last-child {
    border: 0;
}
.deposit-meta > view > text:last-child {
    text-align: right;
    overflow-wrap: anywhere;
}
</style>
