// resources/js/components/user/PaidPromotionSummary.tsx
import { useState } from 'react';
import { ChevronDown } from 'lucide-react';
import {
    commissionSum,
    promotionMoney,
    promotionTableAmount,
    promotionLevel,
} from '@/lib/paid-promotion';
import { Link } from '@inertiajs/react';
import { t, dateTime } from '@/i18n';
import { exactAmount } from '@/lib/exact-amount';

export type PaidLevel = {
    id: string;
    rank: number;
    fee: string;
    percent: number;
    reward: string;
    target: number;
    revision: number;
    enabled: boolean;
};
type Cell = { count: number; amount: string; minimum: string; maximum: string };
export type PaidClaim = {
    id: string;
    rank: number;
    amount: string;
    status: string;
    target: number;
    direct: number;
    indirect: number;
    createdAt: string;
    reviewedAt: string | null;
    reason: string | null;
};
export type PaidPromotionData = {
    membershipStatus: 'NONE' | 'ACTIVE' | 'EXPIRED';
    previousCycle: { rank: number; endsAt: string } | null;
    availableBalance: string;
    levels: PaidLevel[];
    rank: number;
    percent: number;
    reward: string;
    cycle: { id: string; startsAt: string; endsAt: string; tariff: string } | null;
    progress: {
        direct: number;
        indirect: number;
        target: number;
        paid: string;
        returned: string;
        remaining: string;
    } | null;
    claimsPage: number;
    hasMoreClaims: boolean;
    pending: boolean;
    claims: PaidClaim[];
    tables: Record<'ANNUAL' | 'ACTIVATION', { rank: number; direct: Cell; indirect: Cell }[]>;
    totals: Record<'ANNUAL' | 'ACTIVATION', string>;
    legacy: string;
    teamByLevel: { rank: number; direct: number; indirect: number }[];
    directPeople: number;
    indirectPeople: number;
};
const price = (cell: Cell) =>
    cell.minimum === cell.maximum
        ? exactAmount(cell.minimum)
        : `${exactAmount(cell.minimum)}–${exactAmount(cell.maximum)}`;

export function PaidPromotionMembership({ paid: p }: { paid: PaidPromotionData }) {
    const action =
        p.rank >= 8
            ? 'View benefits'
            : p.membershipStatus === 'EXPIRED'
              ? 'Renew level'
              : p.rank > 0
                ? 'Upgrade level'
                : 'Apply for level';
    return (
        <section aria-labelledby="membership-title" className="rounded-xl bg-[#faf5e7] px-4 py-3">
            <div className="flex items-center justify-between gap-3">
                <h2
                    id="membership-title"
                    className="min-w-0 flex-1 break-words text-sm font-semibold"
                >
                    <span className="text-xs font-normal text-muted-foreground">
                        {t('My level')}:{' '}
                    </span>
                    {promotionLevel(p.rank)}
                </h2>
                <Link
                    href="/promotion/membership"
                    className="flex min-h-11 max-w-[42%] shrink-0 items-center justify-center rounded-full border border-[#a58c4c] px-3 py-2 text-center text-xs font-medium text-[#254235]"
                >
                    {t(action)}
                </Link>
            </div>
            {p.cycle && (
                <p className="mt-1 text-xs text-muted-foreground">
                    {t('Valid until {{time}}', { time: dateTime(p.cycle.endsAt) })}
                </p>
            )}
            {p.membershipStatus === 'EXPIRED' && p.previousCycle && (
                <p className="mt-1 text-xs text-muted-foreground">
                    {t(
                        'Your previous level expired on {{time}}. Ordinary member rewards now apply.',
                        { time: dateTime(p.previousCycle.endsAt) },
                    )}
                </p>
            )}
        </section>
    );
}

export function PaidPromotionSummary({ paid: p }: { paid: PaidPromotionData }) {
    const [showAll, setShowAll] = useState(true);
    const [expanded, setExpanded] = useState<number | null>(null);
    const rows = p.tables.ACTIVATION.map((activation) => {
        const annual = p.tables.ANNUAL.find((row) => row.rank === activation.rank)!;
        const people = p.teamByLevel.find((row) => row.rank === activation.rank)!;
        return {
            rank: activation.rank,
            directPeople: people.direct,
            indirectPeople: people.indirect,
            annual,
            activation,
            annualAmount: commissionSum(annual.direct.amount, annual.indirect.amount),
            activationAmount: commissionSum(activation.direct.amount, activation.indirect.amount),
            hasRecords: [
                annual.direct,
                annual.indirect,
                activation.direct,
                activation.indirect,
            ].some((c) => c.count > 0 || !/^0(?:\.0+)?$/.test(c.amount)),
        };
    });
    const visible = rows.filter(
        (row) => showAll || row.hasRecords || row.directPeople > 0 || row.indirectPeople > 0,
    );
    return (
        <section
            className="min-w-0 rounded-2xl border border-border/60 bg-surface px-3 py-4 sm:p-5"
            id="team-summary"
        >
            <div className="mb-3 flex items-center justify-between gap-2">
                <h2 className="min-w-0 text-base font-semibold">{t('Reward breakdown')}</h2>
                <button
                    className="ml-auto min-h-11 min-w-0 text-xs underline"
                    onClick={() => setShowAll(!showAll)}
                    aria-expanded={showAll}
                >
                    {t(showAll ? 'Show populated levels' : 'Show all levels')}
                </button>
                <p className="shrink-0 whitespace-nowrap text-[11px] text-muted-foreground">
                    {t('Amounts in USDT')}
                </p>
            </div>
            <table className="w-full table-fixed text-right text-[11px] sm:text-sm">
                <caption className="sr-only">{t('Team members and commissions by level')}</caption>
                <colgroup>
                    <col className="w-[24%]" />
                    <col className="w-[13%]" />
                    <col className="w-[13%]" />
                    <col className="w-[25%]" />
                    <col className="w-[25%]" />
                </colgroup>
                <thead>
                    <tr className="border-b">
                        {[
                            'Level',
                            'Direct members',
                            'Indirect members',
                            'Annual fee commission',
                            'Activation commission',
                        ].map((label) => (
                            <th
                                key={label}
                                scope="col"
                                className="break-words whitespace-pre-line px-1 py-3 align-bottom font-medium first:text-left"
                            >
                                {t(label)}
                            </th>
                        ))}
                    </tr>
                </thead>
                {visible.map((row) => (
                    <tbody key={row.rank} data-reward-rank={row.rank}>
                        <tr className="border-b">
                            <th scope="row" className="px-1 py-1 text-left font-normal">
                                <button
                                    onClick={() =>
                                        setExpanded(expanded === row.rank ? null : row.rank)
                                    }
                                    aria-expanded={expanded === row.rank}
                                    aria-controls={`reward-detail-${row.rank}`}
                                    className="flex min-h-12 w-full items-center justify-between gap-1 py-2 text-left"
                                >
                                    <span className="min-w-0 break-words">
                                        {promotionLevel(row.rank)}
                                    </span>
                                    <ChevronDown
                                        className={`size-3 shrink-0 ${expanded === row.rank ? 'rotate-180' : ''}`}
                                    />
                                </button>
                            </th>
                            <td className="break-all px-1 py-3 tabular-nums">{row.directPeople}</td>
                            <td className="break-all px-1 py-3 tabular-nums">
                                {row.indirectPeople}
                            </td>
                            <td className="break-all px-1 py-3 tabular-nums">
                                {row.rank ? promotionTableAmount(row.annualAmount) : '—'}
                            </td>
                            <td className="break-all px-1 py-3 tabular-nums">
                                {promotionTableAmount(row.activationAmount)}
                            </td>
                        </tr>
                        <tr hidden={expanded !== row.rank} id={`reward-detail-${row.rank}`}>
                            <td colSpan={5} className="pb-4 text-left">
                                <div className="mt-4 space-y-5 rounded-xl bg-muted/40 p-3">
                                    {(['ANNUAL', 'ACTIVATION'] as const).map((kind) => {
                                        const annual = kind === 'ANNUAL';
                                        const data = annual ? row.annual : row.activation;
                                        return (
                                            <section key={kind} className="space-y-3">
                                                <h4 className="text-sm font-medium">
                                                    {t(
                                                        annual
                                                            ? 'Annual fee commission'
                                                            : 'Activation commission',
                                                    )}
                                                </h4>
                                                {annual && row.rank === 0 ? (
                                                    <p className="text-xs text-muted-foreground">
                                                        {t(
                                                            'Ordinary members do not earn annual fee commission.',
                                                        )}
                                                    </p>
                                                ) : (
                                                    <>
                                                        {(['direct', 'indirect'] as const).map(
                                                            (relation) => {
                                                                const cell = data[relation];
                                                                return (
                                                                    <div
                                                                        key={relation}
                                                                        className="space-y-1 text-xs"
                                                                    >
                                                                        <p>
                                                                            {t(
                                                                                relation ===
                                                                                    'direct'
                                                                                    ? 'Direct'
                                                                                    : 'Indirect',
                                                                            )}{' '}
                                                                            ·{' '}
                                                                            {t(
                                                                                annual
                                                                                    ? '{{count}} paid orders'
                                                                                    : '{{count}} funding events',
                                                                                {
                                                                                    count: cell.count,
                                                                                },
                                                                            )}
                                                                        </p>
                                                                        {!annual && (
                                                                            <p className="text-muted-foreground">
                                                                                {t(
                                                                                    relation ===
                                                                                        'direct'
                                                                                        ? 'Unit price'
                                                                                        : 'Difference',
                                                                                )}
                                                                                :{' '}
                                                                                {cell.count
                                                                                    ? price(cell) +
                                                                                      ' USDT'
                                                                                    : '—'}
                                                                            </p>
                                                                        )}
                                                                        <p className="break-words font-medium">
                                                                            {promotionMoney(
                                                                                cell.amount,
                                                                            )}
                                                                        </p>
                                                                    </div>
                                                                );
                                                            },
                                                        )}
                                                        <Link
                                                            className="inline-flex min-h-11 items-center text-xs underline"
                                                            href={`/promotion/rewards?kind=${kind}&rank=${row.rank}`}
                                                        >
                                                            {t('View records')}
                                                        </Link>
                                                    </>
                                                )}
                                            </section>
                                        );
                                    })}
                                </div>
                            </td>
                        </tr>
                    </tbody>
                ))}
                {!visible.length && (
                    <tbody>
                        <tr>
                            <td
                                colSpan={5}
                                className="py-6 text-center text-sm text-muted-foreground"
                            >
                                {t('No team members or reward records yet.')}
                            </td>
                        </tr>
                    </tbody>
                )}
            </table>
            <p className="mt-3 text-[11px] leading-5 text-muted-foreground">
                {t('Members: current level. Commission: level at the time earned.')}
            </p>
            <details className="text-xs leading-5 text-muted-foreground">
                <summary className="cursor-pointer py-2">{t('Statistics notes')}</summary>
                <p>
                    {t(
                        'Member counts use current valid levels; commission uses historical event levels. Do not multiply current member counts by current reward rates.',
                    )}
                </p>
                <p>
                    {t('Select a level for actual award records. Ranges reflect historical rates.')}
                </p>
            </details>
        </section>
    );
}

// mobile/uni-app/src/components/PaidPromotionSummary.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import UiIcon from './UiIcon.vue';
import { locale, t } from '../lib/i18n';
import { go } from '../lib/navigation';
import { exactAmount } from '../generated/exact-amount';
import {
    commissionSum,
    promotionMoney,
    promotionTableAmount,
    promotionLevel,
} from '../lib/promotion';
import type { PaidPromotionData } from '../lib/promotion-types';
const props = defineProps<{ paid: PaidPromotionData }>(),
    showAll = ref(true),
    expanded = ref<number | null>(null),
    notes = ref(false);
const rows = computed(() =>
    props.paid.tables.ACTIVATION.map((activation) => {
        const annual = props.paid.tables.ANNUAL.find((r) => r.rank === activation.rank)!,
            people = props.paid.teamByLevel.find((r) => r.rank === activation.rank)!;
        return {
            rank: activation.rank,
            directPeople: people.direct,
            indirectPeople: people.indirect,
            ANNUAL: annual,
            ACTIVATION: activation,
            annualAmount: commissionSum(annual.direct.amount, annual.indirect.amount),
            activationAmount: commissionSum(activation.direct.amount, activation.indirect.amount),
            hasRecords: [
                annual.direct,
                annual.indirect,
                activation.direct,
                activation.indirect,
            ].some((c) => c.count > 0 || !/^0(?:\.0+)?$/.test(c.amount)),
        };
    }),
);
const visible = computed(() =>
    rows.value.filter(
        (r) => showAll.value || r.hasRecords || r.directPeople > 0 || r.indirectPeople > 0,
    ),
);
const kinds = ['ANNUAL', 'ACTIVATION'] as const,
    relations = ['direct', 'indirect'] as const;
function count(kind: string, value: number) {
    return t(
        kind === 'ANNUAL' ? '{{count}} paid orders' : '{{count}} ordinary member activations',
        { count: value },
    );
}
function price(cell: { minimum: string; maximum: string }) {
    return cell.minimum === cell.maximum
        ? exactAmount(cell.minimum)
        : exactAmount(cell.minimum) + '–' + exactAmount(cell.maximum);
}
function tableHeading(label: string) {
    const translated = t(label);
    return locale.value === 'zh-CN' && label !== 'Level'
        ? translated.replace(/\s/g, '').replace(/^(.{2})(.{2})$/, '$1\n$2')
        : translated;
}
</script>
<template>
    <view class="summary"
        ><view class="heading"
            ><text>{{ t('Reward breakdown') }}</text
            ><button @click="showAll = !showAll">
                {{ t(showAll ? 'Show populated levels' : 'Show all levels') }}</button
            ><text class="unit muted">{{ t('Amounts in USDT') }}</text></view
        ><view class="table-head table-row"
            ><text
                v-for="label in [
                    'Level',
                    'Direct members',
                    'Indirect members',
                    'Annual fee commission',
                    'Activation commission',
                ]"
                :key="label"
                >{{ tableHeading(label) }}</text
            ></view
        ><view v-for="row in visible" :key="row.rank"
            ><view class="table-row"
                ><button
                    :aria-expanded="expanded === row.rank"
                    @click="expanded = expanded === row.rank ? null : row.rank"
                >
                    <text class="level-label">{{ promotionLevel(row.rank) }}</text>
                    <UiIcon
                        name="chevron-down"
                        :size="12"
                        :class="{ 'level-expanded': expanded === row.rank }"
                    /></button
                ><text>{{ row.directPeople }}</text
                ><text>{{ row.indirectPeople }}</text
                ><text>{{ row.rank ? promotionTableAmount(row.annualAmount) : '—' }}</text
                ><text>{{ promotionTableAmount(row.activationAmount) }}</text></view
            ><view v-if="expanded === row.rank" class="detail"
                ><view v-for="kind in kinds" :key="kind"
                    ><text class="detail-title">{{
                        t(kind === 'ANNUAL' ? 'Annual fee commission' : 'Activation commission')
                    }}</text
                    ><text v-if="kind === 'ANNUAL' && row.rank === 0" class="small muted">{{
                        t('Ordinary members do not earn annual fee commission.')
                    }}</text
                    ><template v-else
                        ><view v-for="relation in relations" :key="relation" class="cell"
                            ><text
                                >{{ t(relation === 'direct' ? 'Direct' : 'Indirect') }} ·
                                {{ count(kind, row[kind][relation].count) }}</text
                            ><text v-if="kind !== 'ANNUAL'" class="muted"
                                >{{ t(relation === 'direct' ? 'Unit price' : 'Difference') }}:
                                {{
                                    row[kind][relation].count
                                        ? price(row[kind][relation]) + ' USDT'
                                        : '—'
                                }}</text
                            ><text class="strong">{{
                                promotionMoney(row[kind][relation].amount)
                            }}</text></view
                        ><button
                            class="records"
                            @click="go('/promotion/rewards?kind=' + kind + '&rank=' + row.rank)"
                        >
                            {{ t('View records') }}
                        </button></template
                    ></view
                ></view
            ></view
        ><text v-if="!visible.length" class="empty muted">{{
            t('No team members or reward records yet.')
        }}</text
        ><text class="note muted">{{
            t('Members: current level. Commission: level at the time earned.')
        }}</text
        ><button class="notes-button muted" @click="notes = !notes">
            {{ notes ? '−' : '+' }} {{ t('Statistics notes') }}</button
        ><view v-if="notes" class="note muted"
            ><text>{{
                t(
                    'Member counts use current valid levels; commission uses historical event levels. Do not multiply current member counts by current reward rates.',
                )
            }}</text
            ><text>{{
                t('Select a level for actual award records. Ranges reflect historical rates.')
            }}</text></view
        ></view
    >
</template>
<style scoped>
.summary {
    border: 1px solid #e1e7dd;
    border-radius: 16px;
    padding: 16px 12px;
    background: white;
    min-width: 0;
}
.heading {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
    margin-bottom: 12px;
    font-size: 16px;
    font-weight: 600;
}
.heading button {
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 44px;
    font-size: 12px;
    line-height: 18px;
    text-decoration: underline;
    background: none;
    padding: 0;
    margin: 0 0 0 auto;
    min-width: 0;
}
.unit {
    font-size: 11px;
    white-space: nowrap;
    font-weight: 400;
}
.table-row {
    display: grid;
    grid-template-columns: 24% 13% 13% 25% 25%;
    border-bottom: 1px solid #e1e7dd;
    align-items: center;
    font-size: 11px;
    line-height: 18px;
}
.table-row > text {
    padding: 12px 4px;
    overflow-wrap: anywhere;
    text-align: right;
}
.table-row > text:first-child {
    text-align: left;
}
.table-head {
    align-items: end;
    font-weight: 500;
}
.table-head > text {
    white-space: pre-line;
}
.table-row > button {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 4px;
    background: none;
    min-height: 48px;
    width: 100%;
    font-size: 11px;
    line-height: 18px;
    margin: 0;
    padding: 8px 4px;
    text-align: left;
    overflow-wrap: anywhere;
}
.level-label {
    min-width: 0;
}
.level-expanded {
    transform: rotate(180deg);
}
.detail {
    margin: 16px 0;
    padding: 12px;
    border-radius: 12px;
    background: #f0f3f166;
    display: flex;
    flex-direction: column;
    gap: 20px;
}
.detail-title {
    display: block;
    font-size: 14px;
    line-height: 22px;
    font-weight: 500;
    margin-bottom: 12px;
}
.cell {
    font-size: 12px;
    line-height: 20px;
    margin-top: 12px;
}
.cell text {
    display: block;
    margin-top: 4px;
    overflow-wrap: anywhere;
}
.strong {
    font-weight: 500;
}
.small {
    font-size: 12px;
    line-height: 20px;
}
.records {
    min-height: 44px;
    font-size: 12px;
    line-height: 20px;
    text-decoration: underline;
    background: none;
    padding: 12px 0;
    margin: 0;
    text-align: left;
}
.empty {
    display: block;
    text-align: center;
    font-size: 14px;
    padding: 24px 0;
}
.note {
    display: block;
    font-size: 11px;
    line-height: 20px;
    margin-top: 12px;
}
.note text {
    display: block;
}
.notes-button {
    font-size: 12px;
    line-height: 20px;
    background: none;
    padding: 8px 0;
    margin: 0;
    text-align: left;
}
@media (min-width: 640px) {
    .summary {
        padding: 20px;
    }
    .table-row,
    .table-row > button {
        font-size: 14px;
        line-height: 22px;
    }
}
</style>
