// mobile/uni-app/src/components/PreviewImage.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { photoUrl } from '../lib/api';
import { t } from '../lib/i18n';
const props = defineProps<{ src: string; sources?: string[]; mode?: 'aspectFit' | 'widthFix' | 'aspectFill'; preview?: boolean }>();
const candidates = computed(() => [...new Set([props.src, ...(props.sources ?? [])].filter(Boolean).map(value => photoUrl(value) || value))]);
const index = ref(0);
watch(() => JSON.stringify(candidates.value), () => { index.value = 0; });
function open() {
    const current = candidates.value[index.value];
    if (props.preview && current) uni.previewImage({ urls: [current], current });
}
</script>
<template>
    <image v-if="index < candidates.length" :key="candidates[index]" :src="candidates[index]" :mode="mode ?? 'aspectFit'" @error="index++" @click="open" />
    <text v-else role="button" @click.stop="index = 0">{{ t('Image failed to load. Click to retry.') }}</text>
</template>

// resources/js/components/shared/PreviewImage.tsx
import { useState, type ImgHTMLAttributes } from 'react';
import { t } from '@/i18n/admin';

type Props = ImgHTMLAttributes<HTMLImageElement> & { sources?: string[] };
export function PreviewImage({ sources = [], src, ...props }: Props) {
    const candidates = [
        ...new Set([src, ...sources].filter((value): value is string => Boolean(value))),
    ];
    return <ImageAttempt key={JSON.stringify(candidates)} candidates={candidates} {...props} />;
}
function ImageAttempt({
    candidates,
    ...props
}: Omit<Props, 'src' | 'sources'> & { candidates: string[] }) {
    const [index, setIndex] = useState(0);
    if (index >= candidates.length)
        return (
            <span
                role="button"
                tabIndex={0}
                className="cursor-pointer text-sm text-muted-foreground"
                onClick={(event) => {
                    event.stopPropagation();
                    setIndex(0);
                }}
                onKeyDown={(event) => {
                    if (event.key === 'Enter' || event.key === ' ') {
                        event.preventDefault();
                        event.stopPropagation();
                        setIndex(0);
                    }
                }}
            >
                {t('Image failed to load. Click to retry.')}
            </span>
        );
    return (
        <img
            {...props}
            key={candidates[index]}
            src={candidates[index]}
            onError={() => setIndex((value) => (value === index ? value + 1 : value))}
        />
    );
}
